### ISSUE TITLE
0.3.3 crashes

### ISSUE THREAD

**Issue by swratten** [jellyfin/jellyfin-kodi#114]
**Describe the bug**
Fresh install of Kodi Leia on multiple machines. 
Install Jellyfin plugin 0.3.3, Jellyfin plugin crashes as soon as it starts. I get no login prompt or manual server add dialog.

 - OS: Xbox One, MacOS Yosemite, Manjaro Linux 18.0
 - Jellyfin Version: 10.3.7
 - Kodi Version: 18.4
 - Addon Version: 0.3.3

**Comment by mcarlton00** [comment]
Likely fixed by #109.  Try upgrading to 0.3.4 instead

**Comment by swratten** [comment]
Just went through the logs and it said "ImportError: No module named ipaddress"
The repository doesn't show 0.3.4 available at the moment in kodi

**Comment by swratten** [comment]
> Likely fixed by #109. Try upgrading to 0.3.4 instead

yeah that pr looks like the problem

**Comment by mcarlton00** [comment]
You can manually refresh the repo by going to `Settings -> Add-ons -> My Add-ons -> Add-on Repository`, right click the Jellyfin repo, and "Check for updates"

**Comment by swratten** [comment]
> You can manually refresh the repo by going to `Settings -> Add-ons -> My Add-ons -> Add-on Repository`, right click the Jellyfin repo, and "Check for updates"

Thanks seems to fix this problem :)

**Comment by oddstr13** [comment]
Duplicate of #108
