### ISSUE TITLE
Cannot load settings from kodi

### ISSUE THREAD

**Issue by TrueTechy** [jellyfin/jellyfin-kodi#116]
**Describe the bug**
There's a few logs I've seen now and only those with debug enabled where there's dozens of lines relating to being unable to load the addons settings 

**Logs**
Snippet example, no specific reasons is given in the error or in the surrounding logs
```
DEBUG: CAddonSettings[plugin.video.jellyfin]: loading setting definitions
DEBUG: CAddonSettings[plugin.video.jellyfin]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[plugin.video.jellyfin]: loading setting values
DEBUG: CSettingsManager: requested setting (MinimumSetup) was not found.
DEBUG: CAddonSettings[plugin.video.jellyfin]: failed to find definition for setting MinimumSetup. Creating a setting on-the-fly...
```

**System (please complete the following information):**
 - OS: Android, maybe others
 - Jellyfin Version: any
 - Kodi Version: 18.4
 - Addon Version: 0.3.4, but seen on earlier version as well

**Comment by oddstr13** [comment]
I've seen those too, but haven't bothered looking into it yet, as it seems to be "working" as-is

**Comment by z3ntu** [comment]
The PR https://github.com/xbmc/xbmc/pull/17822 removes the logging in kodi.

**Comment by mcarlton00** [comment]
Thanks for the update.  Always nice when something gets fixed for us
