### ISSUE TITLE
Popups for managing libraries all have the same title

### ISSUE THREAD

**Issue by TrueTechy** [jellyfin/jellyfin-kodi#121]
**Describe the bug**
All the popups which are used to manage the libraries after setup all have the same title

**To Reproduce**
1. Within the addon, Go to manage libraries
2. Click on any of the library options that isn't add libraries
3. Note that all titles say "Select the libraries to add"

**Expected behavior**
Titles reflect the action being taken

**System (please complete the following information):**
 - OS: Any
 - Jellyfin Version: Any
 - Kodi Version: 18.3 and 18.4 tested
 - Addon Version: 0.3.4

**Comment by therealmelee** [comment]
You beat me to submitting this by one day 👍
