### ISSUE TITLE
Music content is synced to Kodi from deselected libraries

### ISSUE THREAD

**Issue by therealmelee** [jellyfin/jellyfin-kodi#122]
Discussed on this reddit thread: https://www.reddit.com/r/jellyfin/comments/dfdafp/kodi_addon_ignores_or_syncs_wrong_libraries/

**Describe the bug**
When importing music libraries, the way the addon seems to extract from Jellyfin database results in content not in the selected library being pulled over.

**To Reproduce**
Populate multiple music libraries. Compilation albums seem to be the main contributor to the issue.

```
Library A
\
  - Artist A
  \
    - Album 1
    \ - Title

Library B
  - Album 2
  \
    \  - Artist A - Title
       - Artist B - Title
       - Artist C - Title
```

In Jellyfin for Kodi, select only Library A to be imported.

**Expected behavior**
Kodi should only import content actually included in the Libraries selected.

**Actual behavior**
Artists, Albums and Tracks from content not existing in the selected libraries is synced over to Kodi. In the above example, not only does the track from Artist A on Album 2 get synced, but the entirety of Album 2 is pulled over as well.

When the sync is occurring you can follow in the top-right and see the Artist / Album / Title being copied over. It seems that even if Artist A only appears in one track on an album, it pulls over the entire album e.g. "Bee Gees / Now That's What I Call Music X / [every single track]". As a side note, this may also be causing significant performance loss because the same album is pulled multiple times, once for each unique artist that appears in the album.

**System (please complete the following information):**
 - OS: NVIDIA Shield TV 8.0.1
 - Jellyfin Version: 10.4.0
 - Kodi Version: 18.4
 - Addon Version: 0.3.4

**Comment by mcarlton00** [comment]
Unfortunately, this seems to be a limitation of the API right now.  I'm pretty sure I can code around it, though.  Quick question though: Can you confirm that you're seeing this in the Web client as well? My test filestructure right now is:
```
- Library1
  - ArtistA
    - AlbumA
    - AlbumB
- Library2
  - ArtistA
    - AlbumC
    - AlbumD
```
And if I browse to just `ArtistA` in the web client in either library, I get a list of all 4 albums

**Comment by therealmelee** [comment]
Yes, that's correct. That doesn't directly match my use case / what my libraries look like, but for the one artist I know that would be the case for 'W.A. Mozart', I do indeed see albums in the 'Albums' listing (not 'Also appears on' - I think that wouldn't be a problem) that extend beyond the library I initially clicked into.

Removing access to the other library immediately fixes it and I only see what I would expect to see.

**Comment by therealmelee** [comment]
Fantastic work! Great job thank you! The performance improvements quoted are remarkable!

**Comment by mcarlton00** [comment]
I can't promise that it's 100% fixed, but just judging by the API calls it _should_ be fixed.  We're hoping for another release this coming week, so we'll find out soon(ish)
