### ISSUE TITLE
unable to add jellyfin server to kodi addon

### ISSUE THREAD

**Issue by Darkmagister** [jellyfin/jellyfin-kodi#134]
**Describe the bug**

i've installed this kodi addons to add jellyfin server but i'm unable to connect to the server
i've tried with jellyfin 10.4.0 and 10.4.1, with kodi 18.3 and 19 with version 0.3.4 and 0.3.3 of the anddon
but still nothing, i'm using the android app to connect to the server on the same lan as kodi and it's working normaly there

**To Reproduce**

add server address, i've tried http port, https port but when i press update server information i get an error, to check kodi log

**Logs**

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'str' object has no attribute 'decode'
                                            Traceback (most recent call last):
                                              File "/home/astr/.kodi/addons/plugin.video.jellyfin/default.py", line 15, in <module>
                                                __base__ = xbmc.translatePath(os.path.join(__addon__.getAddonInfo('path'), 'resources', 'lib')).decode('utf-8')
                                            AttributeError: 'str' object has no attribute 'decode'
                                            -->End of Python script error report<--
2019-11-04 21:28:04.916 T:22927   ERROR: Previous line repeats 1 times.
```

**System:**
 - OS: linux 64 bit
 - Jellyfin Version: 10.4.1
 - Kodi Version: 18.3 and 19
 - Addon Version: 0.3.4

**Comment by TrueTechy** [comment]
Have you tried using the initial setup wizard instead of the settings screen? If you start the addon(or kodi) with no server configured it should pop up automatically. I've never had much success configuring through the settings screen.

If it doesn't pop up automatically you can trigger it to pop up in the addon menu by clicking on "Add Server"

**Comment by rinasek** [comment]
I am having the same issue since updating jellyfin docker containers yesterday morning. I could not update library, but could play existing videos. 

After removing the server i am not able to add it back. It just gets stays on connecting to .....

**Comment by TrueTechy** [comment]
@rinasek If you updated to the server version 10.4.1 then you might've gotten the base URL issue. If you never had one before the server might've added /jellyfin to the base URL config in the server settings. if you don't want this you can remove it from there and kodi should connect to the server

**Comment by rinasek** [comment]
@TrueTechy That was the problem! Not sure how i managed to miss it, was watching things today via browser... thanks!

**Comment by oddstr13** [comment]
`AttributeError: 'str' object has no attribute 'decode'` is a Python 3 error, I'm assuming that log is extracted from Kodi 19?

**Comment by Darkmagister** [comment]
yes the baseurl Is ok now and that is not the issue, yes I have kodi19 now and yes the logo is from that version, this add-ons it's not compatible with python3?

**Comment by TrueTechy** [comment]
The addon is not currently python3 compatible no

**Comment by oddstr13** [comment]
> yes the baseurl Is ok now and that is not the issue, yes I have kodi19 now and yes the logo is from that version, this add-ons it's not compatible with python3?

We have not yet started looking at what changes are needed for Python 2+3 compat, nor what is needed for Kodi 19.

As evident from the stacktrace you provided, we are not yet Python 3 compatible - thanks for actually confirming this (even tho I had a feeling this was the case).

Do you know if there is a timeline for when Kodi 19 will get released?

**Comment by Darkmagister** [comment]
> Do you know if there is a timeline for when Kodi 19 will get released?

from what i know they are trying to finish before 1 jan 2020 as the end of life of python 2

[https://kodi.tv/article/kodi-19-python-3-goes-live](url)

i've updated to kodi 19 as kodi 18 also was not working, now i'll wait for all the module to update to python 3 and kodi 19 and try again later ;)
