### ISSUE TITLE
Does this add-on support KODI 16.1 ?

### ISSUE THREAD

**Issue by zhyf1019** [jellyfin/jellyfin-kodi#147]
Does this add-on support KODI 16.1 ?

Download the repository installer here
It will be saved as repository.jellyfin.kodi.zip
Install the Jellyfin repository
Open Kodi and navigate to "Add-on Browser"
Select "Install from zip file"
If prompted, enter settings and enable "Unknown Sources", then go back
Select the newly downloaded file and it will be installed
Install Jellyfin for Kodi
From within Kodi, navigate back to "Add-on Browser"
Select "Install from repository"
Choose "Kodi Jellyfin Addons"
"Video Add-ons" 
**Select the Jellyfin add-on and choose install**   

when i move to last step ,   There's no add-on in the list
Does this add-on support KODI 16.1 ?

**Comment by oddstr13** [comment]
We currently support Kodi 17 and 18
