### ISSUE TITLE
Missing prompt for server-details

### ISSUE THREAD

**Issue by vdot0x23** [jellyfin/jellyfin-kodi#168]
**Describe the bug**
Missing initial setup prompt for my server-details.

**To Reproduce**
1. Install Jellyfin repo
2. Install Jellyfin for Kodi
3. Wait for prompt

**Expected behavior**
I would expect a prompt as written in the docs
> Within a few seconds you should be prompted for your server-details.

**System (please complete the following information):**
 - OS: NixOS
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.5
 - Addon Version: 0.4.0

**Additional context**
I am running Kodi and Jellyfin on the same host and bare-metal (ie. not virtualized or containerized).
When the addon is open, only the following buttons react when clicking them:
- Settings
- Perform local database reset
- Restart Jellyfin for Kodi
- Manage libraries

The other buttons that do not react are:
- Add server
- Add user to session

EDIT: Kodi version was actually 18.5

**Comment by oddstr13** [comment]
Could you please provide the Kodi logs? Preferrably with debug logging enabled in the *Jellyfin for Kodi* addon settings.

**Comment by vdot0x23** [comment]
Yes, here it is https://gist.github.com/vdot0x23/b8c0ee4455080898cbd203fc62633a9a :)
I found the lines below quite interesting.
```
2019-12-20 17:21:34.041 T:139630078306048  NOTICE: JELLYFIN.service -> ERROR::service.py:54 [Errno 13] Permission denied: u'/home/tv/.kodi/userdata/profiles/guest/library/video/movies/index.xml'
                                            Traceback (most recent call last):
                                              File "service.py", line 47, in run
                                                service = Service()
                                              File "jellyfin_kodi/entrypoint/service.py", line 70, in __init__
                                                verify_kodi_defaults()
                                              File "jellyfin_kodi/views.py", line 130, in verify_kodi_defaults
                                                write_xml(etree.tostring(xml, 'UTF-8'), file)
                                              File "jellyfin_kodi/helper/utils.py", line 294, in write_xml
                                                with open(file, 'w') as infile:
                                            IOError: [Errno 13] Permission denied: u'/home/tv/.kodi/userdata/profiles/guest/library/video/movies/index.xml'
```
Could this be related to me having  a dedicated user `jellyfin` running Jellyfin and another user `tv` running Kodi?

**Comment by TrueTechy** [comment]
The different users for running jellyfin and kodi wouldn't matter. That error suggest the `tv` user doesn't have write access to the file within the `.kodi` folder which it should have access to everything in there if that's the user Kodi is running as. 

Have you ran Kodi before as a different user? If you have you might need to either change the owner or file permissions on the folder and it's contents to allow the user to write to it

**Comment by vdot0x23** [comment]
@TrueTechy i have not ran Kodi as a different user IIRC, but I do have a "guest" profile and as shown below, those seem to be read only. Not sure why.
```
$ pwd
/home/tv/.kodi/userdata/profiles/guest/library/video/movies

$ ls -la
total 52
dr-xr-xr-x 2 tv users 4096 Jan  1  1970 .
dr-xr-xr-x 5 tv users 4096 Jan  1  1970 ..
-r--r--r-- 1 tv users  199 Jan  1  1970 actors.xml
-r--r--r-- 1 tv users  205 Jan  1  1970 country.xml
-r--r--r-- 1 tv users  206 Jan  1  1970 directors.xml
-r--r--r-- 1 tv users  198 Jan  1  1970 genres.xml
-r--r--r-- 1 tv users  172 Jan  1  1970 index.xml
-r--r--r-- 1 tv users  209 Jan  1  1970 recentlyaddedmovies.xml
-r--r--r-- 1 tv users  237 Jan  1  1970 sets.xml
-r--r--r-- 1 tv users  203 Jan  1  1970 studios.xml
-r--r--r-- 1 tv users  198 Jan  1  1970 tags.xml
-r--r--r-- 1 tv users  230 Jan  1  1970 titles.xml
-r--r--r-- 1 tv users  196 Jan  1  1970 years.xml
```

Deleting the "guest" profile, means i get the following log intstead.
```
2019-12-21 09:55:53.358 T:140431673259776  NOTICE: JELLYFIN.service -> ERROR::service.py:54 [Errno 13] Permission denied: u'/home/tv/.kodi/userdata/library/video/movies/index.xml'
                                            Traceback (most recent call last):
                                              File "service.py", line 47, in run
                                                service = Service()
                                              File "jellyfin_kodi/entrypoint/service.py", line 70, in __init__
                                                verify_kodi_defaults()
                                              File "jellyfin_kodi/views.py", line 130, in verify_kodi_defaults
                                                write_xml(etree.tostring(xml, 'UTF-8'), file)
                                              File "jellyfin_kodi/helper/utils.py", line 294, in write_xml
                                                with open(file, 'w') as infile:
                                            IOError: [Errno 13] Permission denied: u'/home/tv/.kodi/userdata/library/video/movies/index.xml'
```
Which is the same as before, just for the "Master user" profile as those file are also read only.
```
$ pwd
/home/tv/.kodi/userdata/library/video/movies

$ ls -la
total 52
dr-xr-xr-x 2 tv users 4096 Jan  1  1970 .
dr-xr-xr-x 5 tv users 4096 Jan  1  1970 ..
-r--r--r-- 1 tv users  199 Jan  1  1970 actors.xml
-r--r--r-- 1 tv users  205 Jan  1  1970 country.xml
-r--r--r-- 1 tv users  206 Jan  1  1970 directors.xml
-r--r--r-- 1 tv users  198 Jan  1  1970 genres.xml
-r--r--r-- 1 tv users  172 Jan  1  1970 index.xml
-r--r--r-- 1 tv users  209 Jan  1  1970 recentlyaddedmovies.xml
-r--r--r-- 1 tv users  237 Jan  1  1970 sets.xml
-r--r--r-- 1 tv users  203 Jan  1  1970 studios.xml
-r--r--r-- 1 tv users  198 Jan  1  1970 tags.xml
-r--r--r-- 1 tv users  230 Jan  1  1970 titles.xml
-r--r--r-- 1 tv users  196 Jan  1  1970 years.xml
```

For a quick hack i  `$ chmod 664 *.xml`, which results in another error. Which is basically the same, but for another directory.
```
2019-12-21 10:03:45.680 T:140477105960704  NOTICE: JELLYFIN.service -> ERROR::service.py:54 [Errno 13] Permission denied: u'/home/tv/.kodi/userdata/library/video/tvshows/index.xml'
                                            Traceback (most recent call last):
                                              File "service.py", line 47, in run
                                                service = Service()
                                              File "jellyfin_kodi/entrypoint/service.py", line 70, in __init__
                                                verify_kodi_defaults()
                                              File "jellyfin_kodi/views.py", line 130, in verify_kodi_defaults
                                                write_xml(etree.tostring(xml, 'UTF-8'), file)
                                              File "jellyfin_kodi/helper/utils.py", line 294, in write_xml
                                                with open(file, 'w') as infile:
                                            IOError: [Errno 13] Permission denied: u'/home/tv/.kodi/userdata/library/video/tvshows/index.xml'
```

Continuing this with`$ chmod 664 *.xml`for `./movies`, `./tvshows`, and `./musicvideos`. Now it works :)

Not sure why my files were read only (security?), but the addon should probably handle it more elegantly.

**Comment by mcarlton00** [comment]
I'd argue that the addon handled it as well as can be expected.  The logs told you exactly what the problem was.  This isn't an addon problem, it's a kodi/workstation management problem.  If you had tried to add any local media from the filesystem or a network mount, it would have behaved the exact same way.

**Comment by oddstr13** [comment]
None of the files in my `~/.kodi` directory are marked as read-only for the user.

Run the following command to fix permissions;
`chmod u+w /home/tv/.kodi -R`
This will recursively give the owner (tv) write access to all files and directories under `/home/tv/.kodi`
