### ISSUE TITLE
Support DNS WAN Address (breaking change in jellyfin-server)

### ISSUE THREAD

**Issue by Phlogi** [jellyfin/jellyfin-kodi#17]
https://github.com/jellyfin/jellyfin/pull/1151
The mentioned merge will cause the login to the server to fail. The kodi jellyfin app needs to handle a DNS name (instead of plain IP) as the advertised public WAN endpoint. This currently fails and the endpoint variable stays empty.

**Comment by mcarlton00** [comment]
I'm using a public DNS name and it's working correctly still.  It doesn't seem like anything needs to be changed, unless I'm missing something

**Comment by oddstr13** [comment]
As far as I can tell, all API requests go via `requests` which handles either just fine.
