### ISSUE TITLE
How do I stop jellyfin altering my Kodi database ? 

### ISSUE THREAD

**Issue by MasterCATZ** [jellyfin/jellyfin-kodi#170]
**Describe the bug**
 I never even gave jellyfin any mysql username/passwords ?

**To Reproduce**
run jellyfin with kodi running 

**Expected behavior**
to Keep Kodi and Jellyfin separated and standalone 

**Logs**
now mysql kodi database is cluttered with jellyfin related content 

(1200,'Risa Taneda','<thumb>/var/lib/jellyfin/metadata/People/R/Risa Taneda/poster.jpg</thumb>')

and files have been redirected to jellyfin's metadata 

**Screenshots**

**System (please complete the following information):**
 - OS: [Ubuntu 19.10]
 - Jellyfin Version: [e.g. 10.5]
 - Kodi Version: [e.g. 19]
 - Addon Version: [e.g. ???]

**Additional context**
or is it something on kodi's side reading jellyfins data ?

**Comment by cvium** [comment]
That's what this plugin is designed to do though

**Comment by mcarlton00** [comment]
Jellyfin for Kodi replaces the need for the MySQL database backend, and as such is incompatible with it.  I don't understand what your use case is where you could want both, but it's not possible currently (and we don't really have any plans to change that).

It _might_ be possible to create separate Kodi profiles and have one linked to Jellyfin and one linked to your local database.

**Comment by oddstr13** [comment]
Seeing as this is incompatable with the underlying design of this addon, I'm closing this issue as wontfix.

If all you want is a library browser / playback, you could try selecting no  libraries to sync, and see if you can browse the libraries from the addon menu. I have not tested this myself however.
