### ISSUE TITLE
Updating from 0.4.0 causes crashes until restarting Kodi

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#176]
**Describe the bug**

Trying to access the addon settings page results in an error and being unable to change any settings

**To Reproduce**

1. Settings
2. Video Addons
3. Jellyfin

**Logs**

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ImportError'>
Error Contents: No module named kodi_six
Traceback (most recent call last):
  File "/home/matt/.kodi/addons/plugin.video.jellyfin/default.py", line 10, in <module>
    from kodi_six import xbmc, xbmcaddon
ImportError: No module named kodi_six
-->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.jellyfin/?content_type=video
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/?content_type=video) failed
```

**System (please complete the following information):**
 - Kodi Version:18.5
 - Addon Version: https://github.com/jellyfin/jellyfin-kodi/commit/896c2fe6ec9f5fa03f7a4aa638bc8effd04ac182

**Additional context**

Broken from the Py3 conversion.  Upgraded from 0.4.0 to current master.  After restarting Kodi it begins working again

**Comment by oddstr13** [comment]
I *think* this is only an issue in dev setup, as Kodi seems to not always pull in dependencies properly then.

Try installing from a zip and see if you can reproduce with that?

**Comment by mcarlton00** [comment]
Yeah that's what I'm doing.

1. Install 0.4.0 from the repo
2. Restart kodi (just making sure I'm starting 'clean')
3. Start kodi, you can access the settings page
4. Install current master .zip
5. Settings page throws error
6. Restart kodi
7. Settings page works again

It's likely a result of shifting dependencies, but since the addon restarts after an install I would expect it to not be an issue.  It's obviously not a huge issue and we could just chalk it up to a requirement of upgrading and mention it in the next release notes, but seems like something to at least take a look at before hand.

**Comment by mcarlton00** [comment]
Update: playback also fails after upgrading from 0.4.0 to current master.  Same issue.  We need to find a way to either force a restart or make the new libraries get ordered properly

**Comment by mcarlton00** [comment]
I'm unable to get the libraries to load correctly, and can't catch the upgrade process in the code.  I'm considering making an intermediate release (0.4.1) just make sure that kodi_six and other new dependencies are installed and ready to be used before the current master release lands.  Potentially release 0.4.1 in the next day or two and do a 0.5.0 at least a week afterwards.

**Comment by mcarlton00** [comment]
Intermediate release is live. https://github.com/jellyfin/jellyfin-kodi/releases/tag/v0.4.1
