### ISSUE TITLE
Errors out trying to play grouped TV episodes

### ISSUE THREAD

**Issue by juicetin** [jellyfin/jellyfin-kodi#177]
**Describe the bug**
When TV episodes are grouped, they are displayed as a single episode in the Kodi jellyfin plugin, but when trying to play them, it says unavailable media.

**To Reproduce**
1. Pick any TV episode, and group together 2 or more episodes
2. Go to the Jellyfin plugin in Kodi, and try to play the grouped episode
3. Error will appear

**Expected behavior**
More than one possibility here, but it could have an option to choose with version to play, or automatically select the version based on estimated network speed.

**Logs**
[Don't currently have access but can provide these later]

**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.4.2
 - Kodi Version: 18.5.1
 - Addon Version: 0.4.0

**Comment by mcarlton00** [comment]
Just so I understand this feature correctly, it's for when you have 2 of the same episode but in a different quality/language/something?

**Comment by mcarlton00** [comment]
I can't replicate this.  When I've grouped episodes in the Web UI and try to play it via Kodi, I get a popup asking for which version I'd like to play.  Possibly it was a bug that has since gotten fixed, but given that it's working now and there haven't been any other replies, closing.
