### ISSUE TITLE
controlling session from browser not working

### ISSUE THREAD

**Issue by Darkmagister** [jellyfin/jellyfin-kodi#183]
**Describe the bug**
I have a jellyfin 10.4.3, i've a kodi 19 connected with the the git version of the addons, if i go to the webpage of jellyfin i can see the session in kodi, i can see what it's playing but i can not interact with it, no pause, skip or even adding element to the queue, there is any configuration that i'm missing (on server or kodi) ? 

i've also the kodi queue sync plugin enabled in jellyfin

FYI
to install the git addons in kodi 19 i had some issue with module kodi-six, i think i have an older version and it was not able to find it, after some try on removing the module and adding it again, and try to update it i was able to install it

**Logs**
i'm not sure is a kodi addons issue because i can not see any error in the kodi.log file

**System (please complete the following information):**
 - OS: Ubuntu
 - Jellyfin Version: 10.4.3
 - Kodi Version: 19
 - Addon Version: 0.4.0 git

**Comment by mcarlton00** [comment]
Confirmed that control from the web UI isn't working in Kodi 19.  It's working as expected in Kodi 18.

I also didn't have any issues installing the addon, so maybe that piece was just a fluke.  Kodi's upstream addon repos seem to behave weirdly sometimes.
