### ISSUE TITLE
Kodi plugin does not work under Kodi 19

### ISSUE THREAD

**Issue by masca90021** [jellyfin/jellyfin-kodi#186]
Hi guys,

As the title says, I'm having trouble locating a build of the Kodi 19 plugin that will work. I have some fixes that are only commited to Kodi 19 by their respective developers and now I am using both Kodi 18.5 ( for Jellyfin ) and 19 ( for everything else ) but I would like to be able to use only Kodi 19. Is there such a build of the plugin or I should just wait for the official release ?

**Comment by oddstr13** [comment]
You can download current master with this link: https://github.com/jellyfin/jellyfin-kodi/archive/master.zip
Use the install from zip option.

**Comment by masca90021** [comment]
Tyvm, it worked.
