### ISSUE TITLE
Submit to the official repo?

### ISSUE THREAD

**Issue by Razzeee** [jellyfin/jellyfin-kodi#187]
Are there any plans to submit this to the official repo?

You'll get a code review and some more eyes on the addon for free :)

**Comment by mcarlton00** [comment]
We can't.  We modify the Kodi database directly, which isn't allowed to happen if we want to exist in the official Kodi repos.  That's why we run our own repo over [here](https://repo.jellyfin.org/releases/client/kodi/)

**Comment by dkanada** [comment]
Is this issue a duplicate?

**Comment by mcarlton00** [comment]
Not really.  It could kinda sorta be considered a duplicate of #19, but submitting it to the official Kodi repos has never been discussed here that I know of.

Though since there's no way forward to the official repos, no use keeping this one open.
