### ISSUE TITLE
Kodi UWP no audio

### ISSUE THREAD

**Issue by BRainXstorming** [jellyfin/jellyfin-kodi#204]
**Describe the bug**
Hello I tried to use my Jellyfin Server with Kodi UWP with xbox one. 
But when I play a movie or tv-show I have no audio

**To Reproduce**
Just Play a video

**Expected behavior**
I should hear sound

**Logs**
Logs from XBOX are complicated...

**Screenshots**
cannot screenshot no sound :D

**System (please complete the following information):**
 - OS: XBOX OS (Windows 10 UWP)
 - Jellyfin Version: latetes linux raspbian
 - Kodi Version: latest XBOX UWP

**Comment by mcarlton00** [comment]
Potentially stupid question, but are you positive the volume within Kodi is turned up?  I've had a few instances where I've started Kodi on various devices and the internal volume is defaulted to a super low level or muted.

If you check that and it's still an issue, you should be able to pull logs out using https://kodi.wiki/view/Log_file/Easy

**Comment by BRainXstorming** [comment]
Kodi internal volume was 100%. I looked up all possible reasons before, I do not know the Reason I restarted Kodi and Xbox Many times too. But now I tried again and sound is working.

**Comment by TrueTechy** [comment]
I've had this happen a few times. Strange Xbox glitch with Kodi I put it down to
