### ISSUE TITLE
Jellyfin playlists are missing items when viewed on Kodi

### ISSUE THREAD

**Issue by nicmcr** [jellyfin/jellyfin-kodi#205]
**Describe the bug**
Kodi playlists are missing items from the Jellyfin playlists. 

**To Reproduce**
1. Add number of items to a playlist
2. Browse to playlist on Jellyfin for Kodi addon
3. Compare list of items on Kodi to that on Jellyfin 

**Expected behaviour**
List of items in playlists in Kodi match those in Jellyfin. 

**System (please complete the following information):**
 - OS: Libreelec
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.2 (Libreelec 9.0.2)
 - Addon Version: 0.4.0

**Additional context**
When viewing the items i have in playlists in the Jellyfin web interface, some are listed with the format: 

`<show name> - S##E## - <episode title>`

and others are listed without the show name and the format:

`S##:E## - <episode title> `

It seems that those wth the show name first are not included when that same playlist is viewed in the Kodi interface. This doesn't appear to be related to the filenames, they all share the same format:

`<show name>/Season ##/<show name> - S##E## - <episode title> `

Although the different shows have been imported into Jellyfin over different versions. Without looking specifically, it seem shows added more recently seem to appear on both Jellyfin and Kodi, and those added earlier are missing on Kodi.

**Comment by mcarlton00** [comment]
You're finding the playlists by going through the Jellyfin add on menu directly, correct?  `Add-Ons -> Video Add-Ons -> Jellyfin -> Playlists`.  Just making sure I start looking in the right place for this.

**Comment by nicmcr** [comment]
Yes, accessing playlists in Kodi as you have described.

**Comment by mcarlton00** [comment]
Unfortunately I'm not able to replicate this to figure out what's going on.  It's possible that the playlist format of episodes has changed over the versions, but I don't remember seeing any mention of that.  If you try to add one of those items already present that has the full `<show name>/Season ##/<show name> - S##E## - <episode title>` to the playlist a second time, does it change what name format is in the playlist?  There's not any filtering that I can find happening here, as long as the API is returning the data it should be showing up

**Comment by nicmcr** [comment]
Thanks for checking. Can you confirm - what name/title format is correct when viewing Jellyfin playlists? I might find the ones displaying incorrectly and remove/readd them to my library.

**Comment by mcarlton00** [comment]
I can't claim that I know enough to say what's right or wrong, but this is a short playlist I just created to test this and they're all showing up correctly in Kodi.

![2020-02-27-222204_930x445_scrot](https://user-images.githubusercontent.com/17029228/75507633-a58f4400-59af-11ea-8707-be69b074b4cf.png)

**Comment by nicmcr** [comment]
Ok in my library the shows with that format are the ones that do show up correctly in Kodi - so that matches with your experience. I guess some shows in my library have some quirk on how they are added to a playlist, which then doesnt play nice with the JfK addon.

**Comment by mcarlton00** [comment]
Not sure how much manual work that would be for you, but if it's a lot I can put together a custom build that will log all items it finds.  That way we'll know for sure if the API is returning the correct values or not

**Comment by nicmcr** [comment]
Yeah if its not too much work for you i'd be happy to give that a try. Thanks

**Comment by nicmcr** [comment]
This persists with the new Jellyfin and Jellyfin for Kodi versions.

**Comment by mcarlton00** [comment]
Can you try installing the current master and seeing if this issue still persists?  I'm wondering if this may have been inadvertently fixed as a side effect of #300 

https://github.com/jellyfin/jellyfin-kodi/archive/master.zip

**Comment by nicmcr** [comment]
Thanks for trying. Sadly no such luck, same deal. I even made a brand new playlist to be sure. 

![image](https://user-images.githubusercontent.com/10767653/82754451-50c56300-9e10-11ea-9a9a-da2ce17b9766.png)

![image](https://user-images.githubusercontent.com/10767653/82754476-73577c00-9e10-11ea-9fc1-81e0cd04dd1f.png)

**Comment by mcarlton00** [comment]
Alright, put some extra noisy logging into this build so we can see exactly what the server is responding with.  Give it a shot and let's see where things are falling apart.

https://github.com/mcarlton00/jellyfin-kodi/archive/playlist-items.zip

**Comment by NovaCyntax** [comment]
This isn't explicitly related to the issue, so my apologies in advance, but I saw this issue was open and decided I might try asking here.

Let's say I create a music playlist in Jellyfin. Can I access/share this playlist through Kodi natively, or would I have to go through the Jellyfin add-on for Kodi in order to access it?

**Comment by mcarlton00** [comment]
Right now you have to go through the addon menu.  Adding the ability to sync it to the database like other media types is on my todo list, but i haven't sat down to figure it out the details yet.  You're probably looking for #175 (I just renamed it to be clearer)

**Comment by NovaCyntax** [comment]
Alright thanks, I appreciate the clarification. I recently set up a Jellyfin server and I'm enjoying it a lot so far, I appreciate all the work members of the community such as yourself have put into it.

**Comment by nicmcr** [comment]
> Alright, put some extra noisy logging into this build so we can see exactly what the server is responding with. Give it a shot and let's see where things are falling apart.
> 
> https://github.com/mcarlton00/jellyfin-kodi/archive/playlist-items.zip

OK I installed this, do you just want the log? Looking through it it only ever sees two episodes.

**Comment by nicmcr** [comment]
> This isn't explicitly related to the issue, so my apologies in advance, but I saw this issue was open and decided I might try asking here.
> 
> Let's say I create a music playlist in Jellyfin. Can I access/share this playlist through Kodi natively, or would I have to go through the Jellyfin add-on for Kodi in order to access it?

Actually depending on the skin you use you can kinda do this. I have a home menu item that takes me straight the the playlist in the jellyfin addon. So it's not a native playlist but you'd barely know it.

**Comment by mcarlton00** [comment]
If you're only seeing 2 items in the logs, then it sounds like there's something with the way our API call is structured that's excluding some files.  We'll need to do more testing to determine what's going on here.  It's really not making much sense.

Are all items on the playlist from the same media library/media folder?  TV Shows vs Mixed Content?

**Comment by nicmcr** [comment]
Yes all items coming from the same location. All TV shows content type. Thanks

**Comment by mcarlton00** [comment]
Alright, I added some different api calls to try to narrow this down.  When you request a playlist through the addon menu, you should see 4 separate log lines spit out.  They're listing how many items were found with each type of API call that I'm doing.  There's several other options, but these seem the most likely to be causing issues to me.

It will look something like this:
```
INFO::jellyfin_kodi/monitor.py:208 filtered Playlist items found: 9
INFO::jellyfin_kodi/monitor.py:209 filtered_recursive Playlist items found: 9
INFO::jellyfin_kodi/monitor.py:210 no_filter Playlist items found: 9
INFO::jellyfin_kodi/monitor.py:211 no_filter_recursive Playlist items found: 9
```

Same link as before, but it's been updated with my latest changes now: https://github.com/mcarlton00/jellyfin-kodi/archive/playlist-items.zip

**Comment by nicmcr** [comment]
Hey sorry for the radiosilence on this. I ended up having to rebuild my Jellyfin box and on the new install I am no longer experiencing this issue. So it seems it was a quirk of when I imported those select shows I guess? 

Thanks a lot for the work you put in trying to get this fixed.

**Comment by mcarlton00** [comment]
Thanks for the update.  Shame we couldn't find the true source, but hopefully it won't be an issue again
