### ISSUE TITLE
Direct play skipping is limited to 10 second gaps

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#21]
After upgrading the server to 10.3.0, when trying to skip while a video file is playing, no matter how far you tell it to skip it will only do 10 second intervals.

Gif provided by /u/SpectralGelatin on reddit:
https://gfycat.com/QualifiedPleasantInsect

Forcing kodi to transcode all files allows skipping to behave normally, so this appears to be a bug in direct play.  Unsure if it's related to the kodi plugin specifically or other clients that can direct play as well.

To force kodi to transcode all jellyfin files:
Addons -> Video Add-Ons -> Jellyfin -> Settings -> Playback -> Force Transcode

**Comment by Verequies** [comment]
Wow, this is an issue. After reading this I realised this is the reason why I can't skip in 30 second blocks etc.

**Comment by 98WuG** [comment]
Can confirm same issue. Is anybody maintaining this plugin? If not, I can try to look into it when I have some spare time.

**Comment by mcarlton00** [comment]
@anthonylavado mentioned that he might have a possible lead on what the root cause is, but I don't think he's had time to finish investigating yet.

As for maintaining: Yes, but the core team has largely been busy making improvements to the server and getting other clients operational, and since this hasn't needed a whole lot of love yet their priorities have been elsewhere.  If you do end up looking into things, PRs are welcome.

**Comment by GotekSC** [comment]
I can't say for certain, but I think this is also related to why selecting bookmarks/chapters has no effect at all. Resuming playback instead starts videos from the beginning, and seeking backwards also skips forward for me.

**Comment by anthonylavado** [comment]
https://github.com/jellyfin/jellyfin/pull/1287 should fix this

**Comment by mcarlton00** [comment]
Confirmed the fix is working after updating the Jellyfin server to 10.3.2
