### ISSUE TITLE
Updating library wipes already synced content

### ISSUE THREAD

**Issue by TrueTechy** [jellyfin/jellyfin-kodi#213]
**Describe the bug**
When forcing a library update in the addon menu instead of new content being added or old content refreshed, all content just dissapears from the Kodi menus

**To Reproduce**
Open addon settings
Go to 'Manage Libraries' then 'Update Libraries'
Click 'All'

**Expected behavior**
New content and changes are  synced from server

**System (please complete the following information):**
 - OS:Ubuntu
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.5
 - Addon Version: 10.4.* (development branch)

**Comment by suodrazah** [comment]
Do the Jellyfin-Kodi libraries automatically update, on a schedule or otherwise?
