### ISSUE TITLE
Bad year metadata causing sync failure

### ISSUE THREAD

**Issue by flatline-studios** [jellyfin/jellyfin-kodi#216]
Some of my videos (home movies), had erroneous year tags (it had put together the whole date in the year field in the metadata).

My Kodi log (with Jellyfin addon debug enabled) shows:

`"ProductionYear": 20110112, `

It then produces this error:

```
2020-02-27 16:39:00.274 T:20092  
NOTICE: JELLYFIN.full_sync -> ERROR::jellyfin_kodi\full_sync.py:240 year is out of range
  Traceback (most recent call last):
    File "jellyfin_kodi\full_sync.py", line 231, in process_library
      media[library['CollectionType']](library)
    File "jellyfin_kodi\helper\wrapper.py", line 40, in wrapper
      result = func(self, dialog=dialog, *args, **kwargs)
    File "jellyfin_kodi\full_sync.py", line 363, in musicvideos
      obj.musicvideo(mvideo, library=library)
    File "jellyfin_kodi\helper\wrapper.py", line 102, in wrapper
      return func(*args, **kwargs)
    File "jellyfin_kodi\helper\wrapper.py", line 116, in wrapper
      return func(self, item, e_item=e_item, *args, **kwargs)
    File "jellyfin_kodi\helper\wrapper.py", line 175, in wrapper
      return func(self, item, *args, **kwargs)
    File "jellyfin_kodi\objects\musicvideos.py", line 79, in musicvideo
      obj['Premiere'] = Local(obj['Premiere']) if obj['Premiere'] else datetime.date(obj['Year'] or 2021, 1, 1)
  ValueError: year is out of range
```

Can we get a sanity check for the value(s) of the date/year fields, and simply ignore the bad data if it fails?

**Comment by TrueTechy** [comment]
is this still a bug using the latest version of the addon and server? I tried it there but it didn't throw any errors when syncing, though the content wasn't synced after the invalid date so that still needs fixed

**Comment by flatline-studios** [comment]
It's still a bug.

Sync will take place up until an invalid formatted year appears in the queue. Then it fails, without warning. 

If the invalid year meta data appears in "zebra_001.mp4", then it's not that much of a problem... If it appears in, "01242011_0645.mp4", then it's a big problem, in that the rest of the library won't import.

I wish I had the time, and instead of using atomic parsley, and a shell script to fix the metadata, I really should've modified the kodi plug in to not be so strict about its checks...

**Comment by TrueTechy** [comment]
@flatline-studios Not to worry. I couldn't replicate the issue at first, but then I got it after a while and I've got an open PR you can see above which will resolve this issue till the server validates the data
