### ISSUE TITLE
Password incompatibility with 10.3+

### ISSUE THREAD

**Issue by jmeacoe** [jellyfin/jellyfin-kodi#22]
as per: https://www.reddit.com/r/jellyfin/comments/bgmer1/embyforkodi_broken_with_jellyfin_1031031/

Currently, Jellyfin4Kodi sends a prehashed password when you try and authenticate.
The server now requires a salt.

Where the issue is:
https://github.com/jellyfin/jellyfin-kodi/blob/master/resources/lib/jellyfin/core/connection_manager.py#L161

**Comment by oddstr13** [comment]
Only happens over what the addon (or Jellyfin?) determines is a connection over the internet (WAN, External), and then only over HTTP.

https://github.com/jellyfin/jellyfin-kodi/blob/c12918f32112b09593cbf5dd415b6e5c9b62895b/resources/lib/jellyfin/core/connection_manager.py#L26-L30

https://github.com/jellyfin/jellyfin-kodi/blob/c12918f32112b09593cbf5dd415b6e5c9b62895b/resources/lib/dialogs/loginmanual.py#L119-L123

https://github.com/jellyfin/jellyfin-kodi/blob/c12918f32112b09593cbf5dd415b6e5c9b62895b/resources/lib/jellyfin/core/connection_manager.py#L147-L174

As to how it decides `mode == 'Remote'`, I have decided I would like to keep my sanity (for now at least).

**Comment by mcarlton00** [comment]
The quick and dirty fix is to just change https://github.com/jellyfin/jellyfin-kodi/blob/master/resources/lib/jellyfin/core/connection_manager.py#L161 from
```
request = {
    'type': "POST",
    'url': self.get_jellyfin_url(server, "Users/AuthenticateByName"),
    'json': {
        'username': username,
        'password': hashlib.sha1(password or "").hexdigest(),
    }
}
if clear:
    request['json']['pw'] = password or ""
```
to
```
request = {
    'type': "POST",
    'url': self.get_jellyfin_url(server, "Users/AuthenticateByName"),
    'json': {
        'username': username,
        'password': password,
    }
}
```
This way it bypasses the whole WAN detection/mode/shenanigans and always sends a clear password.

I haven't seen any of my boxes fail to connect, so I'm not sure if it's actually broken for people or not.  This will get them working again if so.  I agree that we should track down all the other unneeded code around this and keep it cleaned up though.

**Comment by EraYaN** [comment]
Shouldn't it be `Pw` instead of `password`

**Comment by mcarlton00** [comment]
It should, good catch.  Corrected.  Too early in the morning for me to be having technical discussions

**Comment by oddstr13** [comment]
I'm not sure of how emby/jf handles auth, and if they would reject a plain password login over wan.
As such, I would suggest just removing the clear check and unindenting the set password line

**Comment by mcarlton00** [comment]
If we go that route, might as well just change the payload instead of adding another parameter later.
```
'json': {
    'username': username,
    'password': hashlib.sha1(password or "").hexdigest(),
    'Pw': password,
}
```

That being said, my impression was that all support for pre-hashed passwords had been removed, WAN or otherwise.  I could be wrong though

**Comment by anthonylavado** [comment]
Well, what @mcarlton00 says is correct. All pre-hashed password support has been removed, regardless of connection method. If you send one, you get a friendly 405 MethodNotAllowed.

Thus, my vote here is for whatever gets it working again with a plain password.

**Comment by oddstr13** [comment]
So that's a 405 when the pre-hashed password is present? or just when the plaintext one is missing?

**Comment by anthonylavado** [comment]
In Jellyfin/Jellyfin#1244 we have the relevant changes
