### ISSUE TITLE
0.5.0 init issue on windows / and ascii error

### ISSUE THREAD

**Issue by Ashyni** [jellyfin/jellyfin-kodi#220]
**Describe the bug**
The add-on don't start properly on windows. 
On a fresh kodi install (AppData clean), the add-on first configuration works (server/credentials/library/first sync), then on restart, no "Welcome me!" message and no sync.
Tested on Kodi Windows UWP 18.5 and Kodi 18.6 x64 standard (fresh install in between).
On Android (no fresh install yet), we have the welcome message but no sync appears.

**Logs**
Windows UWP:
https://pastebin.com/7sis95qF
Windows standard x64 Bin:
https://pastebin.com/CBxZHwB0
Android:
https://pastebin.com/PvHdyhhX

**System**
 - OS: [Windows]
 - Jellyfin Version: [10.4.3]
 - Kodi Version: [18.5-6]
 - Addon Version: [0.5.0]

**Comment by mcarlton00** [comment]
This seems to be related to the Python 2/3 conversation we did.  It's also manifesting later in the addon as shown by [these logs](http://ix.io/2dvr) from a LibreElec install.  I went through 7 devices yesterday across multiple versions and can't get the error to trigger, so there's some special circumstances that I'm missing somewhere.  Possibly it's a language/encoding related thing.

Are you using a reverse proxy with your server?

**Comment by Ashyni** [comment]
Hey, Jellyfin server is behind Traefik, yes, with "secure connection mode" to "Handle by reverse proxy".
But my Windows Client bypass the proxy, it's a direct connection on local network 192.x.x.x:8096,
the rest of my client are behind Traefik on https://

**Comment by Ashyni** [comment]
Same log if i switch to Disabled for secure connection mode and my local windows client.

**Comment by mcarlton00** [comment]
I'm wondering if it's language specific.  What language is your computer and Jellyfin server set to?  And do you know if you have any special characters in items, like movies or playlist titles?  There definitely seems to be some unicode characters popping up where they shouldn't right now, it's just finding where they're coming from so we can make the addon behave

**Comment by Ashyni** [comment]
French so é à è ç ù ... Bazarr app get similar issue when switching to python 3.

**Comment by mcarlton00** [comment]
Think I tracked down all the issues.  Can you give [this](https://github.com/mcarlton00/jellyfin-kodi/archive/xml-unicode.zip) build a try and see if it solves the problems?

**Comment by Ashyni** [comment]
Got this on install
https://pastebin.com/m6wUw8BL

**Comment by Ashyni** [comment]
I have reset kodi 18.6 x64 and jellyfin addon 0.5.0-xml-unicode, and done some change related to the last log, just to test, no idea if it's the correct change.
add `<import addon="script.module.elementtree" version="1.2.8"/>` to `addon.xml`
and change `from lxml import etree` to `from elementtree import ElementTree as etree` in `helper/xmls.py` and  `views.py`.
Even with kodi in english, jellyfin clean (no adresss or credential or library, really nothing setup), i get the same log in the first post, just no proper init.

**Comment by Ashyni** [comment]
Could be related to the Python version ? when we compare Windows/Android (or Linux/LibreElec)
```
KODI Version: 18.6 Git:20200229-8e967df921
Platform: Windows
Python Version: 2.7.13 (default, Jul 14 2017, 17:41:26) [MSC v.1900 64 bit (AMD64)]
```
```
KODI Version: 18.6 Git:20200229-8e967df921
Platform: Linux/Android
Python Version: 2.7.15 (default, Feb 29 2020, 11:25:05) [GCC 4.2.1 Compatible Android (4751641 based on r328903) Clang 7.0.2
```

**Comment by mcarlton00** [comment]
That was my bad.  Forgot to check which XML libraries were supported by Kodi.  One more try, if you don't mind.  https://github.com/mcarlton00/jellyfin-kodi/archive/xml-unicode.zip

**Comment by Ashyni** [comment]
Seems good on android, here is a full kodi log https://pastebin.com/mCmSYucm
But not on Windows, here two log, one after delete `appDataRoming/Kodi` https://pastebin.com/JX73mfts and one after reboot Kodi https://pastebin.com/J8sqLxLj
It's working just after a clean install not after reboot kodi.

**Comment by mcarlton00** [comment]
Hmm, that doesn't make sense.  I'm testing on Libreelec in french and i can upgrade fine there.  Unless it's a windows specific bug, but I can't imagine how it was ever working if that's the case

**Comment by Ashyni** [comment]
Clearly windows specific, could be related to python version ?
I have commented the line 72 `#verify_kodi_defaults()` in service.py and the addon works (ask for new server) here the log https://pastebin.com/F8hBeqiN

**Comment by Ashyni** [comment]
Fully configure and first sync, restarted Kodi, still working, so something related to windows and `verify_kodi_defaults()`

**Comment by mcarlton00** [comment]
I think I found it.  Some bad logic about checking file paths followed by poor usage of try/except blocks triggered an error, which then sent straight Unicode into the logging statement, which triggered a second traceback (the ascii one you're seeing).  Try one more time, please.  Same download link.

**Comment by Ashyni** [comment]
All good, well done, last log if you wanna check https://pastebin.com/xpCrExF7

**Comment by Ashyni** [comment]
Hello, me again,
i have found more ascii error, log below.
https://pastebin.com/tfrd9ad7

**Comment by mcarlton00** [comment]
Can you give some instructions to replicate that one?  I can't read French, but I've been flipping through all the settings I see in the addon menu and can't seem to trigger it.

**Comment by oddstr13** [comment]
Something funky seems to be happening with this log call, causing unicode errors. Probably when passed the value of `u"Param\xe8tres"`, which is somehow encoded to `utf8`, and then attempted decoded with the `ascii` codec.

**Comment by Ashyni** [comment]
Kodi Language to 'French', then 'Right Click'/'Context Menu' on a movie or show 'Options Jellyfin' -> 'Paramètres' > Error in log/Nothing append.
