### ISSUE TITLE
Auto Discovery Not Working

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-kodi#229]
**Describe the bug**

When installing, the server is not auto discovered.

**Screenshots**

![image](https://user-images.githubusercontent.com/20715731/76644346-35df9400-652d-11ea-9e1f-615b74ee8d45.png)

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows] Linux
 - Jellyfin Version: [e.g. 10.0.1] 10.5.0
 - Kodi Version: [e.g. 18.3]18.3
 - Addon Version: [e.g. 0.2.1]0.2.1

**Additional context**

**Comment by TrueTechy** [comment]
How are you running the sever, is it in a docker container? I'm running jellyfin and kodi on the same machine for testing and it auto discovers the server fine

**Comment by Artiume** [comment]
Kodi is on my windows box. I have about 7 servers that I'm aware of (woes of dev life lol). My main server is in docker, host_mode plus 3 more in containers in bridge mode. 2 Pi's are bare metal install, and 1 Pi in docker host_mode.

**Comment by TrueTechy** [comment]
Could you provide us the log files from any of your instances during the initial setup when it'll do the auto discovery?

**Comment by oddstr13** [comment]
Can you please check to see if you're getting the following in your server log?
```
[WRN] [34] Emby.Server.Implementations.EntryPoints.UdpServerEntryPoint: Unable to respond to udp request because the local ip address could not be determined.
```

**Comment by Artiume** [comment]
Nothing Udp in the logs, but maybe I need to invoke auto discovery.

**Comment by Artiume** [comment]
im going to close this until i figure it out my system, i think it's a me problem, not a kodi problem

**Comment by oddstr13** [comment]
The log line above is what I'm getting on my Jellyfin server - it can't figure out it's own local IP for whatever reason, and as such does *not* respond to the discovery request.

You may be able to run `tcpdump -Xvv port 7359` on the server to verify whether it receives the discovery request, or wireshark on desktop to verify if it's getting sent over the correct network interface.

My initial thought was that the discovery request may be sent on the wrong network interface, but that was not the cause in my setup.
