### ISSUE TITLE
Unable to install on Kodi 19 (LibreELEC 9.80)

### ISSUE THREAD

**Issue by z3ntu** [jellyfin/jellyfin-kodi#230]
**Describe the bug**

On the image https://test.libreelec.tv/LibreELEC-A64.arm-9.80-nightly-20200311-097260a-pine64-lts.img.gz for the PINE A64-LTS it's not possible to install the jellyfin kodi addon. I've followed https://jellyfin.org/docs/general/clients/installing-kodi.html but when trying to install the Jellyfin addon (under "Video Add-ons") I get an error `The dependency on xbmc.python version 2.25.0 could not be satisfied.`

**To Reproduce**

1. Try to install the addon on the latest LibreELEC nightly

**Expected behavior**

The addon should install successfully

**Logs**

```
...
2020-03-13 20:21:19.204 T:2994  NOTICE: CAddonMgr::FindAddons: xbmc.python v3.0.0 installed
2020-03-13 20:21:19.204 T:2994  NOTICE: CAddonMgr::FindAddons: xbmc.webinterface v1.0.0 installed
2020-03-13 20:21:19.734 T:2996   ERROR: CCurlFile::Open failed with code 404 for https://addons.libreelec.tv/9.80.3/H3/arm/addons.xml.gz.sha256:
2020-03-13 20:21:19.735 T:2996   ERROR: Open - failed to open source <https://addons.libreelec.tv/9.80.3/H3/arm/addons.xml.gz.sha256>
2020-03-13 20:21:19.735 T:2996   ERROR: CRepository: failed read 'https://addons.libreelec.tv/9.80.3/H3/arm/addons.xml.gz.sha256'
2020-03-13 20:22:14.534 T:3026   ERROR: CAddonInstallJob[plugin.video.jellyfin]: The dependency on xbmc.python version 2.25.0 could not be satisfied.
2020-03-13 20:23:01.784 T:2715   ERROR: Previous line repeats 1 times.
2020-03-13 20:23:01.784 T:2715   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
2020-03-13 20:24:35.167 T:3056   ERROR: CAddonInstallJob[plugin.video.jellyfin]: The dependency on xbmc.python version 2.25.0 could not be satisfied.
2020-03-13 20:36:28.778 T:3130   ERROR: Previous line repeats 1 times.
2020-03-13 20:36:28.778 T:3130   ERROR: GetDirectory - Error getting addons://search/

```

**Screenshots**

**System (please complete the following information):**
 - OS: LibreELEC
 - Jellyfin Version: irrelevant (Docker image from a few weeks ago)
 - Kodi Version: 19
 - Addon Version: 0.5.1

**Additional context**

Unfortunately there only seems to be this nightly version for this hardware.

**Comment by z3ntu** [comment]
After playing around a bit I managed to get the addon installed:

Change in [script.module.addon.signals](https://github.com/ruuk/script.module.addon.signals) and install manually (not available in `matrix` repo yet apparently):
```diff
diff --git a/addon.xml b/addon.xml
index 36cec70..952b385 100644
--- a/addon.xml
+++ b/addon.xml
@@ -4,7 +4,7 @@
     version="0.0.5"
     provider-name="Rick Phillips (ruuk)">
     <requires>
-        <import addon="xbmc.python" version="2.14.0" />
+        <import addon="xbmc.python" version="3.0.0" />
     </requires>
     <extension point="xbmc.python.module" library="lib" />
     <extension point="xbmc.addon.metadata">

```

Change in jellyfin-kodi and install manually:
```diff
diff --git a/addon.xml b/addon.xml
index 46fd6c61..dfedf84f 100644
--- a/addon.xml
+++ b/addon.xml
@@ -4,13 +4,12 @@
         version="0.5.1"
         provider-name="Jellyfin Contributors, angelblue05">
   <requires>
-    <import addon="xbmc.python" version="2.25.0"/>
+    <import addon="xbmc.python" version="3.0.0"/>
     <import addon="script.module.requests" version="2.22.0"/>
     <import addon="script.module.dateutil" version="2.7.3"/>
     <import addon="script.module.six" />
     <import addon="script.module.kodi-six" />
     <import addon="script.module.addon.signals" version="0.0.1"/>
-    <import addon="script.module.futures" version="2.2.0"/>
   </requires>
   <extension    point="xbmc.python.pluginsource"
                 library="default.py">

```
I'm at the login process right now, seems to work fine.

**Comment by mcarlton00** [comment]
Yeah, it was working fine and then upstream Kodi changed some stuff around and broke it on us.  Matrix is in an alpha state, so it's to be expected.  Last I looked none of our dependencies supported the new 3.0.0 version, so good to know that there's progress being made

**Comment by mcarlton00** [comment]
For future reference here (and anybody else who comes here), there was lots of internal discussion how to handle the move to Kodi 19 and Python 3 compatibility.  It was decided to maintain Python 2 and 3 compatibility in the same codebase.  We got that working largely thanks to @oddstr13, but now Team Kodi has essentially decided that the method we chose was wrong.

The only valid way to maintain support for both Kodi 18 and Kodi 19 is to have 2 separate branches, 2 separate add-on repos, and 2 completely separate releases that target different versions of xbmc.python.  This is obviously going to involve significantly more work and coordination to make happen, so we'll need to start those discussions over again on how best to handle that from an organizational point of view and what the infrastructure for that needs to look like.

**Comment by oddstr13** [comment]
I would like to note that the only change required for the addon to run in Kodi 19 nightlies is the following change:
```diff
diff --git a/addon.xml b/addon.xml
index 569e749e..5c4523fe 100644
--- a/addon.xml
+++ b/addon.xml
@@ -4,7 +4,7 @@
         version="0.5.3"
         provider-name="Jellyfin Contributors, angelblue05">
   <requires>
-    <import addon="xbmc.python" version="2.25.0"/>
+    <import addon="xbmc.python" version="3.0.0"/>
     <import addon="script.module.requests" version="2.22.0"/>
     <import addon="script.module.dateutil" version="2.7.3"/>
     <import addon="script.module.six" version="1.13.0"/>
```

Music database has changed and needs fixing, but that is a different issue.

**Comment by z3ntu** [comment]
I still need to remove the `script.module.futures` dependency on latest kodi from git master, otherwise:
```
2020-06-17 19:24:41.135 T:194805   ERROR <general>: CAddonInstallJob[plugin.video.jellyfin]: The dependency on script.module.futures version 2.2.0 could not be satisfied.
```

**Comment by oddstr13** [comment]
Yes, looks like dependencies are only checked on install time, and the `xbmc.python` one is checked on every addon load.

Thus, I'm not getting any of the dependencies pulled in by Kodi in my dev setup, nor do I see missing dependencies in the Kodi 19 repos, unfortunately.

I've got `~/.kodi/addons/plugin.video.jellyfin` symlinked to my dev copy of the git repository, for ease of testing changes, and thus never go via the addon installation logic in Kodi.

**Comment by obbardc** [comment]
Any update on this at all?
Upstream issue seems closed/unwilling to fix.
This is a major blocker and i got burned on my upgrade the other day :/.

**Comment by mcarlton00** [comment]
We were kinda holding and hoping they would change their minds, but it's not looking like they're going to.  We're going to need to set up a separate addon repository to handle Kodi 19 releases, which is frustrating.  Hopefully one of us will have time to look into it soon.

In the meantime, I've just manually attached a build of the current release to https://github.com/jellyfin/jellyfin-kodi/releases/tag/v0.5.8 that _should_ be compatible with Kodi 19.  Be aware that music syncing doesn't currently work on Kodi 19.

**Comment by fosspill** [comment]
I'm very confused by this, but it seems like the addon now requires Python 3 which I believe libreelec not yet supports?

Regardless, I keep getting an error about it being unable to run  due to python 3.0.0 missing

**Comment by TrueTechy** [comment]
Python3 is required for running kodi 19. You should still be able to install the addon with python 2

**Comment by fosspill** [comment]
I'll try with a clean kodi install and give logs. It's Kodi 18 in my case

**Comment by frezeen** [comment]
i try to install manually .zip 0.5.9 but fail on kodi 19 apha 1
i try py2 and py3 zip

The dependency on xbmc.python version 3.0.0 could not be satisfied. for py3

**Comment by mcarlton00** [comment]
If you're using Kodi 18, you need to use the `-py2-` version.  If you're on Kodi 19, you need to use the `-py3-` version.  I've just downloaded the py3 zip from the release page and it installed fine in a freshly compiled Kodi 19.

It sounds like you're trying to install the py3 version on Kodi 18 if it can't find xbmc.python 3.0.0

**Comment by frezeen** [comment]
thanks for reply, im trying to install py3 on kodi 19 alpha 1from here: http://mirrors.kodi.tv/snapshots/windows/win64/

**Comment by oddstr13** [comment]
Kodi 19 version is now available in our repo, and an update from Kodi 18 -> 19 ***should*** just work.

We are routing to different repositories based on the user agent, so if any distribution does something stupid with the user agent, it may break.

**Comment by schilling3003** [comment]
I am still unable to get it to work. Using Kodi 19 Alpha 2 and the latest version of the Jellyfin add-on from the repo.

**Comment by oddstr13** [comment]
@schilling3003 What error are you getting?
*Exactly* how are you installing the add-on?
May I have the Kodi logs from a failed install attempt?

**Comment by obbardc** [comment]
seems to be broken using kodi 19 on debian unstable, entering the installed jellyfin repository shows no entries or addons to download.

**Comment by PANiCnz** [comment]
Trying to install on LibreELEC-RPi4.arm-9.80-nightly-20210210-06bafb5 and getting the error "The dependency on script.module.six version 1.14.0+matrix.2 could not be satisfied.". Managed to download and install the dependency manually but it would be nice if it was automated.

**Comment by mcarlton00** [comment]
@obbardc I can't replicate this.  Running Kodi master on Arch it works as expected.  If you're still having issues it could be that the debian packagers have changed the useragent and made our lives more difficult again.

@PANiCnz It is automated.  If that's the only dependency that failed, then you've been hit by Kodi's addon mirror ecosystem that sometimes gets out of whack.  You got sent to a bad mirror that didn't have the files requested.

**Comment by obbardc** [comment]
@mcarlton00 can you remind me how the user agent detection works? Do you have the code for that released anywhere or? I'll go check if Debian messes with the ua ;-)

**Comment by mcarlton00** [comment]
We know debian messes with the UA (which is already annoying), the question is whether they've changed their standard for Kodi 19 or not.  The reason this is important is because our repository is filtering traffic based on user agent.  This is so we can run one repo that serves multiple Kodi versions, instead of having to run multiple under different URLs and make things really ugly for users (as well as no true upgrade path from v18 to v19).

As an example, vanilla Kodi's user agent looks like this:

    "Kodi/18.2
    "Kodi/18.3
    "Kodi/18.4

While Debian just has to be difficult and changed theirs to

    "KodifromDebian/17.1
    "KodifromDebian/17.6
    "KodifromDebian/18.7
    "KodifromDebian/18.8

It's just made our filtering rules on the addon repo more annoying.  Unfortunately, I'm not sure if there's any way to check it from within Kodi itself, I only found out about this after experimenting with the addon repo and viewing logs.  It is a bit of a hack and I don't like that this is what we're doing, but I wasn't able to find a better alternative at the time.  I should be able to get a debian unstable VM spun up soon so I can verify this and see if they've changed it again.

**Comment by z3ntu** [comment]
Reading through the patch in Debian `KodifromDebian/$version` still seems to be the case

https://salsa.debian.org/multimedia-team/kodi-media-center/kodi/-/blob/master/debian/patches/kodi/0004-differentiate-from-vanilla-Kodi.patch#L46

(GetAppName returns `Kodi from Debian` (likely) and then `appName.erase(std::remove_if(appName.begin(), appName.end(), ::isspace), appName.end());` removes all spaces)

**Comment by mcarlton00** [comment]
I haven't heard any other complaints about this recently, so I'm assuming it's been fixed on our repo.

**Comment by obbardc** [comment]
can confirm the addon repo is working nicely on kodi 19.1 on debian sid :-)
