### ISSUE TITLE
Some language files are not in right path

### ISSUE THREAD

**Issue by outline941** [jellyfin/jellyfin-kodi#235]
**Describe the bug**

Some language files are not in right path, and the language in addon will fallback to english.
According to https://kodi.wiki/view/Language_support#Layout_of_the_language_folders
	These folders use "language-country" naming scheme. 
Like:
resource.language.ja -> resource.language.ja_jp
resource.language.zh_Hans -> resource.language.zh_cn

not good in english

**To Reproduce**

1. Change front to arial
2. Change language to one that string.po is not in correct place.
3. Go jellyfin setting
4. See english

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Debian
 - Jellyfin Version: 10.5.0
 - Kodi Version: 18.5
 - Addon Version: 0.5.1

**Additional context**

**Comment by mcarlton00** [comment]
Confirmed.  Thanks for the report
