### ISSUE TITLE
"Next Episodes" displays the entire library instead of only the next episode

### ISSUE THREAD

**Issue by quixventure** [jellyfin/jellyfin-kodi#239]
**Describe the bug**
When selecting "Next Episodes" from within the Jellyfin addon the result is a list of every episode in every library. 

This is only happening for new installs. 

**To Reproduce**

1. Go to Jellyfin addon
2. Click on a library
3. Scroll down to Next Episodes
4. See a list of all episodes in every library

**Expected behavior**
A list of only the 25 "next" episodes and only in the current library.

**Logs**
No errors

**Screenshots**

**System (please complete the following information):**
 - OS: MacOS, Libreelec
 - Jellyfin Version: [e.g. 10.5.0]
 - Kodi Version: [e.g. 18.6]
 - Addon Version: [e.g. 0.5.1]

**Additional context**
The issue can be fixed by manually editing the nextepisiodes.xml file in the userdata>> library>> video>> jellyfinXXXXXXXXXXX folder and changing:

`<node order="5" type="filter">`

to:

`<node order="5" type="folder">`

Specifically, changing the type to folder instead of filter. 

This appears to have been introduced in 0.5.0 or 0.5.1 as my older installs are fine and when upgrading the XML files are unchanged, but new installs are behaving differently.

**Comment by mcarlton00** [comment]
Good catch on where it's broken at.  Looks like this somehow changed due to the changing of the xml files due to ascii errors.
