### ISSUE TITLE
Wrong Metadata between libraries

### ISSUE THREAD

**Issue by eglia** [jellyfin/jellyfin-kodi#24]
When accessing my Jellyfin library within Kodi, either Movies or TV Shows show the Metadata of another item, depending on which was synced last.

For example, if I only sync the Movies library, everything is fine. If I then sync the TV Shows library, the TV Shows are correct, but when opening a Movie, it shows the Metadata of a random TV Show or Episode and playback fails.
If I then sync the Movies library again, the Movies work correctly but all TV Shows and Episodes show the Metadata of a random Movie.

I've also seen this previously with Emby for Kodi (and Jellyfin server), but it was always fixed by repairing the libraries from the Addon. With Jellyfin for Kodi, one of the libraries is always messed up and can't be repaired.

**Comment by jmeacoe** [comment]
Please supply more details as to your setup.
Kodi version and env
Jellyfin version and env
  JF install method
  Is kodi sync queue installed
and do you have any logs that might show this issue occuring?

**Comment by oddstr13** [comment]
Closing due to no response from issue creator. Please give more details if you are still having this issue.
