### ISSUE TITLE
Player.set_audio_subs exception when setting subs

### ISSUE THREAD

**Issue by mrmaltgr** [jellyfin/jellyfin-kodi#247]
While trying to figure out why Kodi doesn't display subtitles, I found this traceback in the logs

```
2020-03-25 18:49:48.645 T:1586589920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: unsupported operand type(s) for +: 'int' and 'unicode'
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 261, in onNotification
                                                self.general_commands(data)
                                              File "/root/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/monitor.py", line 390, in general_commands
                                                self.player.set_audio_subs(None, args['Index'])
                                              File "/root/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/player.py", line 190, in set_audio_subs
                                                self.setSubtitleStream(len(mapping) + subtitle - tracks - 1)
                                            TypeError: unsupported operand type(s) for +: 'int' and 'unicode'
                                            -->End of Python script error report<--
```

It seems that `subtitle` sometimes is a `str`, so doing something like
```python
if subtitle is not None:
   subtitle = int(subtitle)
```

fixes this error. Doesn't fix the subtitle display though. Then I's getting a

```OpenStream - Unable to create subtitle parser```

error in the logs.

Unfortunately this cannot be deterministicly reproduced, right now I don't see any of the errors for the same combination of subtitle, video and it "just works"

**Comment by mcarlton00** [comment]
Do you know what format the subs having issues are?  Embedded or external files?  I know there's an existing issue in the server for vobsub (.sub and .idx) where it isn't being served to Kodi properly.  If others are broken as well we need to look into it further.

**Comment by mrmaltgr** [comment]
They are `srt` and `utf-8`. I experience the same problem with other `srt` subtitles which also have BOM and 1024 bytes at start as suggested in https://github.com/jellyfin/jellyfin/issues/2507

Jellyfin version 10.5.2.

**Comment by mcarlton00** [comment]
Do these currently work in the Web UI?  I know the server guys have been working through various subtitles issues lately, wondering if this one falls in with those or if it's a separate issue.

**Comment by mrmaltgr** [comment]
Yes, WebUI works in all cases

**Comment by mcarlton00** [comment]
I've worked through a decent portion of my library that has srt subs and haven't been able to replicate this.  At one point somebody mentioned rescanning the library to pick up external files again after the move to 10.5.x, and my system does that fairly regularly, so it's possible it was a server side weirdness.  We'll leave it open for now until we get more information.

**Comment by mrmaltgr** [comment]
Thanks for looking into this. I will rescan library and report back

**Comment by mrmaltgr** [comment]
I followed these steps:
 - Removed BOM
 - Removed 1024 bytes from start
 - Made sure that all subs are utf-8 and also with unix line endings

and finally I re-scanned the library. 

Everything works as expected! :tada:

Many thanks for looking into this @mcarlton00

**Comment by rootkiwi** [comment]
As a new Jellyfin user I just wanted to report that I had the same problem.

My .srt files were encoded as ISO-8859-1.

Used `iconv -f ISO-8859-1` to change the .srt files to UTF-8 and now it works. Thanks!
