### ISSUE TITLE
Addon trying to connect to previous server ip

### ISSUE THREAD

**Issue by b177y** [jellyfin/jellyfin-kodi#250]
**Describe the bug**
When trying to add a new jellyfin server (to replace a previous server) using the manually add server dialog prompt, it fails to connect, although the server is available to other devices using the web frontend. After looking through the logs, I found that jellyfin was attempting to connect to the original IP given instead of the one entered in the prompt. As I don't have time to look for the bug at the moment, I uninstalled then reinstalled the addon and its all working again.

**To Reproduce**
1. Add jellyfin server with ip X.X.X.Y
2. X.X.X.Y is no longer available, go into settings and change to X.X.X.Z

**Expected behavior**
The addon should connect to X.X.X.Z and work as before, but instead it just keeps popping up with the prompt for the server address.

**Logs**
```
232:2020-03-27 19:41:45.547 T:139845695411968  NOTICE: JELLYFIN.monitor -> INFO::jellyfin_kodi/monitor.py:452 --->[ listener ]
233:2020-03-27 19:41:45.551 T:139844907169536  NOTICE: JELLYFIN.webservice -> INFO::jellyfin_kodi/webservice.py:44 --->[ webservice/57578 ]
234:2020-03-27 19:41:45.551 T:139844946548480  NOTICE: JELLYFIN.connect -> INFO::jellyfin_kodi/connect.py:36 --[ server/default ]
235:2020-03-27 19:41:45.555 T:139844946548480  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:162 Begin connect
236:2020-03-27 19:41:45.556 T:139844946548480  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:70 Begin getAvailableServers
237:2020-03-27 19:41:46.557 T:139844946548480  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:289 Found Servers: []
238:2020-03-27 19:41:46.558 T:139844946548480  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:220 Begin connectToServers, with 1 servers
239:2020-03-27 19:41:46.558 T:139844946548480  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:148 begin connectToServer
240:2020-03-27 19:41:46.558 T:139844946548480  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:248 tryConnect url: http://X.X.X.Y:8096/system/info/public
241:2020-03-27 19:41:49.610 T:139844946548480  NOTICE: Jellyfin.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:106 HTTPConnectionPool(host='X.X.X.Y', port=8096): Max retries exceeded with url: /system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3078049fd0>: Failed to establish a new connection: [Errno 113] No route to host',))
```

**System (please complete the following information):**
 - OS: Linux 64 bit
 - Jellyfin Version: 10.5.0
 - Kodi Version: 18.6
 - Addon Version: 0.5.1

**Comment by mcarlton00** [comment]
The issue with just switching the server in the config is that all of the previously synced media from the original server is still going to be in the database.  Changing the config won't reset that.  The best way to handle switching servers would be to go into `Add-Ons -> Jellyfin -> Perform local database reset` and when it asks to reset your addon settings, say yes.

**Comment by b177y** [comment]
Ah ok thank you. It might be helpful if something popped up asking if you want to reset it when you enter a different IP, as I thought it would just be a case of changing the IP in the settings to reflect the new IP of the server.

**Comment by TrueTechy** [comment]
![image](https://user-images.githubusercontent.com/23321780/77938894-4bcfb180-72ae-11ea-8661-2fc8787b813c.png)

Turns out there is a warning. You have to hit update server information after you've changed the details. Though since this doesn't update the paths in the library it still doesn't solve the problem
