### ISSUE TITLE
library.SortWorker exception

### ISSUE THREAD

**Issue by glogiotatidis** [jellyfin/jellyfin-kodi#254]
I fished the following from my kodi-jellyfin logs. 

Jellyfin 10.5.2, kodi-jellyfin 0.5.1

```
NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:741 Could not find media fd6f012570cdc3992d75d63d0f8bb3dd in the jellyfin database.
2020-03-29 18:37:34.201 T:1328533728  NOTICE: JELLYFIN.library -> ERROR::jellyfin_kodi/library.py:736 None
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/library.py", line 734, in run
                                                self.output[media].put({'Id': item_id, 'Type': media})

```

**Comment by mcarlton00** [comment]
Do you have any steps taken to reproduce this?  I've never seen that error trigger

**Comment by mcarlton00** [comment]
Nevermind, I've found it.  Only seems to happen when you have Music libraries synced locally

**Comment by glogiotatidis** [comment]
Indeed I've a Music library synced locally.

**Comment by mcarlton00** [comment]
I think this and #255 might already be fixed with #249.  You can either test the current master build with [this](https://github.com/jellyfin/jellyfin-kodi/archive/master.zip) link if you want to check, otherwise we should have a new build out within a few days.

**Comment by mcarlton00** [comment]
We've made a new release.  Can you make sure you're running 0.5.3 and test if this is still happening for you?

**Comment by glogiotatidis** [comment]
Re-synced all my music library and didn't see this exception in the logs. 

Thanks for the quick patch. Stay safe :mask: !
