### ISSUE TITLE
Provide method for user to update password

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#258]
**Describe the bug**

Currently the only way to update a user's password to Jellyfin is to reset the database and do the whole sync again.  We should change add a new dialog in the settings menu to allow this.

**Comment by TrueTechy** [comment]
We're not currently storing the password in the addon, only the API token I believe so unless that gets made invalid when a user changes their password I'm not sure we'd need to be aware of password changes. Could be a potential issue if you wanted to change you password so old devices couldn't access your server though
