### ISSUE TITLE
Remove dependency on WAN IP address

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#26]
Currently, the code is doing a lookup of the WAN IP address to determine what authentication method should be used (hinted at [here](https://github.com/jellyfin/jellyfin-kodi/issues/22#issuecomment-488442044) in the different connection options, as well as discussed in more detail [here](https://github.com/jellyfin/jellyfin/issues/236)).  This is unneeded as now all support for pre-hashed passwords has been removed from the server, so all connections should be using the same clear text authentication method.  Remove any unneeded code around the WAN address detection to help keep things clean and maintainable.

**Comment by oddstr13** [comment]
Does #28 solve this issue, or are you including cleaning up this mess and related code?
https://github.com/jellyfin/jellyfin-kodi/blob/c12918f32112b09593cbf5dd415b6e5c9b62895b/resources/lib/jellyfin/core/connection_manager.py#L322-L373

**Comment by mcarlton00** [comment]
I say merge 28 to get the auth fix out there, but for this one I was thinking of cleaning up all the related code around the mode checking and everything.  We're not using that, so I'm of the opinion that it should be pulled out.  Less unneeded code means it's more maintainable down the road.  I'm planning on looking more deeply into it this weekend.

**Comment by dkanada** [comment]
@mcarlton00 I have a PR removing this in [jellyfin-apiclient-javascript](https://github.com/jellyfin/jellyfin-apiclient-java/pull/23) if that helps with the effort at all. It ended up only being a few hundred lines of code.

**Comment by mcarlton00** [comment]
#60 actually removed the dependency already.  Ironically, the big crash was happening while trying to log the IP, it wasn't actually doing anything useful at the time.

I meant to update this ticket and forgot.  There's just a lot of code hanging out about various connection types and logic for choosing which one to use that needs to get cleaned up still (Like oddstr's comment above).  We should probably close this one and open a new ticket for that, though
