### ISSUE TITLE
Wrong mapping audio when transcoding

### ISSUE THREAD

**Issue by Ashyni** [jellyfin/jellyfin-kodi#265]
**Describe the bug**
Hello,
When choosing the audio/sub tracks for transcoding, only the subtitle is good, the audio track seems to always be the last no matter the choice made.
Everything works correctly on the web client.
Movie mapping https://pastebin.com/hfkLQ54k .

**To Reproduce**
. Reduce video quality to force transcode
. Enable audio/subtitles selection
. Play a movie with multi audio/sub
. Select Audio track
. Select Sub track
. Watch the movie

**Expected behavior**
Watch the movie with the correct audio/sub track when using transcoding.

**Logs**
https://pastebin.com/GynM97ix

**System (please complete the following information):**
 - OS: [Android, Windows]
 - Jellyfin Version: [10.5.3]
 - Kodi Version: [18.6]
 - Addon Version: [0.5.3]

**Comment by mcarlton00** [comment]
Confirmed that I'm seeing this on multi audio videos when selecting the "Jellyfin transcode" option in the context menu.

**Comment by Ashyni** [comment]
Let me know if you need testing.

**Comment by mcarlton00** [comment]
Just to be clear, you've set `Enable audio/subtitles selection` to "Enabled" in `Addons -> Jellyfin -> Settings -> Playback`, correct?  Fun fact, I didn't know that option existed until I started digging through the code.  Anyway, if I flip that to enabled I get a dialog when I start transcoding a file and it seems to behave properly for audio.  The file I tested had 2 tracks, one English and one Japanese, and both played correctly after choosing them

**Comment by Ashyni** [comment]
Yes, i have enable this to select the track.
I was wondering if it could be a good idea to have a `Video quality selection` when using `Context menu > Jellyfin transcode` for occasional transcode, the same way audio/sub selection are.
Independent to `Settings > Playback > Video quality` and/or may be move this setting to the `Context menu > Quality transcode` for faster access/adjustment, i don't know, just an idea.

**Comment by mcarlton00** [comment]
That sounds fairly involved to get working, and especially that Kodi will nativly play just about everything it has fairly minimal benefit.  It also deserves it's own issue if it's going to be discussed further.

I can't replicate your issue of the wrong audio file mapping during transcoding.  Is it still present for you?

**Comment by Ashyni** [comment]
Yes, problably fix with this issue i had (CORS issue on my end https://github.com/iwalton3/jellyfin-mpv-shim/issues/77)
Subtitles not always showing up but audio follow the track choose.
I closed the issue, sorry for the time waste.
