### ISSUE TITLE
Potential reforking of Emby for Kodi

### ISSUE THREAD

**Issue by leftl** [jellyfin/jellyfin-kodi#267]
This is more of a discussion post, but I'm working on a fresh fork of the original Emby for Kodi plug-in. With a little effort, I have a fork of 4.1.19 working with the latest versions of Kodi and the Jellyfin server. It seems more performant than the current plugin when it comes to syncing, and fixes the issue that originally sent me on this chase: #35. Other issues like #228 would also be resolved included are various syncing/worker/websocket/playlist improvements. 

This is all fine and dandy, but this would be a loss in pretty much all of the code cleanup, Jellyfin specific additions+bug fixes, and some of work towards python3 compatibility. It also introduces a few new dependencies which I haven't gotten around to messing with (plugin.video.\*.movies, plugin.video.\*.musicvideos, and plugin.video.\*.tvshows) and a new structure for **objects** with a built-in updater which I have just removed for the mean time. There are many features of Jellyfin I don't use and haven't been able to fully test, like music.

I just wanted to ask before I move everything onto github, is this something the team would consider pursuing?

**Comment by mcarlton00** [comment]
I'm interested to see the kinds of changes you did, but odds are we won't be replacing this fork with yours.  Purely from a management standpoint, we're familiar with this codebase and maintaining it, and totally swapping that out for a new baseline will be a big hindrance towards future work.  Just from what you've mentioned I have other concerns as well:

* websocket changes (We're mostly trying to keep in sync with the [api client](https://github.com/iwalton3/jellyfin-apiclient-python) with plans to integrate the two projects together)
* code cleanup (Again, a maintainability standpoint that we've put a decent amount of time into)
* I'm not sure how anybody else feels, but I've personally never liked the .movies/.tvshows dependency system.  It makes it a lot harder to debug than a single unified project

That's not to say that we're not interested in your code at all.  A flat recreation of the project isn't likely to happen, but I'd be happy to review what you've got and we can work together to see what pieces can be integrated here, especially if you've fixed bugs or gotten better performance in areas.

**Comment by dkanada** [comment]
You can of course keep releasing yours even if it doesn't get integrated, which would always be welcome.

**Comment by leftl** [comment]
This can be closed until I get a bit closer towards the current state of the official addon. If you want to give it a look, just check out my [rebase](https://github.com/leftl/jellyfin-kodi/tree/rebase) branch.
