### ISSUE TITLE
sync is not working with videolibrary on MySQL

### ISSUE THREAD

**Issue by thiller2018** [jellyfin/jellyfin-kodi#268]
I'm using the following settings to have a shared database:

<advancedsettings>
  <videodatabase>
    <type>mysql</type>
    <host>xxxx</host>
    <port>3306</port>
    <user>xbmc</user>
    <pass>xbmc</pass>
  </videodatabase> 
  <musicdatabase>
    <type>mysql</type>
    <host>xxxx</host>
    <port>3306</port>
    <user>xbmc</user>
    <pass>xbmc</pass>
  </musicdatabase>

jellyfin-kodi according to kodi.log still looks for local database.

Can this be added?

**Comment by mcarlton00** [comment]
Using this addon replaces the need for using a mysql backend.  It moves the burden of keeping track of your watched status and libraries in sync to the Jellyfin server.  So no, support for mysql in addition to the builtin library isn't planned.

**Comment by robinsmidsrod** [comment]
@mcarlton00 For reference, if you've been running with MySQL for some time, how do you migrate from MySQL back to local database, and keep all of your stuff, so that you can use Jellyfin for Kodi? If this is already documented in Kodi docs, a pointer would be very useful.

**Comment by robinsmidsrod** [comment]
I think I actually found the information on how to do this in the Kodi wiki. It's under the import/export database page, located here: https://kodi.wiki/view/Import-export_library
