### ISSUE TITLE
Transcoded videos do not appear to be buffered the way direct play videos are.

### ISSUE THREAD

**Issue by TheFeshy** [jellyfin/jellyfin-kodi#271]
**Describe the bug**
I have adjusted buffer settings in kodi via advancedsettings.xml, to compensate for my spotty ISP upload.  This works as expected for videos that direct play - the buffer visually fills up on the play bar, network traffic comes in big blocks, and the video plays smoothly.

However, when playing a video that requires transcoding by jellyfin, this is not the case - the play bar shows no signs of buffering, the network traffic is in smaller chunks every second, and I get frequent stalls

**To Reproduce**
1. Have a video in your library
2. Set buffer settings in kodi's advancedsettings.xml to higher than default values (example attached below)
3. Play the video via jellyfin-kodi
4. Pause it and watch the buffer bar fill in light gray indicating the position buffered to
5. Stop the video
6. Play the video again, but this time choose force transcode
7. No buffer bar is visible, nor does network traffic or playback indicate buffering.

**Expected behavior**
Buffering behavior should be identical between transcode and direct play

**Logs**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Jellyfin is running in Docker, Kodi and Jellyfin-kodi on Odroid C2s running coreelec
 - Jellyfin Version: 10.0.5
 - Kodi Version: 18.6
 - Addon Version: 0.5.3

**Additional context**

.kodi/userdata/advancedsettings.xml:

`<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>278921216</memorysize>
    <readfactor>20</readfactor>
  </cache>
</advancedsettings>`

Transcoding speed isn't an issue in this case - I'm seeing transcoding speeds of 200 fps or more.

**Comment by mcarlton00** [comment]
I'll need to verify, but this may be a server thing.  I remember discussion about the buffering there, but I'm not sure if it's provided to clients as soon as it's transcoded, or if it only streams out at a constant rate and the reset is stored on the server while waiting for the client to need it.

**Comment by mcarlton00** [comment]
Talking with the server crew about this and there's not really anything that can be done about it.  Transcoding is much more "on demand" and only serves very small chunks at a time when they're needed, so there's not really anything we can do client side to increase the caching distance.

**Comment by JustAMan** [comment]
Adding here... first of all, are you sure your server is keeping up with transcoding? What you describe seem to me like lack of processing power on server side to transcode it ahead of time.

And other point, just for the completeness - pieces aren't served "when needed" but "when requested", so _maybe_ addon requests them not frequent enough.

But my bet is on server being slow on transcoding. If you @TheFeshy could show us ffmpeg logs from transcoding attempt I would be able to tell better.

**Comment by TheFeshy** [comment]
@JustAMan Here you go: [ffmpeg log from jellyfin](https://pastebin.com/ZUMmMtmG)

I set the maximum bandwidth to 3.2 mb/s, selected "jellyfin transcode" from the menu, on a player that is running on the same NAS that is running jellyfin, to eliminate any network issues.  Jellyfin's dashboard reported between 175 fps and 200 fps on the transcode.  At no point did it show the buffer bar (light gray on the video progress bar) filling in; even when paused.  I let it run about ten minutes, at which point the video was around 2/3rds transcoded (judging by the red transcoding bar on the jellyfin dashboard.)  Server is set to use quicksync, and doesn't break 50% CPU usage while transcoding.

**Comment by JustAMan** [comment]
Hmm, server is definitely converting them fast enough. @mcarlton00 it could still be a client issue here, maybe Kodi is requesting next chunk too late, or is accounting for buffer somehow differently.

**Comment by charredchar** [comment]
I know this is closed and old but it is an issue that I think should be looked at. I don't know if this is purely a server-side thing because there are options for throttling transcoding and it seems like other versions of the client buffers better than Kodi while transcoding.

I duplicated this myself and I'm looking for a solution. I travel often and a lot of hotels have flaky WiFi, I'll get a couple minutes of 15Mbps then nothing. It bounces around like this and a decent buffer would fix it. Kodi has buffer options that could fix it but it doesn't seem to take effect when transcoding, only direct play. It seems to me that the plugin needs to be made to stream the data as soon as it's available, not while it's playing.

You can also hit `o` on a keyboard to see the buffer percentage and see it isn't the same between direct play and transcoding. It'll hit 100% instantly and forward (the size buffered) stays at 0.00 B.
