### ISSUE TITLE
Receive misspelled as recieve in websocket.py comments

### ISSUE THREAD

**Issue by scottwedge** [jellyfin/jellyfin-kodi#278]
**Describe the bug**
"receive" is incorrectly spelled as "recieve"

**Expected behavior**
Expected no spelling errors.

**Comment by oddstr13** [comment]
There is no need to open a separate issue when submitting PRs to fix it right away :slightly_smiling_face:
Also, try to make more descriptive issue/pull-request titles next time. Those are used in changelogs, and are present in all notifications regarding the issue.
