### ISSUE TITLE
can't start jellyfin : Method 'RunAsync' does not have an implementation.

### ISSUE THREAD

**Issue by krodelabestiole** [jellyfin/jellyfin-kodi#283]
Hi, I use jellyfin in docker. It use to work but I tried to update by removing the image and grabbing it again. But I can't start it any more, here is the error message :

```
[FTL] [1] Main: Error while starting server.
 System.TypeLoadException: Method 'RunAsync' in type 'Emby.Kodi.SyncQueue.EntryPoints.LibrarySyncNotification' from assembly 'Emby.Kodi.SyncQueue, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null' does
 not have an implementation.
```

How can I disable this plugin while I don't have access to the Jellyfin interface ?

And how to fix this issue and have the plugin to work properly again ?

**Comment by krodelabestiole** [comment]
I had an old `Emby.Kodi.SyncQueue.dll` file remaining in my `/config/plugins` directory. removing it has fixed the issue, sorry for the useless message.

**Comment by oddstr13** [comment]
Thank you for reporting back :slightly_smiling_face:
