### ISSUE TITLE
Special Characters on smartplaylists of library folders not working

### ISSUE THREAD

**Issue by Norin-Radd** [jellyfin/jellyfin-kodi#292]
Kodi 18.6

as said, special characters are not being used when creating the smart playlist name (or the tags)

for example library folder on jellyfin is animação smartplaylist on kodi shows animao, séries show sries.

its Portuguese, ISO/IEC 8859-1 Latin.

suppose its an easy fix...

**Comment by mcarlton00** [comment]
This is when creating playlists from within Kodi, or when using playlists you've made on the server?  You can manually define the name of a smart playlist when it's created, so I'm not entirely sure where the issue lies here.

**Comment by Norin-Radd** [comment]
I did not create playlists on the server nor in kodi.
It's my server library folder... addon when importing movies and series to the database automatically create playlists in kodi of the content of my server library folder... i suppose its based on tags.
This is an addon issue.

**Comment by mcarlton00** [comment]
I'm afraid I'm still lost as to where you're seeing this. When I sync content down I don't see any playlists available either going through "Music" on my home screen or through "Add-Ons -> Jellyfin -> Music"

**Comment by Norin-Radd** [comment]
Hi there,

Its not music playlists... its video smart playlists. 

As i understand when importing video libraries, the addon sets dummy folders and creates smart playlists based on tags... the tags are the name of the libraries on jellyfin.

you either see it on tags or on smart playlists tabs.

btw the problem is fixed. Because when importing my libraries i haven't installed the Portuguese addon first... so when creating the tags on import it missed the special characters of the librarie name. ( é, ç, ã)

So you have to install first the language addon then import libraries to get propper naming of the tags smart playlists if your naming of libraries has special characters.

Problem is fixed, you can close this. 

I hope know i have explained myself correctly and the "false" issue is understood besides of being corrected. 

Sorry for the headache trying to reproduce this, and thank you for the help.

**Comment by mcarlton00** [comment]
Ah, I understand now.  Glad you got it worked out.  No worries, just trying to keep everything working as best we can.
