### ISSUE TITLE
Playlist items not appearing in the order set in Jellyfin

### ISSUE THREAD

**Issue by jamesmorganti** [jellyfin/jellyfin-kodi#293]
**Describe the bug**
Playlists with TV shows are ordered by Season/Episode rather than the order set in Jellyfin.

**To Reproduce**
1. Create a playlist in Jellyfin with TV shows, re-arrange to have them not in episode order, eg:
```
Show A S01E05
Show A S01E01
Show A S01E02
Show A S01E03
Show **B** S01E01
Show A S01E04
```

2. Navigate to Jellyfin playlists within the Kodi addon (Add-Ons > Video add-ons > Jellyfin > Playlists)
3. Playlist displays in the following order:
```
Show A S01E01
Show B S01E01
Show A S01E02
Show A S01E03
Show A S01E04
Show A S01E05
```

**Expected behavior**
Playlist to appear in order set in Jellyfin, namely:
```
Show A S01E05
Show A S01E01
Show A S01E02
Show A S01E03
Show **B** S01E01
Show A S01E04
```

**Logs**
N/A

**Screenshots**
![Jellyfin Web UI](https://user-images.githubusercontent.com/11370070/81410036-05386700-9138-11ea-9de1-b55b820cc855.PNG)
![Kodi UI](https://user-images.githubusercontent.com/11370070/81410042-07022a80-9138-11ea-9ddd-98af3e887272.png)

**System (please complete the following information):**
 - OS: Kodi on Android TV (Shield) and Windows
 - Jellyfin Version: 10.5.5 (linuxserver/jellyfin docker image)
 - Kodi Version: 18.6
 - Addon Version: 0.5.5

**Additional context**
- When movies are included in a playlist, they are placed at the end in alphabetical order
- Media files are stored at `/tv/<series name>/Season <season number>/S0<season number>E0<episode number> - <episode title>.<extension>` and `/movies/<movie name> (<year>)/<movie name> (<year>) - <edition>.<extension>`
- The addon is configured to access media through jellyfin rather than directly
- Although the "Sort By" option says date, it is in fact sorting by episode number
- Opening the menu with backspace doesn't give an option to change what is being sorted by, only ascending/descending

**Comment by mcarlton00** [comment]
Confirmed.  I'm seeing it with music playlists as well.

**Comment by mcarlton00** [comment]
Related to #228

**Comment by mcarlton00** [comment]
Issue is tracked to this line.

https://github.com/jellyfin/jellyfin-kodi/blob/19b4e90291c58e03dc766f10702b59c913a269eb/jellyfin_kodi/downloader.py#L105

However I'm hesitant to just change that because it's almost guaranteed to have an unintended effect elsewhere as well.  We could likely put in a special case for playlists here, however it might be better to just wait until we rework that whole functionality into something that's actually somewhat sane (See #228 for my ranting on that)
