### ISSUE TITLE
playback feels like its in fast forward at time

### ISSUE THREAD

**Issue by leaderdog** [jellyfin/jellyfin-kodi#294]
When playing movies or shows on my htpc it fieels like the color is too vibrant and the picture has this weird feeling like it hits fast forward to keep everything in sync.. not sure if sync is the right word.  But playback isn't smooth.  It's not stuttery, just a weird fast forward view.

sorry that's horrible for an explanation but I can't really explain it better.  I don't know if there is something I need to turn off or if it's because playback is via http instead of straight samba share (at least I don't believe it is?) like I used to do in kodi (which never had this anomaly) 

Windows 10 (updated as of last week) htpc
Jellyfin version 10.5.3
Kodi 18.6
plugin kodi sync queue 4.0 is installed.

Anyone else experiencing this, or know what I need to do to smooth out the playback.  Plex played fine (just didn't want to use it any more) kodi playing directly from my media server was flawless.  I just wanted the centralized server that kept track of watched shows.

Thanks in advance.

**Comment by mcarlton00** [comment]
I may have seen something similar happen a few times, but only in a very specific circumstances.  The time I remember seeing it is when I have a video playing and back out to the main menu without pausing or stopping it.  When I switch back to the video, it almost does a fast forward/catch up to the current timestamp.  But that's the only time I can think of seeing something like what you're describing.  Could that be what you're talking about?

**Comment by leaderdog** [comment]
That sounds about right.  But it's doing it through out the whole movie.  But my experience may be more subtle, but constant.  It's usually not bad in movies that aren't very action filled.  I watched Edge of Tomorrow and it was very noticeable through the entire movie.  To me that is extremely distracting.  I'm sure many might not care or notice it.

**Comment by mcarlton00** [comment]
I've never noticed it during normal playback.  Is there anything in your logs suggesting there's an issue here?  Have you noticed it in other movies?  I seem to remember Edge of Tomorrow having lots of weird speed variations in the movie itself, so maybe you were just seeing that

**Comment by leaderdog** [comment]
No errors in logs in Jellyfin or in Kodi.  

I have noticed it in many shows, both Tv shows and movies.  It's been bugging me for the past couple weeks, that's when I started with Jellyfin for kodi.

I'll keep an eye on it.  see how consistent it really is.  I just found it odd that it's the only setup I've noticed it with.

I did test Edge of Tomorrow on one of my other pc just using Media Player Classic Home Cinema, and I couldn't really see any sped up parts.  it seemed to play smoothly.  And it was playing it from my media server as well.

**Comment by leaderdog** [comment]
Update:

I've noticed that in the menu occasionally there is a bit of a pause.  Where it seems Kodi hiccups and then resumes.  

I turned off kodi sync while playing shows, but that didn't fix it in either the show or the menu.

Is this some odd windows 10 thing? or is there some setting in kodi that's refreshing every x number of seconds or minutes?

**Comment by mcarlton00** [comment]
I've never heard of it happening the way you're describing.  I can't think of what could be causing it.  It's extra weird that it only happens with the Jellyfin addon and not native Kodi, as we're using Kodi's built in database for metadata.  Unless it's some sort of network bandwidth weirdness you're having, but that seems unlikely.

**Comment by leaderdog** [comment]
It is a bit odd that's for sure.  The colors are sooo over saturated in kodi with Jellyfin too.  I just watched survivor finally and it was almost blinding how bright the colors were.  Just to compare, I shut it off, loaded up plex and the colors looked natural.  Turned it off,  played it in Kodi again to  confirm.  This time I just hit pause in Kodi and and then alt tabbed into Plex and the colors in plex were equally over saturated.  Turned off both programs and tried plex again and it was back to natural looking colors.

Originally I used Koid as the operating system version.  (I forget what it was called) but I kept having the odd lock up issues when it loaded or switching profiles, and a few times lost all the data and had to remark all shows, that's why I started looking for a proper server side so I wouldn't have to do that any more.  Plex plays correctly, I just loathe how often I've had to go to a website and enter that stupid pin number.   Kodi at least I can just switch users.  Only a few times does the syncing mess up and then I have to kill the instance and start it up again.  By this I mean, if you try to switch users while kodi sync is doing it's thing, it just hangs.  You have to kill it and reload.

It's been a weird journey that's for sure.  I'm not sure if it's Kodi having some interaction with windows 10 that it doesn't like.  And I did install windows 10 1909 when it was closer to it's original release date.  Where literally half of the function for networking was completely screwed up.  When I installed it on my Server pc installing Radarr or Sonarr that should have taken me 5 minutes took close to 5 hours to diagnose because it boiled down to windows broke the firewall.  Once I disabled the firewall all internal networking finally worked.  No matter how I put in the firewall exception (that is usually automatic) would it allow for me to access it via http.  All systems have been updated to the latest version of windows. but honestly. something from that may still have been corrupted or when I tried to "Fix" it I may have created a problem.

I guess I should just suck it up and reinstall windows and the updates and all the tweaks. ugh.  frickin windows ;)

If you have any suggestion on the over saturation of color I'd love to know why it's doing that.

**Comment by leaderdog** [comment]
ok, I got the over saturation fixed. not sure what fixed it, but I had to close kodi in order for anything to take effect. so not sure which setting I turned off to fix it.

I'll keep an eye on the stutter/fast forward and see if I didn't accidentally correct it.  I turned off "force http:" so maybe that'll take care of it.
