### ISSUE TITLE
HTTP headers are not properly encoded.

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#302]
**Describe the bug**

Running Jellyfin server on Rpi4. There is already 3 local Windows 10 PC connecting to the server with Jellyfin addon for Kodi without a single problem. But 1 PC can't connect. This PC can connect to the web version (192.168.1.31:8096) but not with the Kodi addon (Kodi 18.7, Addon 0.5.5).

Here is my logfile : https://paste.kodi.tv/zemiguqexo

Already tried completely resetting network config on that PC, didn't work. I don't think it comes from that (but I'm no expert). Looked into my router, there is no setting distinguishing this PC from the others.

I looked into everything I could think about, I searched for days and days about this issue. I can't find a single reason why it can't connect. There no visible reason why EVERY OTHER PCs can connect and not this one.

I come to the conclusion I will never be able to fix this alone. So I'm asking for your help. Any help, any answer is welcome.

**To Reproduce**

1. Install Kodi latest, addon latest
2. Try to connect to the local server
3. I can't. It says it can't connect.

**Expected behavior**

Should connect to the server like the dozens that are already doing it locally and remotely.

**Logs**

Here is my logfile : https://paste.kodi.tv/zemiguqexo

**Screenshots**

https://imgur.com/a/5tVzXIP

**System (please complete the following information):**
 - OS: [Windows 10 latest]
 - Jellyfin Version: [10.5.5]
 - Kodi Version: [18.7]
 - Addon Version: [0.5.5]

**Additional context**

This is the 1st time I see something THAT beyond understanding. I literally can't even tell or approach the source of the issue after days of research. Any help is welcome, don't hesitate to ask if you need more details to help. Have a good day.

**Comment by oddstr13** [comment]
Looks like the `é` in the computer name is the cause of the problem.
HTTP headers are not properly encoded.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> Looks like the `é` in the computer name is the cause of the problem.
> HTTP headers are not properly encoded.

Just changed the name of the computer to replace the é by a e. Thank you so much. One of the worst computer headache of my life for a single letter. I feel dumb now. 

But I'm happy to have that working now. I guess this could be solved in future addon releases ?

**Comment by oddstr13** [comment]
Yes, this is definitely an issue we want to solve.
