### ISSUE TITLE
Error during Jellyfin-Kodi sync

### ISSUE THREAD

**Issue by jokerknight** [jellyfin/jellyfin-kodi#31]
1.JELLYFIN SERVER STATUS (OPENED)
2.JELLYFIN SYNC QUEUE PLUGIN STATUS (INSTALLED)

SCREENSHOOT IN THE ATTACH FILE

![1231](https://user-images.githubusercontent.com/7285685/57907224-56a87000-78af-11e9-9d49-1421f4295172.jpg)

![image](https://user-images.githubusercontent.com/7285685/57907463-1f868e80-78b0-11e9-9bbc-938581d51a2d.png)

**Comment by jokerknight** [comment]
@anthonylavado

**Comment by jokerknight** [comment]
BTW, 
    It's any client can running on my iPhone, i have tried https://github.com/jellyfin/jellyfin-react-client，but it's look like uncompleted.

**Comment by oddstr13** [comment]
Please provide software versions;
 * Jellyfin server version
 * Kodi Sync Queue server plugin version
 * Jellyfin Kodi version
 * Kodi version

**Comment by oddstr13** [comment]
That being said, it looks like the issue attempted solved by #16, that is, database changes in Kodi with version 18.

I would suggest using Kodi 17 for now, until we have a proper fix for Kodi 18 in this plugin.
