### ISSUE TITLE
Playing a video completely freezes Raspberry pi 3

### ISSUE THREAD

**Issue by draganczukp** [jellyfin/jellyfin-kodi#316]
**Describe the bug**
Whenever I try to play a movie from my server using Kodi running on a Raspberry Pi 3, the entire system freezes. I can't do anything using a remote app and I can't SSH into the device. The only thing I can do is remove the power cord and plug it back in.

**To Reproduce**
1. Open jellyfin addon
2. Go to the video library
3. Play any video

**Expected behavior**
The movie starts playing

**Logs**
[kodi.log](https://gist.github.com/draganczukp/a6f98f90e8817138d7ff6bbc081edecb)

**System (please complete the following information):**
 - OS: Arch Linux arm
 - Jellyfin Version: 10.5.5, running in docker
 - Kodi Version: 18.7
 - Addon Version: 0.5.6
 - Playback Mode: Both

**Additional context**
There's PiHole also running on the same RPi. I doubt it would have any effect, since my phone also uses the PiHole and can play videos no problem.

**Comment by mcarlton00** [comment]
Have you tried using Kodi directly without the addon in this case?  It's been several years, but last time I tried installing Kodi directly to a vanilla Arch or Raspbian install on a Pi it basically tanked the whole system.  Stuff like LibreElec and OSMC have put in a lot of work to optimizing the OS for Kodi, and I'm not entirely sure the hardware is strong enough for Kodi on top of a standard OS and other programs.

**Comment by draganczukp** [comment]
The PI handled Kodi quite good, although I had to lower the resolution to 720p. Trying to play from Jellyfin was the first major issue.

Anyway, I decided to stop using a RPi for media and moved Kodi to an old laptop. This will at least let me have some fun with the Pi, like running Pi-Hole, or a SMB domain controller.
