### ISSUE TITLE
Library's item with broken link

### ISSUE THREAD

**Issue by mr-mental** [jellyfin/jellyfin-kodi#318]
**Describe the bug**
Every single day I have to repair my library to be able to play items inside. They are displayed are available but when playing "This item doesn't exist anymore" popup like

**To Reproduce**
Hard to say.

1. Repair library
2. Play an item or more than one
3. Come back the day after without touching the library at all
4. Play another item (next up episode)
5. Popup is displayed, need to repair 

**System (please complete the following information):**
 - OS: Linux
 - Jellyfin Version: 10.5.5
 - Kodi Version: 18
 - Addon Version: 0.5.6
 - Playback Mode: Default

**Comment by mcarlton00** [comment]
I've only seen this in the past with Native mode when the media got disconnected in the mean time, but never in add-on mode (which is the default).  Do you have anything else set up in Kodi that could be causing database conflicts?

**Comment by mr-mental** [comment]
I had the emby plugin installed but I removed everything I found.
My Emby server is still running and connected in parallel but  should not interfer.

I have removed my connector in Radarr and Sonarr which where updating Kodi directly. It never caused trouble to Emby but might be the cause?

**Comment by mcarlton00** [comment]
If the Emby addon was still installed and configured that likely had something to do with it.

I may be wrong, but I don't believe having the *arrs pointed at Kodi in this situation will do anything.  The JF for Kodi addon receives new media info directly from the server whenever it's added.  So at best it's just causing redundant scans and at worst it's not doing anything.

**Comment by mcarlton00** [comment]
Are you still having database problems after cleaning up other addons?

**Comment by mr-mental** [comment]
Hi there,
I have performed several tests, the problem happend with Emby installed even when disabled. I also had Sonarr/Radarr linked to Kodi directly for content updates.
I have uninstalled Emby addon completely and removed the link between -arr apps and Kodi (which was not causing trouble while using Emby), now it seems stable.
I will let you know if it comes back.
Thanks for your support
