### ISSUE TITLE
Playback failure on Odroid C4

### ISSUE THREAD

**Issue by PANiCnz** [jellyfin/jellyfin-kodi#329]
**Describe the bug**
When I try to play a TV Show or Movie through Kodi playback fails. The "Working" popup appears on the bottom right of the screen and spin indefinitely. 

**To Reproduce**

1. Try to start a video from the TV Shows or Movies library

**Expected behavior**
Video should play.

**Logs**
http://ix.io/2pVl

**System (please complete the following information):**
 - OS: CoreELEC 9.2.3
 - Jellyfin Version: 10.5.5
 - Kodi Version: 18.7
 - Addon Version: 0.5.8
 - Playback Mode: Add-On

**Additional context**
Have a similar install with LE 9.2.3 and a Pi4 that is working without issue. Video can be played back fine through the Jellyfin web gui also. Issue looked to be isolated to my C4.

**Comment by oddstr13** [comment]
The errors in your log file suggests the network is down on your C4.

Verify that it is indeed connected to the network, and try again (a reboot might do it)

**Comment by PANiCnz** [comment]
Had some network issues couple of day ago but not today. Successfully watched media off an NFS share before and after the issue with Jellyfin. Also no issues connecting to Tvheadend and watching live TV.

**Comment by mcarlton00** [comment]
What's in your Jellyfin server logs during this?

**Comment by PANiCnz** [comment]
No corresponding entries in the server logs. 

In the client logs at 2020-06-23 18:52 there is a python error from when I tried to watch an episode.

**Comment by mcarlton00** [comment]
Enable debug logging in the addon (`Add-Ons -> Jellyfin -> Settings -> Advanced`) and try again.  What you've given so far isn't really giving us anywhere solid to start with except for the network errors.  If you're reaching the server, then there should be some indication of that in the server logs as well.  If the server has no indication that you've logged in (in the logs or in the server dashboard) it's more evidence that you have a network problem of some kind.
