### ISSUE TITLE
Can't direct play x265 10bits on all clients, even if all clients supports it when played locally

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#333]
**Describe the bug**

When I try to play from Jellyfin (addon mode) a x265 HEVC 10bit encoded file, it loads for a few seconds then stop. My PC supports it fully, I can play the same file locally with Kodi too.

**To Reproduce**

Try the same x265 10bit file, try it locally first then from the Jellyfin server throught Kodi addon. (addon mode)

**Expected behavior**

Should play the file normally

**Logs**

Here is my log : http://paste.kodi.tv/limuyuyaci

**Screenshots**

![image](https://user-images.githubusercontent.com/64923542/86528114-703abb80-bea5-11ea-98cc-616bf301e614.png)
![image](https://user-images.githubusercontent.com/64923542/86528116-7761c980-bea5-11ea-8c07-adac1e90a4e3.png)

**System (please complete the following information):**
 - OS: Server : Dietpi on Rpi4, Client : Windows 10
 - Jellyfin Version: 10.5.5
 - Kodi Version: 18.7 (from x64)
 - Addon Version: 0.5.8
 - Playback Mode: Add-on

**Additional context**

This bug is a big problem for me as my 5tb movie/serie database is mostly 10bit encoded. Plus a lot of things can only be found in this format now. It's very strange that it can't play as my client supports it completely. Any help is welcome, have a good day.
If more details are needed, don't hesitate to ask.

**Comment by LeVraiRoiDHyrule** [comment]
Does somebody have an info on this ?

**Comment by TrueTechy** [comment]
> Does somebody have an info on this ?

@LeVraiRoiDHyrule we are a community of volunteers who work on Jellyfin in our spare time. You have to be patient and we will get back to you at some point.

As for the issue, the logs suggest the server is returning a 500 error 
> CCurlFile::FillBuffer - Failed: HTTP returned error 500
> CCurlFile::Open failed with code 500 for http://192.168.1.31:8096/Videos/d5064f5f005d0491fddda2159c2ba221/stream?static=true&MediaSourceId=d5064f5f005d0491fddda2159c2ba221&api_key=5609a325d8b74ac885ebf7ea89d51ce2:

Is there anything in your server logs when you try to play the videos which might give a better idea what's happening ?

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> > Does somebody have an info on this ?
> 
> @LeVraiRoiDHyrule we are a community of volunteers who work on Jellyfin in our spare time. You have to be patient and we will get back to you at some point.
> 
> As for the issue, the logs suggest the server is returning a 500 error
> 
> > CCurlFile::FillBuffer - Failed: HTTP returned error 500
> > CCurlFile::Open failed with code 500 for http://192.168.1.31:8096/Videos/d5064f5f005d0491fddda2159c2ba221/stream?static=true&MediaSourceId=d5064f5f005d0491fddda2159c2ba221&api_key=5609a325d8b74ac885ebf7ea89d51ce2:
> 
> Is there anything in your server logs when you try to play the videos which might give a better idea what's happening ?

No problem I can wait, sorry if I looked impatient. You are doing a wonderful job and I respect that. I really don't want to be disrespectful and love your work.
Thanks a lot for having taken a look at my issue.

I tried reproducing the issue with another HEVC 10bit video I have, here are both logs of Kodi and Jellyfin server:

Kodi:
http://paste.kodi.tv/qurugefohi

Jellyfin server:
https://pastebin.com/UjYnWw7k

There is definitely also issues on the Jellyfin server, but I can't manage to find what's causing them. Could you help me if you have time ?
Thanks again and have a good day.

**Comment by TrueTechy** [comment]
The server logs are showing permission errors when it's accessing your files. Make sure the user Jellyfin is using can read the files you're trying to access

```
System.UnauthorizedAccessException: Access to the path '/mnt/westernhdd/SÃ©ries/Mr. Robot (2015)/Saison 1/Mr. Robot - S01E03 - D3bug.mkv (2015-07-08) 1080p h265 10bits 6ch AC3 L[fra, eng] S[fra, fra].mkv' is denied.
 ---> System.IO.IOException: Permission denied
```

**Comment by LeVraiRoiDHyrule** [comment]
I edited the permissions on my dietpi server, to give the jellyfin user the jellyfin permission group on all my series folder, and it works ! It now plays correctly !

Thanks a lot for pointing out that it was a permission problem, looked a lot into it but I'm a dummy at reading logs correctly.
Thanks again and have a great day !

(I will delete my logs as it contain my DDNS address)

**Comment by mcarlton00** [comment]
As an aside for future reference, if you enable debug logging from within the Jellyfin addon (instead of through Kodi itself) it does do log sanitation so your data will remain private.
