### ISSUE TITLE
Can not sign in using Kodi

### ISSUE THREAD

**Issue by fakeid30** [jellyfin/jellyfin-kodi#34]
When I try to sign in using Kodi I put my server url and username (I have no password set), I input my username and the sign in button does not work. 

Tested on Kodi 18.2 in Windows 10 64 bit and Android 9.

**Comment by oddstr13** [comment]
I'm unable to reproduce with latest master of jellyfin-kodi in Kodi 17.6 (Linux) and 18.2 (Windows 10).

How are you connecting to the server?
http/https? remote (over the internet) or local? Using reverse proxy?

What do you mean by "the sign in button does not work"? A screenshot of where the issue occurs would be nice.

If you are attempting to connect remotely over http, #28 which is merged into master, but not in the kodi plugin repo yet probably fixed the issue.

**Comment by fakeid30** [comment]
I fixed it , seems like where my normal jellyfin login was jellyfin.xxx.x with no port I had to use https://jellyfin.xxx.x with 443 port.

Thanks for the answer though @oddstr13
