### ISSUE TITLE
Cinema Mode not working

### ISSUE THREAD

**Issue by erikjunker** [jellyfin/jellyfin-kodi#340]
**Describe the bug**
Cinema Mode does not play pre-rolls before a movie

**To Reproduce**
1. Enable Cinema Mode
2. Play a random movie
3. Observe that the movie starts without playing pre-rolls

**Expected behavior**
There should be pre-rolls/trailers before the movie starts with Cinema Mode enabled

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Libreelec on RPI3
 - Jellyfin Version: Latest
 - Kodi Version: 18.7.1
 - Addon Version: 0.58
 - Playback Mode: Add-On

**Additional context**

**Comment by mcarlton00** [comment]
Did some digging on this.  Cinema Mode is a relic from before the fork and has apparently never worked for us.  It integrated with the "Intros" plugin in Emby to read a configurable number of pre-rolls before a movie played.  It looks like that plugin was never ported over to Jellyfin, so the feature as it sits now doesn't work.

However, I think we can adapt it to work slightly differently.  The web client has the "More like this" section when viewing the details screen of a movie.  We should be able to pull a few random entries from that and play their trailers.  This does bring other challenges though.  Namely the question of local trailers stored in the server vs remote trailers from youtube that would require [another addon](https://github.com/jdf76/plugin.video.youtube) to play properly.

**Comment by erikjunker** [comment]
Thanks for taking a look at this. I don't think I'll be able to contribute much in terms of fixing this, but I know iTunes is a pretty popular place to get trailers from: https://trailers.apple.com/#section=mostpopular

Not sure if that will be helpful in any way?

**Comment by mcarlton00** [comment]
I've been informed that the existing api endpoint that we're using _should_ work with locally downloaded trailers that have been added to the library.  I'll need to track down the naming convention for that and do some testing

**Comment by oddstr13** [comment]
Cinema Mode works, but requires the Jellyfin server to provide preroll(s)
The Intros plugin does this; https://jellyfin.org/docs/general/server/plugins/index.html#dkanadas-repo
