### ISSUE TITLE
movie wont start from from the begin

### ISSUE THREAD

**Issue by riddertommie** [jellyfin/jellyfin-kodi#341]
**Describe the bug**

If i start a already watched movie/serie and the question pops up if i want to start from the begin or from x:xx:xxx if i select from the begin in does not 'listen' to that and wil start from x:xx:xx. It shows the correct correct 'stop' time.

**To Reproduce**

1. start a not finished movie/serie
2. click on start from begin

**Expected behavior**
start from the begin

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: (multiple (android tvbox, androidtv and libreelec (rasp) 
 - Jellyfin Version: [e.g. 10.6]
 - Kodi Version: 18.3
 - Addon Version: Kodi Sync Queue 5.0.0.0
 - Playback Mode: Add-On

**Additional context**

**Comment by mcarlton00** [comment]
I'm seeing this as well, must be a regression somewhere.  Thanks for reporting
