### ISSUE TITLE
Unable to connect to server when Kodi starts automatically at boot

### ISSUE THREAD

**Issue by bradgy** [jellyfin/jellyfin-kodi#343]
**Describe the bug**
Jellyfin for Kodi doesn't connect to server when Kodi is automatically started at system login. Requires exiting Kodi, then loading Kodi again for Jellyfin for Kodi to connect.

**To Reproduce**
1. Set Kodi to autostart in 'Startup applications' in Ubuntu 20.04. Reboot.
2. See there's no notification that Jellyfin for Kodi has started up.
3. Try playing a video from Jellyfin, no response from Kodi.
4. Exit kodi
5. Immediately load Kodi again
6. See notification that Jellyfin for Kodi has started up successfully
7. Play video from Jellyfin, should work straight away now.

**Expected behavior**
Jellyfin should connect to the server successfully when Kodi first loads at system startup.

**Logs**
Kodi log when autostarts 
[coldbootkodi.log](https://github.com/jellyfin/jellyfin-kodi/files/4997363/coldbootkodi.log)
Kodi log when started manually from the desktop
[startfromdesktop.log](https://github.com/jellyfin/jellyfin-kodi/files/4997368/startfromdesktop.log)

**System (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Jellyfin Version: 10.6.1
 - Kodi Version: 18.7
 - Addon Version: 0.5.8
 - Playback Mode: Not sure - it's the default one though.

**Additional context**
I have kodi load automatically with system login as I use it as a HTPC frontend with just a controller. 
Seem to be numerous [Errno 101] Network is unreachable errors in the Jellyfin addon NOTICE logs in the "coldboot.log" file, whereas the addon is able to find and connect to the server successfully in the "startfromdesktop.log" files.
I have checked that the network is up when the system starts, and have checked that other addons that rely on the network being up at system start are able to connect.
I have had this set up going for a few months now, and this behaviour is only a recent observation. 
In a potentially unrelated issue, I had to reinstall the Kodi sync queue plugin after the Jellyfin server update recently. This issue was present before the 10.6 server update.

**Comment by mcarlton00** [comment]
This sounds pretty identical to my setup in the living room and I haven't seen this issue.  Do you have a user account set to auto log in on boot?  I wonder if that's happening before the network is ready, or perhaps networking is up but DNS isn't ready.

**Comment by oddstr13** [comment]
`Network is unreachable` is the error message you get from the kernel when the network interface isn't up.
You can test this by pinging a host and then disabling WiFi, you'll get the same exact message there.

```python
2020-07-28 10:54:21.145 T:140115423430400  NOTICE: JELLYFIN.jellyfin.connection_manager -> ERROR::jellyfin_kodi/jellyfin/connection_manager.py:230 Traceback (most recent call last):
                                              File "/home/brad/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/jellyfin/connection_manager.py", line 228, in _server_discovery
                                                sock.sendto(MESSAGE, MULTI_GROUP)
                                            error: [Errno 101] Network is unreachable
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/jellyfin/connection_manager.py", line 228, in _server_discovery
                                                sock.sendto(MESSAGE, MULTI_GROUP)
                                            error: [Errno 101] Network is unreachable
```

Does this mean the addon should outright fail? Probably not.
But the underlying issue here is that your network isn't up yet when Kodi starts.

**Comment by bradgy** [comment]
Thanks for the insight on this.

@mcarlton00 yes, the system is set to autologin to my user account at startup, then kodi autostarts from there. What I'm seeing is consistent with the network (or DNS) not being ready, for sure. I don't have an optimal network situation for this box: powerline ethernet which has wildly variable latency and low speeds compared to my main cat 5e backbone.

@oddstr13 as mentioned above my network solution is not great, so this makes sense. I don't think I'll be able to fix the hardware anytime soon, so have added a 'sleep 5' line to /usr/bin/kodi as a workaround in the meantime, which has fixed this issue for me (apart from now seeing an ubuntu desktop at boot for a few seconds which doesn't look great aesthetically :)). Agree that some form of graceful failure on the addons part would be beneficial for others that see this issue.

**Comment by oddstr13** [comment]
@bradgy I went looking in the source a little, and it looks like we have a builtin startup delay.
You can try if setting `Addon Settings -> Advanced -> Startup Delay` helps.
![image](https://user-images.githubusercontent.com/638706/89125095-4abcc400-d4dc-11ea-84e8-ddbc4dea69b3.png)

**Comment by bradgy** [comment]
Thank you @oddstr13, works perfectly and this is more appropriate for my needs as it means I can go straight into Kodi and the wait time can be spent staring at a nice skin, rather than an Ubuntu desktop on a 4K TV :)

Appreciate you looking into this, I feel bad that I didn't find this myself and you had to dig it up!
