### ISSUE TITLE
Failed to receive latest content updates

### ISSUE THREAD

**Issue by yoasif** [jellyfin/jellyfin-kodi#357]
I have been seeing this prompt when opening Kodi the last few times I have opened it. Clearing Jellyfin for Kodi out seemed to fix it at least the first time, but has since reappeared.

**To Reproduce**

1.Start Kodi

**Expected behavior**

No error. 

**Logs**

https://paste.kodi.tv/tevozadusa

**Screenshots**

![signal-2020-08-10-044209](https://user-images.githubusercontent.com/152493/89765433-51db6780-dac4-11ea-9c9f-cd6160dff812.jpeg)

**System (please complete the following information):**
 - OS: Android 
 - Jellyfin Version: 10.6.1
 - Kodi Version: 18.7
 - Addon Version: 0.5.8
 - Playback Mode: Native

**Comment by TrueTechy** [comment]
Looks like the addon can't connect to the server plugin. Could you check that it's installed, there's been reports of it being uninstalled when upgrading to 10.6

**Comment by yoasif** [comment]
@TrueTechy looks like the server plugin wasn't installed (likely due to the 10.6 upgrade).

It seems to be working now.
