### ISSUE TITLE
Plugin crashing since jellyfin update to 10.6

### ISSUE THREAD

**Issue by Legogris** [jellyfin/jellyfin-kodi#365]
**Describe the bug**
Can not do initial sync of libraries after upgrade from 10.5.5 to 10.6.3.
Tried full reset of kodi db and reinstall of plugin. The error log below occurs when attempting to add library (doesn't matter which)

https://gist.github.com/Legogris/078926299c19cd032d9d596f125c2dc5

**Comment by Legogris** [comment]
Seems like the plugin crashes when trying to interpret empty result from MPAA ratings
https://github.com/jellyfin/jellyfin-kodi/blob/8b1b648dfabcd6a1ffe4245a1592dc123a03f1d7/jellyfin_kodi/helper/api.py#L186

**Comment by oddstr13** [comment]
Is this against 10.6.3 stable, or are you running unstable?

I've seen a bunch of issues related to the APIs now returning keys that have `None` values, and this looks like one of them.
I don't know what Jellyfin PR(s) changed that behavior.

**Comment by Legogris** [comment]
10.6.3 stable (though I tried unstable from the other day as well with same result). Adding an error handler to this makes it yield a similar error in another place on another value so yes, that sounds like it. Haven't had time to follow through yet.

**Comment by Legogris** [comment]
@mcarlton00 Thanks, and with the new 0.5.9 release syncing completes successfully now :)
