### ISSUE TITLE
When installing from repository on Kodi: Failure to Connect

### ISSUE THREAD

**Issue by jrdfrncs** [jellyfin/jellyfin-kodi#369]
When trying to install the add-on on Kodi, it fails to connect to the repository.

The repository can be normally installed from zip, no problems there. But then when going to install the actual add-on, it simply fails to connect.

**Comment by mcarlton00** [comment]
I've just tested on a clean install of Kodi 18.7 and it worked fine.

What Kodi version are you on?  Are there any errors in the logs?

**Comment by jrdfrncs** [comment]
Here:

`16:30:33.702 T:140392036910848   ERROR: GetDirectory - Error getting
16:30:39.365 T:140392775665408   ERROR: Previous line repeats 2 times.
16:30:39.365 T:140392775665408   ERROR: CCurlFile::Open failed with code 404 for https://repo.jellyfin.org/releases/client/kodi/addons.xml.md5
16:30:39.366 T:140392775665408   ERROR: Open - failed to open source <https://repo.jellyfin.org/releases/client/kodi/addons.xml.md5>
16:30:39.366 T:140392775665408   ERROR: CRepository: failed read 'https://repo.jellyfin.org/releases/client/kodi/addons.xml.md5'
16:30:43.542 T:140393589497280   ERROR: GetDirectory - Error getting addons://repository.jellyfin.kodi/
16:30:43.542 T:140393589497280   ERROR: CGUIMediaWindow::GetDirectory(addons://repository.jellyfin.kodi/) failed
16:30:53.098 T:140392028518144   ERROR: CCurlFile::Open failed with code 404 for https://repo.jellyfin.org/releases/client/kodi/addons.xml.md5
16:30:53.098 T:140392028518144   ERROR: Open - failed to open source <https://repo.jellyfin.org/releases/client/kodi/addons.xml.md5>
16:30:53.098 T:140392028518144   ERROR: CRepository: failed read 'https://repo.jellyfin.org/releases/client/kodi/addons.xml.md5'
`

**Comment by mcarlton00** [comment]
Kodi 17 is pretty ancient at this point, and none of us on the dev team have a device old enough to run it.  It should be working, but perhaps the user agent isn't matching correctly on our repo.  In theory everything in the addon should work properly, but we're just not able to test effectively.

Just curious, is there a particular reason you haven't updated to Kodi 18?

**Comment by jrdfrncs** [comment]
It works now!

I just updated to Kodi 18. There was no particular reason to be stuck to an old version, beyond my lazyness, and that my repos still carried 17. Added new repo, installed 18. All works. Thanks!
