### ISSUE TITLE
Native kodi not syncing 

### ISSUE THREAD

**Issue by riddertommie** [jellyfin/jellyfin-kodi#376]
I  have multiple kodi instance, and if i manually change the status to watched on one Kodi the status is not synced to the other. 

**To Reproduce**

1. Go to 'series' and select a episode that in not yet watched
2. Open/select native kodi menu (i think the standard for that is to press 'c' on you keyboard) and select 'changed to watched'

if you now go to any other Kodi the status of that episode in not synced, and wil not get synced ever.

**Expected behavior**
Sync the status if change manually via the native Kodi menu

**System (please complete the following information):**
 - OS: kodi, multiple android, androidtv and libreelec (pi3)
 - Jellyfin Version: latest docker via linuxserver.io
 - Kodi Version: latest
 - Addon Version: latest
 - Playback Mode: Add-On

**Additional context**
Just to be sure if you watched the serie via the 'normal' way the status get synced, no problem with that.
It's  not only series but also Movies

**Comment by mcarlton00** [comment]
I can't replicate this.  Tested both directions between two Kodi 18.7 boxes.  Mark something as watched, walk to the other room, after a few seconds it gets updated.  Mark it as unwatched again on box 2 and after a few seconds box 1 updates.

The only thing I can think of right now is if you don't have websockets working properly, then it might not pick up changes in real time like that.  When you change the watched status, does it get updated on the server appropriately?

**Comment by riddertommie** [comment]
I did some testing and i cant see that i get synced on the server. and that's weird because if i watched a serie its get synced between the clients, but i does not show synced on the server.

just to be sure, I can see that from the check marks (thick) symbol with each serie? or is there another way that you are referring to?

**Comment by mcarlton00** [comment]
Correct, I'm just going off the checkmarks on the series name.  You may need to refresh the web client before changes show up, but I'm not seeing any weirdness on my end about syncing watched status

**Comment by mcarlton00** [comment]
Been doing more testing and I still can't replicate this.  Closing for now, but if we can get reliable steps to reproduce we can reopen
