### ISSUE TITLE
Login window pops up from time to time

### ISSUE THREAD

**Issue by bipox** [jellyfin/jellyfin-kodi#388]
**Describe the bug**
The login window pops up from time to time. Maybe every hour or so, and never during playback.
I can either click on my username (Jellyfin, admin, no password), or wait a few seconds and it goes away.

**To Reproduce**
I updated LibreELEC recently and started using it again after a few months hiatus. I reinstalled the jellyfin-kodi addon, re-added the libraries. Server and user got detected automatically, it was just a matter of clicking OK.

**System:**
 - OS: Jellyfin on Ubuntu 18.04 server (LAN), LibreELEC 9.2.4 on Raspberry Pi 3 Model B+
 - Jellyfin Version: latest available for ubuntu
 - Kodi Version: 18.8
 - Addon Version: 0.5.9+py2
 - Playback Mode: Add-On
 - default kodi skin

**Comment by mcarlton00** [comment]
I've never seen this behavior before.  We need logs if there's any hope of finding what's triggering this.

**Comment by oddstr13** [comment]
Closing due to no logs.

*May* be cause of unreliable connection to the server?

Comment with logs and reopen if this issue is still relevant for you.

https://kodi.wiki/view/Log_file/Easy
