### ISSUE TITLE
Kodi: tv shows and movies disappear 

### ISSUE THREAD

**Issue by masca90021** [jellyfin/jellyfin-kodi#407]
Hi guys,
 I am using the latest stable kodi and latest stable jellyfin add-on. The issue is that I play a tv show and after the show ends, the kodi library has 0 shows in it. I have to manually sync libraries from the addon. Sometimes I have to restart kodi. Win 10. This issue started recently, like a week ago.

Le: I sometimes need to use the option " perform local database reset" for my shows to be there again. Haven't installed any new software or made any modifications to my setup.

**Comment by mcarlton00** [comment]
What other addons do you have installed?  We've had reports that the Netflix addon regularly runs "Clean library", which will erase our media.

Ref: https://github.com/jellyfin/jellyfin-kodi/issues/375

**Comment by masca90021** [comment]
I have both the Netflix addon and HGo EU addon. Is there a workaround or I should just uninstall Netflix ? Thanks for the reply.

**Comment by mcarlton00** [comment]
As far as I know, the only solution right now is to uninstall the netflix addon.  To my knowledge they don't modify the database anyway, so I'm not sure why they would be triggering the clean like that. I've never used it so I can't say for sure.  But there's nothing that can be done on our side to prevent it, unfortunately.
