### ISSUE TITLE
[Kodi 19] No way of putting server ip and credentials

### ISSUE THREAD

**Issue by mrbiz41** [jellyfin/jellyfin-kodi#422]
**Describe the bug**
Hello, I've installed Kodi 19 alpha 3 on my AppleTV, but after installing Jellyfin 0.6.3+py3 for Kodi, I can't get the "welcome window" where I can put my Jellyfin server IP and username/password. Manual options are greyed out, and resetting the local kodi database doesn't do anything

**To Reproduce**
1. Install Jellyfin for Kodi 0.6.3+py3
2. See that no window appears

**Expected behavior**
A window should appear after install, asking me to put my JF server ip and credentials

**Logs**
None available

**Screenshots**
None available

**System (please complete the following information):**
 - OS: tvOS 14.2
 - Jellyfin Version: 10.6.4
 - Kodi Version: 19 alpha 3
 - Addon Version: 0.6.3+py3
 - Playback Mode: N/A

Thanks for your help

**Comment by mcarlton00** [comment]
Sounds like the wizard is encountering an error.  I suspect this might be the same root cause as #421, but one of us will have to get our Kodi 19 dev installs updated to investigate first.  Mine was last updated in August, so it's been a little while.

**Comment by mrbiz41** [comment]
Thanks for your answer ! Is there any file I can edit in order to put the values myself and force the addon to work or do I have to do it through the wizard ?
Thanks again

**Comment by oddstr13** [comment]
Could you please provide logs? https://kodi.wiki/view/Log_file/Easy
This is unlikely to be #421 unless you're running windows 10.

**Comment by mrbiz41** [comment]
Here you go:
https://paste.kodi.tv/asobapukab.kodi
Thank you

**Comment by oddstr13** [comment]
The relevant section of the log is the following;
```python
2020-11-14 22:14:34.555 T:570494    INFO <general>: JELLYFIN.__main__ -> ERROR::service.py:54 [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/96A92E84-42E0-48C7-8754-E6555308B28F/Library/Caches/Kodi/userdata/library/video/movies/index.xml'
                                                   Traceback (most recent call last):
                                                     File "service.py", line 47, in run
                                                       service = Service()
                                                     File "jellyfin_kodi/entrypoint/service.py", line 70, in __init__
                                                       verify_kodi_defaults()
                                                     File "jellyfin_kodi/views.py", line 150, in verify_kodi_defaults
                                                       tree = etree.parse(file_name)
                                                     File "/private/var/containers/Bundle/Application/287D8C1B-C03D-45A8-9E71-0E9946521CDF/Kodi.app/Frameworks/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
                                                       tree.parse(source, parser)
                                                     File "/private/var/containers/Bundle/Application/287D8C1B-C03D-45A8-9E71-0E9946521CDF/Kodi.app/Frameworks/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
                                                       source = open(source, "rb")
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/96A92E84-42E0-48C7-8754-E6555308B28F/Library/Caches/Kodi/userdata/library/video/movies/index.xml'
```

Looks like it may be due to the file not existing in `special://xbmc/system/library/video`, and thus not getting copied over here;
https://github.com/jellyfin/jellyfin-kodi/blob/b9b420358fbfdfc8cd04db4fe356b1b154c3419d/jellyfin_kodi/views.py#L106-L161

**Comment by mrbiz41** [comment]
Thanks for your answer. Is that a problem specific to my setup, or more a problem of  either Kodi or the Jellyfin add-on ?

**Comment by mcarlton00** [comment]
It's either in the Jellyfin addon or something specific to the tvOS implementation on Kodi that's not matching their docs.  It's trying to copy the files from the system folders to the local library, but failing to find them.  The odd part is that where the documentation says the source is and where it's trying to copy those files on your system are different.

https://kodi.wiki/view/Special_protocol

Here it has listed that "Apple TV 2 (black)" is storing these system files in 

`special://xbmc - /private/var/stash/Applications/Kodi.frappliance/KodiData/KodiHome`,

while the logs seem to indicate it's trying to copy content from

`/private/var/mobile/Containers/Data/Application/96A92E84-42E0-48C7-8754-E6555308B28F/Library/Caches/Kodi/userdata/library/video`

I'm curious if this function is needed at all.  I feel like that's something Kodi proper should be doing itself.
