### ISSUE TITLE
"Force Transcode" limits available of subtitle streams

### ISSUE THREAD

**Issue by duckinator** [jellyfin/jellyfin-kodi#435]
**Describe the bug**

If "Force Transcode" is enabled and the prompt to choose subtitles is enabled, when a file is selected to be played it first shows the "Choose the audio stream" screen. After choosing an audio stream, it shows the "Choose the subtitles stream" screen.

The "Choose the subtitles stream" screen is not presenting all of the options. On the video I'm having problems with, there are multiple options for each language, but only one is shown. Unfortunately, the one it shows is for the "behind the scenes" audio track, not the one I want to listen to.

**To Reproduce**

1. Enable the option to choose audio track/subtitles stream. (I forget where this setting is, sorry.)
2. Enable 'Force Transcoding'
3. Play a video with multiple distinct subtitle streams for a single language.
4. See that only one stream for each language is available.

**Expected behavior**

I'd expect to be able to select all of the available subtitle streams for a given language.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: LibreELEC 9.2.6 (RPi4.arm)
 - Jellyfin Version: 10.6.4
 - Kodi Version: 18.9.0
 - Addon Version: 0.6.5+py2
 - Playback Mode: Add-On

**Additional context**

Jellyfin server and LibreELEC/Kodi client are on the same network. LibreELEC/Kodi is running on a Raspberry Pi 4.

The "Force Transcode" option was enabled due to an issue that appears to be the same as (or closely related to) #321.

**Comment by Electry** [comment]
Are we talking about internal or external subs? Also, do you have "Allow subtitle extraction on the fly" enabled in the server dashboard?

I use transcoding almost exclusively and haven't noticed any subs to be missing.

**Comment by duckinator** [comment]
- What do you mean by "internal or external subs"?
- "Allow subtitle extraction on the fly" is enabled.
- It specifically only occurs on things that have multiple subtitles for the same language. E.g., one has English subtitles + English subtitles with commentary.

**Comment by mcarlton00** [comment]
> Internal vs External

Internal subs are subtitles that are embedded inside of the video file.

External subs are subtitles that are in a separate file - `My Super Awesome Movie.eng.srt` for example

I would guess that it's only showing one or the other, or possibly it's just seeing 2 subtitle tracks of the same language and only displaying one.

**Comment by venomousZealot** [comment]
This is because

1. the available subtitle streams are stored in a dictionary

> /jellyfin_kodi/helper/playutils.py line 586:

`subs_streams = collections.OrderedDict()`


2. the keys are generated based on language (and codec):

> /jellyfin_kodi/helper/playutils.py line 622:

`track = "%s - %s" % (stream['Language'].capitalize(), codec)`


3. If that is identical (e.g. for regular audio and commentary), previous ones get overwritten:

> /jellyfin_kodi/helper/playutils.py line 631:

`subs_streams[track] = index`

which is bad.


A possible solution would be to add a unique number to the names.

**Comment by venomousZealot** [comment]
Same problem could happen with audio tracks, btw, but here the number of channels are also added to the dictionary key.
Since commentaries are usually just stereo, the problem is less likely to appear.
