### ISSUE TITLE
Can’t install Kodi Sync Queue 6 (latest)

### ISSUE THREAD

**Issue by kauniss** [jellyfin/jellyfin-kodi#449]
OS: macOS Catalina 10.15.7
Jellyfin 10.6.4 (Darwin, x64), latest stable Installer/dmg release
Installed where: local (iMac main SSD drive)
Shared folder location: local (iMac main SSD drive)
How I installed Jellyfin: installed dmg from https://repo.jellyfin.org/releases/server/macos/stable/
What I’m ultimately trying to do: Get Jellyfin4Kodi running properly using native mode.

As the title suggests, I cannot install Kodi Sync Queue 6 (latest release). I can install the previous version, 5, though. This appears to not be good enough, as Kodi cannot never initiate/resume a sync

Is there a way around this: anyone able to sync successfully with KSQ5 using latest macOS installer build of Jellyfin + latest Kodi? 

If not, any advice on how I can get it installed?

**Comment by mcarlton00** [comment]
Version 6 of Kodi Sync Queue is meant for use with the upcoming 10.7 release.  There was a bug in the UI that showed plugin versions that are incompatible with the current release.  No functionality has changed, so if version 5 isn't working for you, version 6 won't have any difference.

When you start Kodi, do you receive a popup saying that the plugin isn't installed?  Check your Kodi logs and verify that it's reaching out to the server to check for updates.  It should have

```
2020-11-30 14:40:09.622 T:3637  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:380 --[ retrieve changes ] 2020-11-30T09:58:28z
2020-11-30 14:40:09.936 T:3637  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:340 --<[ retrieve changes ]
```
if there are no changes, and if there are changes it will log extra information between those two statements.

**Comment by kauniss** [comment]
Thanks for your help!

It was resolved after I reinstalled Jellyfin and configured it once again on Kobi. So, still not sure what it was. But I can say I didn’t get a pop message about it not being properly installed.
