### ISSUE TITLE
Having this issue installing on Steam Link (og hardware version) using these instructions: https://jellyfin.org/docs/general/clients/kodi.html

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin-kodi#461]
Having this issue installing on Steam Link (og hardware version) using these instructions: https://jellyfin.org/docs/general/clients/kodi.html

the Kodi log says:

"Failed to install Add-on from zip file
Installing the Add-on from zip file located at 
https://kodi.jellyfin.org/repository.jellyfin.kodi.zip failed due to an invalid structure."

_Originally posted by @gravyboot in https://github.com/jellyfin/jellyfin-kodi/issues/178#issuecomment-763169694_

**Comment by oddstr13** [comment]
@gravyboot Please provide the full logs, or at the very least the Kodi version and system info part of the log.

**Comment by gravyboot** [comment]
Here you go: https://pastebin.com/hUW6xLn6

**Comment by mcarlton00** [comment]
Ideally, we need logs from when you try to install the repo and it fails.  That looks as though you just started Kodi and turned it back off immediately

**Comment by gravyboot** [comment]
I turned it on, tried to install, then turned it off,  so the log should show a failed install attempt. I thought it was lines 177-182.  

I can turn on debug log mode but it's a much longer file won't all display in putty and I had trouble downloading it from steamlink. Will try again if the above isn't helpful.

**Comment by gravyboot** [comment]
Specifically, I turned it on and followed step 2 under the "Embedded" section of the instructions before turning it off.

**Comment by gravyboot** [comment]
Here's a more detailed debug log, the failed addon install attempt starts around line 730. https://pastebin.com/iYr2NmrR

**Comment by oddstr13** [comment]
I don't see any errors related to installing the Jellyfin addon repo in that log, but I do see SSL errors for what looks like mirrors of the official kodi repos.

I suspect the CA certificate store on your device is out of date, and that is the reason for those errors.

I don't know what the CP437 -> UTF-8 encoding errors are about, as I don't know the strings involved, but that *probably* involves a directory with non-ascii characters in it, possibly a username or similar.

I do not see any attempts to install the actual addon, only the addon repository.
Go to Add-ons, Install from repository, Video add-ons and scroll down until you find Jellyfin, and install that. (Or search for Jellyfin).

**Comment by gravyboot** [comment]
Thanks. I can't find any info on how to update the certificate or anyone else having similar errors with Steam Link, but will keep looking. 

> Go to Add-ons, Install from repository, Video add-ons and scroll down until you find Jellyfin, and install that. (Or search for Jellyfin).

Jellyfin is not present in that list.

**Comment by oddstr13** [comment]
Is the Jellyfin repo listed as installed?

**Comment by gravyboot** [comment]
No, if I go to Add-ons > Video add-ons, there is nothing listed. Likewise if I go to My add-ons > All or My add-ons > Add-on repository, Jellyfin is not listed. 

If I go to settings > install from zip > Jellyfin, I have the following options: 
- plugin.video.jellycon
- plugin.video.jellyfin
- script.module.websocket
- repository.jellyfin.kodi.zip

I've tried to install the 2nd and 4th options but they failed. 

I also noticed that the timezone is wrong in Kodi so looking into how to fix that, in case that's causing issues (?)

**Comment by oddstr13** [comment]
I have not tried to install the repo over http, but it should just work (you can browse the directory it looks like).

If it is just the timezone that is wrong, that shouldn't cause any issues with installing, but if the date is wrong, that could be the root cause of the ssl issues in your logs.

I have no idea of what the iconv errors are about, but it looks like your problems are not be specific to our addon.

**Comment by gravyboot** [comment]
Ok thanks again, I'll try to figure it out.

**Comment by mcarlton00** [comment]
@gravyboot did you ever make any progress here?  I can't think of any reason it would be failing unless a steam link install has very unexpected changes from vanilla kodi.
