### ISSUE TITLE
Unable to install on Kodi 18.7

### ISSUE THREAD

**Issue by michelferia** [jellyfin/jellyfin-kodi#464]
**Describe the bug**
I tried many times to install Jellyfin last version and I have always the same issue
"module.script.idna couldn't be satisfied"
**To Reproduce**

1. Just try to install Jellyfin add-on on a fresh 18.7 version of Kodi installed in a fresh Raspberry Pi SO Lite. Using main repositories...

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Raspberry Pi SO Lite 32bits
 - Jellyfin Version:  0.7.0
 - Kodi Version: 18.7
 - Addon Version: 0.7
 - Playback Mode: Add-On

**Additional context**

**Comment by Normonator** [comment]
I think it's an upstream issue. You can install it manually and it works for now.
[https://mirrors.kodi.tv/addons/krypton/script.module.idna/script.module.idna-2.8.zip](https://mirrors.kodi.tv/addons/krypton/script.module.idna/script.module.idna-2.8.zip)

**Comment by michelferia** [comment]
Thanks very much, yes it work !!
