### ISSUE TITLE
kodi matrix jellyfin not syncing music

### ISSUE THREAD

**Issue by popeye2468** [jellyfin/jellyfin-kodi#468]
All libraries sync and it even looks like music has too but no songs sync at all

on a fresh install
installed latest jellyfin repo

**Comment by mcarlton00** [comment]
Music syncing should be fixed in version 0.7.0.  We need logs to see what your error is.

https://kodi.wiki/view/Log_file/Easy

**Comment by popeye2468** [comment]
dont worry i wasnt using the latest dev version of kodi i wa using RC1 which it doesnt show the music

**Comment by popeye2468** [comment]
scrap that, as soon as the music syncs all the songs dissapear

https://pastebin.com/0LSJcsMW

**Comment by mcarlton00** [comment]
Please upload clean logs.  There looks to be a lot more than a sync happening.  I see metadata updates and various browse/playback events, as well as multiple scan events from Kodi itself.  If I had to guess right now, those scans are wiping our your library.  I can't replicate this error, it's all working as expected for me.

**Comment by popeye2468** [comment]
https://pastebin.com/W6f0DXR0

**Comment by mcarlton00** [comment]
The sync completed at line 990, and I don't see any reports of any errors there.  There's no log messages about any errors or messages about removing content from the database.  And I still can't replicate this using v0.7.0 of the addon with Kodi compiled from master today.

My full steps:
1. Addons -> Jellyfin -> Reset database, reset everything when asked
2. Restart Kodi
3. Enter server URL
4. Enter user/password
5. Add-on mode
6. Select Music library
7. Sync

Everything is working as expected here.

**Comment by oddstr13** [comment]
Is `Music` a library group here?
User icon -> Home
![image](https://user-images.githubusercontent.com/638706/110545949-212ce080-812e-11eb-996b-a382d6821a30.png)
In my case, `Anime` and `Series` would be grouped in `TV Series`.
Individually they will sync, but the `TV Series` entry will not.

**Comment by sparklyballs** [comment]
I am seeing this issue following a specific set of circumstances, also running kodi matrix 
If i add my music and tv shows in separate imports and then try to add library for music , the sync runs for 1 second and nothing is imported

**Comment by mcarlton00** [comment]
We've been able to replicate that but haven't had a chance to debug it yet.  It seems as though the initial sync works correctly, but trying to sync subsequent libraries is basically just doing nothing.

**Comment by Hetoft** [comment]
@popeye2468  Did you manage to get it fixed? I'm having the same issue and just created a new ticket (before seeing this one however). It says here that it is closed though, so I'm wondering if you or the devs came up with a solution? Thanks.
