### ISSUE TITLE
Tries to Sync Music Videos and fails

### ISSUE THREAD

**Issue by s1mpleman** [jellyfin/jellyfin-kodi#47]
Hi, just got the latest update installed and got to say great work! 

It however currently tries to sync Music Videos when selecting all instead of leaving that as a dynamic library. 

Work around: Manually select each library except for Music Videos.

**Comment by mcarlton00** [comment]
I was able to sync and play music videos while testing today, so I'm going to close this one.  If you see any other issues with it feel free to open the issue back up with more details.
