### ISSUE TITLE
Python error in library.py, local libraries not being populated

### ISSUE THREAD

**Issue by jlbaker75** [jellyfin/jellyfin-kodi#470]
**Describe the bug**
After adding jellyfin server & authenticating, local sqlite databases are not being populated from jellyfin.

**To Reproduce**
1. Add jellyfin server
2. Authenticate to server
3. Select libraries to add
4. Local libraries are not updated; "dynamic" libraries are available in jellyfin-kodi addon

**Expected behavior**
The local sqlite tv & movie databases should have been populated, or at least have begun to be populated.

**Logs**
Error section from log; full log attached.
```
2021-02-14 03:15:59.646 T:1455395040  NOTICE: JELLYFIN.library -> ERROR::jellyfin_kodi/library.py:319 [Errno 21] Is a directory: u'/home/osmc/.kodi/userdata/'
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/library.py", line 315, in startup
                                                sync.libraries()
                                              File "jellyfin_kodi/full_sync.py", line 100, in libraries
                                                if not xmls.advanced_settings() and self.sync['Libraries']:
                                              File "jellyfin_kodi/helper/xmls.py", line 130, in advanced_settings
                                                tree.write(path)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 802, in write
                                                file = open(file_or_filename, "wb")
                                            IOError: [Errno 21] Is a directory: u'/home/osmc/.kodi/userdata/'
```

**System (please complete the following information):**
 - OS: Linux 4.19.122-2-osmc armv7l GNU/Linux
 - Jellyfin Version: 10.6.4
 - Kodi Version: 18.9
 - Addon Version: 0.7.0+py2
 - Playback Mode: Add-On

**Additional context**
There is a python error thrown when the addon tries to manipulate a file in the userdata folder; see log excerpt above.

[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/5977207/kodi.log)

**Comment by jlbaker75** [comment]
Removing `<cleanonupdate>true</cleanonupdate>` from the `<videolibrary>` section of my userdata/advancedsettings.xml fixed the problem.

The issue wasn't the libraries not syncing, but the addon breaking before it got to the point of syncing.

Seems the issue is in the cleanonupdate xml manipulation in jellyfin_kodi/helper/xmls.py

**Comment by mcarlton00** [comment]
Looking at the function in question:

https://github.com/jellyfin/jellyfin-kodi/blob/ce111cfb61a1443d5151959ba18d4ffae5768cd0/jellyfin_kodi/helper/xmls.py#L103-L135

It seems like it should be `tree.write(file)` instead of `tree.write(path)` at line 130.

In case you're not aware, we're fully incompatible with the clean library function built into Kodi.  I've spent a lot of time trying to find ways around this (#409), but there's just no method that's very feasible at this point

**Comment by jlbaker75** [comment]
Definitely aware of the problems that can/will arise from kodi "cleaning" a library populated from jellyfin.

Using `cleanonupdate` was, in my case, a holdover of switching from a shared backend (mysql + nfs) for my libraries; now that my kodi clients are syncing media additions and deletions from jellyfin, the setting (and attendant functionality) are obsolete, so removing it was zero heartburn.
