### ISSUE TITLE
play on sends music and tvshow playlist shuffled

### ISSUE THREAD

**Issue by bwaddington** [jellyfin/jellyfin-kodi#49]
**Describe the bug**
scince 10.3 when trying play on it sends music and tvshow playlist shuffled to kodi but if you play on web browser thier all in order. same with collections click to play the collection and it shuffles the playlist to kodi.
when ever i select a music track it palys a diffrent track in that album also if you click play it dosnt play from the start of the album and this is with both kodi and browser

im using firefox 66.0.5 (64-bit), Kodi version 18.2 with angelblue05 10.1.0

**Comment by bwaddington** [comment]
is there any chance of this being fix at some point

**Comment by oddstr13** [comment]
It'll get fixed whenever someone with the time and skills required come along. I don't have much time for Jellyfin right now unfortunately.

**Comment by mcarlton00** [comment]
Just as an update, I spent some time looking into this.  Currently, it looks like we're blocked by the data we're receiving from the server itself.

The short version is that the server is sending out a list of item IDs that need to be played, but it's not providing any data on what order they should be played in.  Once we work out a way around that we'll have a way forward with this

**Comment by bwaddington** [comment]
this could do with sorting i has been a while plus it has now stopped seeing thew firestick app too. 

whats point of it if it does not work

**Comment by mcarlton00** [comment]
The fix for this needs to happen on the server.  Currently there's no way for us to handle this locally.  If you look at the linked issue in the server repo you'll see that it's being discussed.

There's zero interaction between Kodi and the Android TV app.  If you're having an issue with that, you should discuss it over [here](https://github.com/jellyfin/jellyfin-androidtv/issues)

**Comment by TrueTechy** [comment]
Seems the latest version of the server should have the fix for this issue implemented. Can we re-check to see if it's still an issue in kodi?

**Comment by mcarlton00** [comment]
This is fixed upstream

**Comment by enomam** [comment]
Sorry for the bump - but I'm observing this behaviour on server 10.6.4, with the kodi client 0.7.1+py2 (running on libreelec).
Is there a config setting I should be applying for this to work?
