### ISSUE TITLE
Kodi addon not respecting internet streaming bitrate limit

### ISSUE THREAD

**Issue by allthesebugsv2** [jellyfin/jellyfin-kodi#498]
**Describe the bug**
When an internet streaming bitrate limit is set it works fine in the web player but is apparently ignored when using a Kodi client.

**To Reproduce**
1. Go to the jellyfin dashboard and set a bit rate limit streaming.
2. Notice that it works in the web player
3. Play the same video via Kodi
4. While it does transcode to Kodi the bit rate is the original leading to constant buffering and finally playback abort

**Expected behavior**
Respect the bit rate limit also for Kodi clients.

**Logs**
Not sure which logs to look for to be honest.

**System (please complete the following information):**
 - OS: LibreElec 9.2.6
 - Jellyfin Version: 10.7.1
 - Kodi Version: 18.9
 - Addon Version: 0.7.1
 - Playback Mode: Add-On

**Comment by mcarlton00** [comment]
Does this happen on LAN, or across the internet as well?  There's different bitrate restrictions for each of those iirc.  I believe the internet streaming bitrate limit only applies when the client is outside your local network.

**Comment by allthesebugsv2** [comment]
This all tested via Internet as the Kodi (and also the web client) are not physically in the same place. Both the web client and the Kodi client connect therefore with the same internet ip but the bitrate limit is only respected for the former.

**Comment by mcarlton00** [comment]
This sounds more like a server bug, honestly.  A client shouldn't even have the option to override the server.  We have a bitrate selector in the settings that controls what we request from the server, but the server should always have the final say in what is and isn't allowed.  Talking with some of the team, it sounds like the per user streaming limits works as expected and is the most common method to do this instead of a global setting.

**Comment by allthesebugsv2** [comment]
After further testing (and discovering that the Kodi addon has its own bitrate limit setting) these are my results while streaming via the internet:

- Global bitrate limit: no effect for Kodi (but affects web players and the desktop client)
- User bitrate limit: same as above
- Kodi addon bitrate limit: works fine

It seems that after all the Kodi addon has the final say. I am happy that it works now but I do think it would make sense to not have Kodi clients overriding server settings (though I guess there is some technical reason why it is setup like this).
