### ISSUE TITLE
Syncing Music Videos fails

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin-kodi#501]
**Describe the bug**
Almost a duplicate of https://github.com/jellyfin/jellyfin-kodi/issues/47, so this issue starts there.

Hi @mcarlton00 I have the same issue on Kodi 19. And it have been a issue since kodi 18.7 on both android and Nvidia Shield, until the release of jellyfin 10.7.2 this have been related to a few specific MV's (music Video), if I removed those from the folders the sync could succeed.

A few days ago I went converting some of the *.webm files into mp4 (as webm files could not be played in kodi + jellyfin), when the sync completely failed.

I then tried to repair the MV folder, remove it, add it back. Now I have no MV's on kodi+jellyfin. However going to the video -> NFS-shared folder and browsing, everything is fine. 
Even that I've setup the MV folder in jellfyn for kodi, it says `Please setup a music video source`

I would be pleased to had added some logs, but haven't spent enough time with the Shield to figure out how to extract the logs without opening a lot of google shit.

**To Reproduce**
Change the contents of your MV folders

**Expected behavior**
Just synced up, if any records should be troubled, report it rather than breaking it all.

**Logs**
Would love to, but still something to learn about the device

**System (please complete the following information):**
 - OS: Android (Tablet + Nvidia Shields)
 - Jellyfin Version: 10.7.2
 - Kodi Version: 19 Matrix
 - Addon Version: 0.7.1+py3 (Updated 9th of April 2021)
 - Playback Mode: Sync issue

**Additional context**
Not currently :smiley:

**Comment by mcarlton00** [comment]
Kodi has a log uploader that you can use to easily retrieve logs from devices like that.  See https://kodi.wiki/view/Log_file/Easy

**Comment by spirillen** [comment]
HI @mcarlton00 thanks for your feedback

I did find the `component-specific logging` and was looking in the lists, but did not find anything that seems directly related to jellyfin-kodi, maybe you could help me with which exactly I should choose among the list, I'm guessing that `JSON-RPC` + `Database` is among the related

**Comment by mcarlton00** [comment]
We need the output from the addon, and I don't think there's a component that limits it to addons.  We'll likely need the full thing.

That said, reading the initial post again I believe this is a duplicate of #468 and should be fixed in #494, just waiting fore review/approval before it's merged.

**Comment by spirillen** [comment]
Thanks for your reply, I'll put this on hold to https://github.com/jellyfin/jellyfin-kodi/pull/494 is merged and distributed.

The diff is that this only occurs on the MV's, never seen the issues on the music folder.

:pause_button:

**Comment by mcarlton00** [comment]
It's not just music.  It was any library.  Once the initial sync was completed, trying to sync any subsequent library wasn't working properly.  When you run the "Repair", it removes the library from the local database and syncs it again from a clean slate, so I suspect you hit the same bug.

**Comment by mcarlton00** [comment]
0.7.2 has been released.  Can you verify if this is still a problem?

**Comment by spirillen** [comment]
Well I have actually uninstalled the plugin as it keeps failing, and I'm completely unable to update the any libraries.

Have tried to uninstall everything, even kodi and start over, now I can't even sync the tv-shows under any condision:
  - not altered at all
  - Add one new episode
  - Removed episodes

It seems as the sources are getting to big (To many episodes in same serie), it crashes completely.

For the log, we will have to wait for me to get a internet connection. (Running on the phone connection)

**Comment by spirillen** [comment]
On my Nvidia Shield, the latest release now breaks on the artist sync.

**Comment by spirillen** [comment]
Hey there

Now I got some :zap: fast internet :hot_face: and reinstalled the plugin on the Nvidia Shield, It did what it is supposed to :clap:  Even faster than I have been trying earlier.

It makes me think, Does the plugin trying to connect to any external (WAN side) domains while it is syncing? 

If so it could explain why it get stalled while it is running on a in_TRA_net vs in_TER_net and I would consider that a problem as my media devices is supposed to be running solely on the intranet, with no access to any external resources (Android OS aka Google spyware) once I'm done with my firewall.

**Comment by mcarlton00** [comment]
We don't have any outgoing connections, so whatever you're experiencing is being caused by something else.  The only thing the addon connects to is your Jellyfin server

**Comment by spirillen** [comment]
> We don't have any outgoing connections, so whatever you're experiencing is being caused by something else. The only thing the addon connects to is your Jellyfin server

Super.
It also makes me think I should retest this plugin when the network have been split as mentioned earlier. And then have a peek on the outgoing connections (Thinking jellyfin might be doing some lookup, hence stalls the delivery of data), as there obviously was a HUGE performance diff with vs without internet connection.

I also reinstall the plugin on the tabled, and so far it seems to be working fine.

Non the less, this particular issue should be considered fixed. And therefor not giving much sense to try to obtain a error log.

Closing.

PS: If the problem arise again, I'll just reopen this issue with a log file. Thanks for the help @mcarlton00
