### ISSUE TITLE
Last couple of releases not being documented on GitHub

### ISSUE THREAD

**Issue by jfranki** [jellyfin/jellyfin-kodi#519]
**Describe the bug**
In the "Relesase" section of this repository last one is 0.7.1 and is marked as _Latest_, when 0.7.2 and 0.7.3 have both been released. The tags are there but there isn't any changelog linked to them either.

**Expected behavior**
The pipeline/actions should populate the release associated with the tag and print the changelog.

**Screenshots**
![image](https://user-images.githubusercontent.com/6547157/117625318-30ec9380-b176-11eb-849b-f73defafb132.png)

**Comment by TrueTechy** [comment]
I've published the last two versions manually as releases in the meantime and we're looking to automate the release creation as part of our build deployment process

**Comment by mcarlton00** [comment]
This is now handled automagically thanks to #523 and it's follow up PRs
