### ISSUE TITLE
Support basic auth

### ISSUE THREAD

**Issue by StableNarwhal** [jellyfin/jellyfin-kodi#52]
I am using a Jellyfin instance behind a nginx reverse proxy with basic auth.
The jellyfin-kodi addon doesn't support basic auth, which would be a great addition.

The obvious workaround would be to disable basic auth for Jellyfin, but I'd rather not advertise my server publicly. 

Just to clarify: I'm not talking about piping the username/password entered by basic auth as login credentials to Jellyfin, just to support connections protected by basic auth.

Cheers!

**Comment by oddstr13** [comment]
Can you try the https://username:password@host:port/path url format when connecting? It might just work.

On August 2, 2019 3:19:28 PM UTC, StableNarwhal <notifications@github.com> wrote:
>I am using a Jellyfin instance behind a nginx reverse proxy with basic
>auth.
>The jellyfin-kodi addon doesn't support basic auth, which would be a
>great addition.
>
>The obvious workaround would be to disable basic auth for Jellyfin, but
>I'd rather not advertise my server publicly. 
>
>Just to clarify: I'm not talking about piping the username/password
>entered by basic auth as login credentials to Jellyfin, just to support
>connections protected by basic auth.
>
>Cheers!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin-kodi/issues/52

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by StableNarwhal** [comment]
> Can you try the https://username:password@host:port/path url format when connecting? It might just work.
> […](#)
> On August 2, 2019 3:19:28 PM UTC, StableNarwhal ***@***.***> wrote: I am using a Jellyfin instance behind a nginx reverse proxy with basic auth. The jellyfin-kodi addon doesn't support basic auth, which would be a great addition. The obvious workaround would be to disable basic auth for Jellyfin, but I'd rather not advertise my server publicly. Just to clarify: I'm not talking about piping the username/password entered by basic auth as login credentials to Jellyfin, just to support connections protected by basic auth. Cheers! -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #52
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

Tried that already, unfortunately it doesn't work neither in username:password nor username:password_urlencoded form. Thanks though!

**Comment by TrueTechy** [comment]
The issue with getting this to work lies with the Authorization header being used for client identification by the server, so putting the proper auth header in allows for the connection to the server but testing shows that it doesn't let you sign in, presumably this is because the server is expecting the identification string in the Authorization header and refused to let a user log in without it. A server side change will be required before basic auth could be supported. 

The function that sets this authentication header can be found at https://github.com/jellyfin/jellyfin-kodi/blob/master/resources/lib/jellyfin/core/http.py#L217
