### ISSUE TITLE
Jellyfin for kodi not connecting the server

### ISSUE THREAD

**Issue by Cissoubaka** [jellyfin/jellyfin-kodi#526]
**Describe the bug**
Jellyfin throw an error at launch, and the connection is not working, the only way to correct this, is to desintall jellyfin for kodi without deleting plugin data (same behavior with or without deleting plugin data), then reinstalling the plugin. And the bug is present the next launch of libreelec.

**Logs**
[KODI.log](https://0bin.net/paste/oUZ073II#yrS0KZmq7iZPsHilCC-e9W2uwYuHdToObIyq8y0FHnd)

**System :**
 - OS: libreelec 9.2.6 Raspberry Pi4 4Go
 - Jellyfin Version: 10.7.5
 - Kodi Version: 18.9
 - Addon Version: 0.7.2 py2 and 0.7.3py2  (the 0.7.3 is not present in the list of the repository)
 - Playback Mode: addon mode

**Comment by mcarlton00** [comment]
I don't know how you've managed to do this, but you're missing a dependency.  You need to install the websockets library from our addon repo.  It should have automatically installed with 0.7.3 (and just did on my test install).

https://kodi.jellyfin.org/py2/script.module.websocket/script.module.websocket-0.57.0.zip

I'm also not sure what you mean by 0.7.3 not being available in the repo.

![2021-05-16-142052_1221x750_scrot](https://user-images.githubusercontent.com/17029228/118408112-f9885600-b651-11eb-9827-4da4fae8cd15.png)

**Comment by venomousZealot** [comment]
On my FireTV Stick, I had to manually install ("sideload") the websocket addon.

**Comment by Cissoubaka** [comment]
Ok I just checked, I'm using 2 profiles (master and Kids), on the master profile the websocket addon is installed and everything works, but on the kid profile, the addon is not installed. I'm trying to install it manually

**Comment by Cissoubaka** [comment]
So it works with manual installation of websocket
for the last version not appearing in the depot :
[no 0.7.3](https://imgur.com/a/k24HP3J)

**Comment by venomousZealot** [comment]
I think I had to un- and reinstall the repository-addon to get 0.7.3 to appear on some machines, but I'm not 100% certain.

**Comment by charredchar** [comment]
I wanted to throw in that I had a similar issue but running on a Intel NUC running Windows 10. I could reinstall the plugin (0.7.2 or 0.7.3, didn't matter) and it would work until the next reboot and error again. I installed the websocket and so far so good. I will keep an eye on it though and if it persists I can post logs and whatnot.

**Comment by Mange** [comment]
I have the same issue. Also using multiple profiles in Kodi.

**Comment by mcarlton00** [comment]
I had a chat with the Kodi devs about this.  While it's not a known bug, they're also not surprised.  Profiles seem to be half implemented and generally aren't well supported.  Unfortunately, the only solution I have for you is to make sure that you have the websocket dependency installed on each of your profiles.  There's nothing we can do within the addon to solve this issue short of reverting to the old embedded websocket library, which isn't a reasonable solution for several reasons.
