### ISSUE TITLE
Incorrect TV Show Metadata/File Issue

### ISSUE THREAD

**Issue by jesse-troy** [jellyfin/jellyfin-kodi#53]
I have added my TV and Movie libraries to Kodi using this (pretty awesome) addon, but I am having a problem with a few TV shows, not all of them.

Example of the problem:
I navigate in Kodi to a TV show and go to information for an episode. It shows the correct thumbnail and title for the episode, but shows the plot and actors for a movie in my library. When I play the episode, it actually plays the movie (that the metadata was from). As far as I can tell this issue only effects some of my TV shows (Planet Earth, South Park) and does not appear to affect movies. Some shows will also not show any information at all (which is my "default select" action in Kodi making it very frustrating to play these videos). The metadata in Jellyfin web interface is correct. 

My environment:
Kodi - Windows 10 PC, Latest version of Kodi
Jellyfin - Docker container, Latest version
Addon - Latest version installed from Repo
Kodi Sync Queue plugin is installed

I will attempt to get some screenshots demonstrating this strange occurrance. Any help would be appreciated. It does look to be posibly related to this previously unresolved issue: https://github.com/jellyfin/jellyfin-kodi/issues/24#issue-440057406

**Comment by jesse-troy** [comment]
I can now confirm that, like issue #24, the last synced library seems to overwrite the other library. If I remove the TV library and then re-add it, then movies in Kodi have descriptions of TV episodes. Then if I add my Movies back, TV episodes have descriptions of movies.

And just because it isn't very clear in my last post, when I am on the "information" screen in Kodi and hit play for one of the entries with the wrong information (TV show with a movies description, for example) it will play the item being described and not the item selected. However if I use the context menu to play the item before going to the information screen it will play the correct item.

I have completely removed Kodi and all addons from my system and reinstalled kodi and only this addon and I am getting the same result.

I am happy to post log files, but I do not know what files would be useful for this issue. 

Any help would be greatly appreciated and I would love to be able to make full use of this addon!

**Comment by oddstr13** [comment]
Enable debuging in the plugin settings, then attach the main Kodi log to this issue after reproducing the problem.

**Comment by jesse-troy** [comment]
Thanks for the response! Here is the kodi log as requested. 

[kodi.log.7z.zip](https://github.com/jellyfin/jellyfin-kodi/files/3490210/kodi.log.7z.zip)


had to compress it as it was over 100MB. renamed to zip, but it is a .7z.

Please let me know if there's anything else I can do to help resolve this issue!

**Comment by LittleCannon** [comment]
I can confirm this bug.
Also, in my testing I have found out that if you synchronize only TV Shows library, informations/metadata are OK. Soon as you synchronize Movies library, TV Shows data gets overwritten by Movies metadata, in order that alphabetically first movie metadata replace alphabetically first TV Shows data.
Also, as stated above, if you chose to show information before play in Kodi , TV Shows will not play.

Kindly asking if there is anything else that I can do to help you resolve this problem (sadly I do not know how to code, son no help from me from that side :( )

**Comment by mcarlton00** [comment]
Just an update: TrueTechy and I were able to replicate this, but haven't found the source yet

Also, ^ that commit was a typo.  Sorry folks, don't get too excited yet

**Comment by oddstr13** [comment]
Does "latest version of Kodi" mean v19? Please be specific with full version info. "latest" is a moving target, and not usefull for tracking down issues, and further reference.

**Comment by jesse-troy** [comment]
Latest was v0.2.1 as that was the latest release when I created this issue.

**Comment by EvilAaron** [comment]
I am seeing this as well, crazy wierd.  Some installs are fine others have metadata all jumbled between movies and tv.

**Comment by truenicoco** [comment]
I also experience this with Debian Stable (buster), kodi 5:18.5-dmo0+deb10u1 from debian-multimedia, jellyfin 10.4.3-1 from the official repo, and jellyfin-kodi 0.3.6 from the official repo as well. I would be glad to help debugging this, let me know if I can.

**Comment by mcarlton00** [comment]
If you're able to find where it's happening, I'd love to know.  I've spent several hours digging and haven't been able to track it down yet.  I suspect that a relative link is getting sent to the wrong item in the database, but when I dump the data and compare it nothing is standing out to me yet.  What I'd love is to find the database calls that Kodi's "Show Info" dialog makes, but so far I haven't been able to find any documentation about that.

**Comment by jesse-troy** [comment]
Do we have evidence that there are users with both TV and Movie libraries that are NOT experiencing this?

Could it be possible that one of the components involved is keeping seperate identifier keys for TV shows and Movies? It does appear as if they are misaligned consecutively. TV shows at the top of the list alphabetically seem to be showing information for the first movie alphabetically or vice versa (since the latest import seems to overwrite the previous library).

**Comment by LittleCannon** [comment]
I have same setup on 2 locations (my parents house and my house). 
On both locations there is Debian (Buster) server with installation from repo and Raspberry PI with Libreeelec and Jellyfin Kodi addon. 
On both locations I have same problem (as I described above).

**Comment by eglia** [comment]
On my installation, it mostly works if I use native mode. In addon mode, it's always messed up.

**Comment by truenicoco** [comment]
I posted [something](https://forum.kodi.tv/showthread.php?tid=350024) on the kodi addons forums, maybe someone will have a clue. I can't code properly but I figured this might help.
