### ISSUE TITLE
No Sync if Kodi starts before the Jellyfin server

### ISSUE THREAD

**Issue by allthesebugsv2** [jellyfin/jellyfin-kodi#532]
**Describe the bug**

If Kodi is started before the JF server and JF is then started at some later point, media will play fine but its play progress/status will not sync to the server.

**To Reproduce**

1. Start Kodi with the JF addon
2. Start the JF server
3. Play some media
4. While the media plays fine the status is not synced to the server (the client is not even shown as active)

**Expected behavior**

That the status is synced as soon as the JF server is online

**System (please complete the following information):**
 - OS: CoreELEC
 - Jellyfin Version: 10.7.5
 - Kodi Version: 19.1
 - Addon Version: 0.7.3
 - Playback Mode: Native (but same problem with add-on mode)

**Additional context**

I know that I can restart the Kodi client to "fix" the problem but that does not really fit my use case. It would be sweet if the JF addon could periodically check whether the server is online (maybe even as a configurable setting).

**Comment by mcarlton00** [comment]
Due to the way the network code is handled in the addon, there's really not a feasible way of dealing with this.  Any other client just fails to load at all, the only reason this issue exists is because we're piggybacking off Kodi.  But it likely wouldn't be an easy or straightforward fix, and given the extremely niche situation that this would apply, it's likely not going to get looked into for a good long time.

**Comment by allthesebugsv2** [comment]
Thank you for having a look! I am just poking into the blue here but would it possible to re-establish the connection with the JF server upon starting media play? As I said media plays fine, only it's status is not synced. 

I do get it though if it's not possible due to the Kodi addon nature.

**Comment by mcarlton00** [comment]
I won't say "not possible", but I will say "an unreasonable amount of work".  If the network code is ever reworked, I imagine this will be touched then.  But until then, I'm gonna have to say this isn't going to happen.
