### ISSUE TITLE
Doesn’t work on Xbox

### ISSUE THREAD

**Issue by Meteor24** [jellyfin/jellyfin-kodi#533]
I was trying to install the add-on on my Kodi client on my Xbox but it keeps saying "Failed to install dependency". I was not able to find any YouTube videos on the installation process and had to go completely off of the website and probably made a mistake in the process. Any additional help to rectify the situation is much appreciated.

**Comment by mcarlton00** [comment]
* What Kodi version?
* Which dependency failed to install?
* Are there errors in the logs? (https://kodi.wiki/view/Log_file/Easy)
* How are you trying to install the addon? We have docs covering it [here](https://jellyfin.org/docs/general/clients/kodi.html)

**Comment by Meteor24** [comment]
The Kodi version is 18.9 and I think the dependency was a Python code/program

**Comment by mcarlton00** [comment]
When you're opening an issue in a project, it's typically useful to help us help you, or we're just wasting everybody's time.  You've ignored the issue template that would have answered my questions, and now you've only answered half of them in the most vague way possible.

It's a high likelihood that this is a Kodi issue that will solve itself.  All our dependencies are packaged for Kodi 18 and function properly.  The most likely issue here is that your Kodi install has decided to use a bad upstream addon mirror and wasn't able to retrieve a package, thus failing.  The only option you have is to install dependencies manually (which is likely to be all but impossible on an xbox), or to be patient and try again later when the DNS cache has expired and you can hopefully get a different addon mirror.  Either way, the odds of this being anything we can solve in the addon code is slim to none.
