### ISSUE TITLE
Shield TV Pro (gen 3) movies crash

### ISSUE THREAD

**Issue by ShadwDrgn** [jellyfin/jellyfin-kodi#542]
**Describe the bug**
Attempting to play movies via Jellyfin (add-on mode) in movie library causes it to wait and think for 20-30 seconds before crashing out to the launcher and the launcher thinks something is playing in the background (it doesn't seem to be. no audio. nothing). The problem disappears if i connect directly to the container IP without traefik in the way, but it SEEMS to be fine connecting from jellyfin desktop via the same hostname which does put me through traefik.

**To Reproduce**
1. Go to movies
2. Click on any movie
3. Press okay to play movie OR just press play button
4. above described crash takes place

**Expected behavior**
Movie plays with no transcoding needed at all.

**Logs**
Kodi:
https://paste.kodi.tv/olefojegah
Jellyfin Server (south park episode played fine. Dragonheart... not so much:
https://paste.kodi.tv/vohaqaheqi

**Screenshots**
Didn't take a screenshot, but it would be of an aeon nox spinning loading icon.

**System (please complete the following information):**
 - OS: Shield Android TV 8.2.3 (note that this is actually android tv 9)
 - Jellyfin Version: 10.7.6
 - Kodi Version: 19.1.0
 - Traefik Version: 2.4
 - Addon Version: 0.7.4+py3
 - Playback Mode: Add-On

**Additional context**
Video plays fine from jellyfin app, and from smb share directly in kodi. TV Shows (some at least) seem to play okay too. Also works fine in LibreElec on 19.1.0. I haven't checked what add-on version that was on my libreelec yet. MPV Shim seems to work flawlessly too. ONLY Shield TV Kodi is broken as far as i can tell.

**Comment by mcarlton00** [comment]
As mentioned in chat, there's no errors in your logs except for one about websockets, which is highly suspicious but shouldn't be able to cause any playback failures.  Does the same movie play on other clients?  Does force transcoding work?  Is it all movies or only some?

**Comment by ShadwDrgn** [comment]
I did not seee a response in chat but i was joined from discord which seems to be bridged somehow. Where can I got for live chat that's reliable? I'd be happy to sit and troubleshoot this live.

The same movies all play on every other client I've got (except my mother's Firestick 4k, which seems to have issues in general). My desktop plays it in jellyfin desktop, even kodi on the shield itself plays it perfectly if i browse to the file directly via smb share.
I have not tried force transcode, but I shouldn't really have to, as I know shield is capable of playing the file directly as mentioned above. I didn't see a simple way to try that either. It's not ALL movies, it seems to possibly be all 4k movies though. My TV shows which are mostly in 1080p or less work fine.

**Comment by ShadwDrgn** [comment]
Ok here's where I'm at. The jellyfin-kodi plugin AND the jellyfin ATV app now works 100% of the time IF I map a port from the container to the host and connect directly via http. traefik seems to be a likely culprit here, but i've done a lot of experimentation and testing, and am now stumped on how to proceed with troubleshooting. The exact configs from the jellyfin documentation on traefik don't seem to fix this, nor do the comments from the seemingly related gh issue about traefik/jf-kodi. Any feedback would be massively appreciated. This now works fine in my home because of a rigged port map, but when i visit my mothers house 4k content will still crash constantly because she's coming in via traefik.

**Comment by mcarlton00** [comment]
As this is an issue with traefik and not specifically the Kodi addon, plus the fact that nobody that frequents this repo knows traefik, I'm going to close this and suggest you reach out to a different group for support.  We're largely flying blind at this point.
