### ISSUE TITLE
force transcoding from VP9 to H264

### ISSUE THREAD

**Issue by SonnTakuu** [jellyfin/jellyfin-kodi#544]
**Describe the bug**
I'm using X96Max Android TV Box which can decode VP9 by hardware, and I using KODI and Jellyfin plugin(add-on mode).

When I playback a VP9 videos from jellyfin server, it have to transcode to H264 and I can't set transcode or not in Kodi's Jellyfin plugin settings (it only have Hi10P HEVC etc.). 
When I open the VP9 video from USB with kodi, It says decoding by HW. So, how to playback VP9 videos from Jellyfin Server directly?

**System (please complete the following information):**
 - OS: [Android TV]
 - Jellyfin Version: [10.7.6]
 - Kodi Version: [19.1]
 - Addon Version: [Latest]
 - Playback Mode: [Add-On]

On Dashboard it says: Transcoding The media is being converted into a format that is compatible with the device that is playing the media. but no more information like why, or how far it transcoded.

**Comment by mcarlton00** [comment]
If I had to guess, it just needs to be added to this line.  I don't currently have any VP9 videos to test that with at the moment though.

https://github.com/jellyfin/jellyfin-kodi/blob/master/jellyfin_kodi/helper/playutils.py#L300

**Comment by SonnTakuu** [comment]
I changed the playutils.py and it can play VP9 videos directly now. Thank you.

**Comment by mcarlton00** [comment]
If you want to make a PR with the change since you've confirmed it works that would be great.  Otherwise I'll probably have time to get to it sometime in the next week or so.

**Comment by SonnTakuu** [comment]
Sorry, I don't know how to add VP9 option in settings, 
And please add AV1 support as well.

**Comment by SonnTakuu** [comment]
I made a PR and I tried VP9 options in settings work. Please check it.
