### ISSUE TITLE
Jellyfin-Kodi imports "criticRating" into the Kodi "userRating" database field (aka "My Rating")

### ISSUE THREAD

**Issue by WybeBosch** [jellyfin/jellyfin-kodi#569]
**Describe the bug**
When importing movies from Jellyfin into Kodi, jellyfin populates the "My Rating" Field with the value of <criticrating>
This happens both when there are NFO files (generated by Jellyfin) and when the are none. 

**To Reproduce**
- Inside jellyfin have a Library with the type "Movies"
- Its using network drives as the contents (not sure if relevant)
- Currently have both "The Open Movie Database" and "TheMovieDB" checked under Movie metadata downloaders

Problems occurs with Both having "Metadata savers" option "NFO" checked And Unchecked
(Happens even if i manually delete all NFO files before importing jellyfin library into kodi)

Inside Kodi:
- Removed the library from "managed libraries" in Jellyfin for Kodi settings
- did a "Reset local database" from Jellyfin for Kodi settings

- Choose the "native" import option for Jellyfin for kodi (And import your libraries)
- Open the Information screen of any movie
- Check the "My Rating" field and it reports the value belonging to the info from <criticrating> (as you would find it in the generated NFO files)

- These "critic" ratings are on a scale from 0-100, while Kodi's build in system uses a 0-10 rating. 
- So if you would enable a addon such as "Trakt" for Kodi to sync watched status and ratings it would fill Trakt watched history with pages full of movies having the "10" rating (since most ratings are Above 10 such as "21"  or "55")

**Expected behavior**
Jellyfin for Kodi ignores the "rating" and "criticrating" fields of NFO files, since the format in which they are supplied does not match the way Kodi expects them (https://kodi.wiki/view/NFO_files/Movies#nfo_Tags)

Or if there are no locally saved NFO files, that Jellyfin for Kodi doesnt import any ratings since Jellyfin doesnt Have any user ratings (outside of Scraper data for imdb etc)

**Logs**
https://drive.google.com/file/d/1TOBsCxGKo48a5ebanQ210g63TogRw1cR/view?usp=sharing

**Screenshots**
xxxxxxxxxxxxxxxxxx

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: [10.7.7]
 - Kodi Version: [19.1.0]
 - Addon Version: [0.7.4+py3]
 - Playback Mode: [Native]

**Additional context**

I thought it was because of the Structure of the NFO files generated by Jellyfin, since Kodi expects different NFO structure than Jellyfin provies. But even after removing the NFO files, removing the library via the Jellyfin for Kodi addon and then importing it again the issue still occurs. 

I made a post on the Kodi forums about it before realizing that it was not todo with the way Kodi handles NFO files, but rather with the way Jellyfin for Kodi imports / injects the movies into the Kodi database. 
For reference: [https://forum.kodi.tv/showthread.php?tid=364558 ](https://forum.kodi.tv/showthread.php?tid=364558 )

**Comment by mcarlton00** [comment]
It sounds like this has nothing to do with NFO files at all, and is more because of the metadata sync and how kodi's databases are .... not well documented.  Highly likely that something just isn't being translated correctly.

It's also possible that this is something Native mode specific.  It wouldn't make a ton of sense, but Native mode does have a handful of weird quirks and it wouldn't be that surprising if this is just another one of those.  Since nobody actually uses or devs on it, more of those tend to slip through the cracks.
