### ISSUE TITLE
Fails on install

### ISSUE THREAD

**Issue by LateralLines** [jellyfin/jellyfin-kodi#570]
Followed the [instructions](https://jellyfin.org/docs/general/clients/kodi.html#install-add-on-repository) for downloading the repo on "embedded devices" and installing the jellyfin addon, yet I get the following error message (verbatim from event logs in settings)

> The dependency on script.module.requests version 2.22.0+matrix.1 could not be satisfied.

I took a look at #477, though I'm still confused as to what I should do (wait it out for upstream to fix itself, install missing dependency, give up)
 
**System**
 - OS: CoreELEC
 - Kodi Version: 19.2-Matrix_rc3
 - Addon Version: 0.7.4+py3
 - Device: Odroid N2+

**Comment by mcarlton00** [comment]
This is an upstream Kodi issue.  Sometimes their addon mirrors are junk and decide that certain addons don't exist.  Typically, either waiting ~24 hours or (sometimes) nuking the whole `~/.kodi` directory and starting fresh will allow it to proceed.  But there's nothing we can do about it, unfortunately.  Alternatively, you can manually install any addons that are having issues by downloading them from upstream directly and installing as a zip file https://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.22.0+matrix.1.zip?mirrorlist

**Comment by bmalinconico** [comment]
@the-lazy-fox's method worked for me, essentially opening the official repo worked no need for me to reboot

**Comment by the-lazy-fox** [comment]
Yes reboot was just to retrigger all automatic updates :)
