### ISSUE TITLE
Kodi can't show the same movie in different collections。

### ISSUE THREAD

**Issue by serenity666** [jellyfin/jellyfin-kodi#572]
I like to classify some movies by myself, such as zombie films and horror films I often watch. I will add them to the collection created, but films like Resident Evil are both zombies and horror films. There is no problem with jellyfin, but after syncing to Kodi, only one of the two collections can display the movie Resident Evil. Look at the screenshot.

![QQ截图20210924150255](https://user-images.githubusercontent.com/64485323/134634119-6b102f08-cc10-4d5b-8c71-a7daabece8a2.png)
![QQ截图20210924150302](https://user-images.githubusercontent.com/64485323/134634139-1e45a71d-6d78-439a-8b1e-5af77c3bf54b.png)

![QQ截图20210924150153](https://user-images.githubusercontent.com/64485323/134634153-6a51ec23-b734-4d5d-8b45-15270a9c5ea8.png)
![QQ截图20210924150206](https://user-images.githubusercontent.com/64485323/134634182-e9e952d3-131b-4f94-bc71-6b4565a98856.png)
 - OS: Android, Windows10
 - Jellyfin Version: 10.7.6
 - Kodi Version: 18.9，19.2
 - Addon Version: 0.7.4
 - Playback Mode:Native

**Additional context**

**Comment by mcarlton00** [comment]
This is a limitation in vanilla Kodi, movies can only be in a single set at a time.  There's nothing we can do about it
