### ISSUE TITLE
Update project layout to conform to Kodi v17+ 

### ISSUE THREAD

**Issue by graybush** [jellyfin/jellyfin-kodi#58]
Currently the code base adheres to Kodi v16 Jarvis and earlier directory layout. 
###  [v16 Jarvis and earlier](https://kodi.wiki/view/Add-on_structure#Kodi_v16_Jarvis_and_earlier)
<pre>addon.py
addon.xml
fanart.jpg
icon.png
LICENSE.txt
changelog.txt
resources/
  settings.xml
  language/
  lib/
  data/
  media/
</pre>
### [v17 Krypton and up](https://kodi.wiki/view/Add-on_structure#Kodi_v17_Krypton_and_up)
<pre>addon.py
addon.xml
LICENSE.txt
resources/
  settings.xml
  language/
  lib/
  data/
  media/
  fanart.jpg
  icon.png
</pre>

**Comment by mcarlton00** [comment]
@graybush I believe this was fixed in your PR (#62), correct?

**Comment by graybush** [comment]
@mcarlton00 correct.
