### ISSUE TITLE
Kodi sync queue don't sync on andriod TV

### ISSUE THREAD

**Issue by youland** [jellyfin/jellyfin-kodi#597]
Debian Bullseye running Jellylfin server 10.7.7,it is ok
Sony TV install kodi 19.2,kodi install jellyfin addon 0.7.7
When I delete a movie on the jellyfin server, kodi does not delete it in parallel.
When I update the movie name on the jellyfin server, kodi doesn't update the movie name at the same time.
When I reset the jellyfin plugin in kodi and reconnect to the jellyfin server, it shows the latest movies in sync, which will then sync with jellyfin.
Kodi sync queue already enable on jellyfin server.

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: [10.7.7]
 - Kodi Version: [19.2]
 - Addon Version: [0.7.7]
 - Playback Mode: [Add-On]

**Comment by oddstr13** [comment]
The sync usually isn't instant, and can take a few minutes

**Comment by mcarlton00** [comment]
Kodi Sync Queue is only used when Kodi is first started to "catch up" with the server.  Changes made in the server while Kodi is running are pushed to Kodi via a websocket connection, but if that has failed then things tend to get "lost" until a manual sync fixes them.  I suspect this is what you're running into, with android TV's power saving or switching apps killing the websocket connection.  In the next release this will be more resilient and should reconnect more reliably

**Comment by youland** [comment]
@mcarlton00 Thanks,Looking forward to a new release and fix it.

**Comment by mcarlton00** [comment]
Closing as this particular issue should be long since fixed.
