### ISSUE TITLE
Kodi crashing after trying to play media through Jellyfin.

### ISSUE THREAD

**Issue by whyiseveryfuckingnameisalreadyused** [jellyfin/jellyfin-kodi#603]
Describe the bug
Whenever I try to play a video with Jellyfin Kodi just crashes, but Jellycon plays the video fine. Jellyfin worked fine until like a week ago, I tried reinstalling Jellyfin addon, Kodi, and I even reinstalled my system.

To Reproduce
I think it's specific to my device, but here it is:
1. Open Kodi
2. Select anything from the synced libraries

Expected behavior
Kodi should play the media, and not crash.

Logs
https://pastebin.com/nMTRGFhZ

System (please complete the following information):
 - OS: EndeavourOS
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.3
 - Addon Version: 0.7.7
 - Playback Mode: Add-On

Additional context
Looks like I have a bunch of python errors in the log, should I try downgrading python?

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
Downgrading python from 3.10.1-1 to 3.10.0-1 fixed the issue.

**Comment by mcarlton00** [comment]
This unfortunately appears to be an upstream python issue that afaik we're unable to do anything about.

https://bugs.python.org/issue46070
