### ISSUE TITLE
Remove or rename png artifacts

### ISSUE THREAD

**Issue by graybush** [jellyfin/jellyfin-kodi#61]
Digging through the project I stumbled upon the following artifacts. I did a quick search of the addon and was unable to find any references to the following files in the source code. The ones with emby in the name I would think should be removed or renamed. The rest I am unsure about.
<pre>resources/skins/default/media/
  box.png
  button-focus.png
  radio-off.png
  emby-bg-fade.png
  emby-icon.png
  emby-separator.png
  kodi-icon.png
  qrcode_disclaimer.png
  radio-on.png
  userflyoutdefault2.png
</pre>

**Comment by TrueTechy** [comment]
Looking through the commits from the emby plugin some of these were for emby connect 

  button-focus.png
  emby-bg-fade.png
  emby-separator.png
  qrcode_disclaimer.png
  userflyoutdefault2.png

and the others were for a user preferences dialog.

Given that these are not referenced in the code, I'd say it's safe to delete them all
