### ISSUE TITLE
Addon fails to start on Xbox Series X (Permission error)

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#612]
**Describe the bug**

The addon installs correctly from the repo on Xbox Series X, but fails to start with an error notification. When trying to open the addon, menu is empty. Settings work though (and allowed me to set the log level to debug) (Kodi UWP on Microsoft Store is 19.3 version)

**To Reproduce**

Install Kodi from Microsoft Store on Series X
Install the Jellyfin Kodi repo from USB drive
Install Jellyfin from the repo
-> Error at each Kodi launch

**Expected behavior**

The addon should start and display server configuration

**Logs**

https://paste.kodi.tv/uhafolaxeq.kodi
See permission error at line 784

**Screenshots**

**System (please complete the following information):**
 - OS: Xbox Series X OS
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.3
 - Addon Version: 0.7.7
 - Playback Mode: Add-On

**Comment by LeVraiRoiDHyrule** [comment]
Found a fix here : https://forum.kodi.tv/showthread.php?tid=365157&page=10
There should also be more info on the source of the issue

**Comment by oddstr13** [comment]
Issue is fixed but not released upstream: xbmc/xbmc#20501
Backported patch xbmc/xbmc#20528 looks to be scheduled for release of Kodi 19.4, whenever that is.

Leaving open for visibility, but there is nothing to be done here.
