### ISSUE TITLE
Music Title Via Remote Play

### ISSUE THREAD

**Issue by jwor80** [jellyfin/jellyfin-kodi#616]
**Describe the bug**
If I start music in Kodi via Yatse (Remote for Kodi) the title of the music says stream.mp3 on all music.  If I start the music via keyboard the title of the music is displayed correctly.  Kodi for JellyFin is the only time I see this issue.  I do not see it with Emby or a local Kodi setup.

**To Reproduce**
1. User your phone to launch Yatse
2. Browse to files > playlist > play a song
3. Kodi will display the title as stream.mp3

**Expected behavior**
When starting music via yatse, the title of the music should display the name of the song

**Logs**

**Screenshots**
![Yatse](https://user-images.githubusercontent.com/38135239/153508484-824ed0ca-40e9-4ff0-b0c5-b07b5eea1a4e.jpg)
![Kodi](https://user-images.githubusercontent.com/38135239/153508492-59211fe0-3e89-4467-b73d-e04aa5932cef.jpg)

**System (please complete the following information):**
 - OS: RaspberryPi OS or Windows 10
 - Jellyfin Version: 10.7.7
 - Kodi Version: 18.9 & 19.3
 - Addon Version: 7.4 through 7.7
 - Playback Mode: Add-On

**Additional context**

**Comment by mcarlton00** [comment]
Logs would be more helpful here.  Not screenshots.  And I can't replicate this.  Installed addon, synced a music library to Kodi, remote controlled Kodi through Yaste, Kodi shows the correct name of the playing track.

**Comment by jwor80** [comment]
I'm still able to reproduce if I got through the playlist option, but going into Music first seems to resolve this issue.  Since there is a workaround I'm fine to close this issue.
