### ISSUE TITLE
Master Lock breaks Plugin

### ISSUE THREAD

**Issue by runzhammer** [jellyfin/jellyfin-kodi#619]
**Description**
Empty libraries, no "manage libraries" among other missing options like in https://github.com/jellyfin/jellyfin-kodi/issues/613

**To Reproduce**
1. Fresh install Kodi 19.x
2. install Jellyfin for Kodi Plugin
3. setup plugin
4. sync libraries: everything should be fine
5. Add a method for locking in Settings/Interface/Master lock - no need to select something else
6. Library content disappears
7. Options in Plugin disappear

**Expected behavior**
Master Lock should not break libraries and/or plugin

**System:**
 - OS: Android, not tested others
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.3 / 19.4
 - Addon Version: 0.7.7
 - Playback Mode: Add-on

**Comment by mcarlton00** [comment]
Duplicate of #169.  Known issue, no solution yet

**Comment by matmielke** [comment]
Is there any solution planned or at least a workaround available?
I'd like to implement the following scenario:

- One Kodi installation on SmartTV
- One central Jellyfin installation with separate users (family and adults)
- Kodi should have one profile for alle the movies (jellyfin's adult profile) with PIN protection and one family profile without PIN

As soon as I enable the PIN, the content disappears at the moment.
