### ISSUE TITLE
Port / Firewal

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin-kodi#626]
**Describe the bug**
It appears that jellyfin for kodi are somehow not using the standard ports for NFSv4 111/2049 for connecting (lookup) to the NFS server.

Here is the rules I have in my firewall, which is working fine on any other linux client on the network.

```
# NFS Server share
udp dport nfs ip saddr $rfc_1918 counter accept comment "NFS"
tcp dport nfs ip saddr $rfc_1918 counter accept comment "NFS"
udp dport sunrpc ip saddr $rfc_1918 counter accept comment "SunRPC"
tcp dport sunrpc ip saddr $rfc_1918 counter accept comment "SunRPC"
 meta l4proto { tcp, udp } th dport { sunrpc, nfs } ip saddr $rfc_1918 accept comment "Accept NFS"
```

**To Reproduce**
1. Start playing a video 60 timeout, then using http

**Expected behavior**
Playing via port 2049 (NFS) share and not on limited http

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Nvidoa
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]
 - Playback Mode: Add-On

**Additional context**

The question is, which ports are required on the NFS to be open for jk to work?

**Comment by mcarlton00** [comment]
Jellyfin for Kodi doesn't use NFS at all.  The only network communication we do is http(s) to your server.  Anything involving shared network storage goes through Kodi's internals.  You should test if this happens without the addon and contact the Kodi devs.

**Comment by spirillen** [comment]
Thanks for the feedback, I get in touch at the kodi repo
