### ISSUE TITLE
how to install update

### ISSUE THREAD

**Issue by allhailCdosdude** [jellyfin/jellyfin-kodi#636]
**Describe the bug**

It is not a bug, only that either the instructions are not correct (https://jellyfin.org/docs/general/clients/kodi.html)
the file zip to download from that link is much too old.
perhaps it might help to link this latest file here to that instruction.
meanwhile, can someone please say how to remove the steps in the above directions and add the file from here, github?

**Expected behavior**

Need to find "Add-on Browser" as per instructions (https://jellyfin.org/docs/general/clients/kodi.html) but not there.
Need to add zip file as per instructions, above, selecting the added repo does not engage 'ok' in kodi, so can't add file.
**Logs**

**System (please complete the following information):**
 - OS: [AppleTV 2]
 - Jellyfin Version: [latest]
 - Kodi Version: [14.2]
 - Addon Version: [https://kodi.jellyfin.org/repository.jellyfin.kodi.zip]

**Additional context**

I am simply trying to install jellyfin plugin in kodi on an appletv2 so that I can enjoy files from my jellyfin server. thanks a lot if you can help.

**Comment by mcarlton00** [comment]
I'm not sure which zip file you're referring to.  The only zip file referenced in that document is the addon repository, which absolutely works just fine.  However, if what you've reported is correct and you're actually trying to use Kodi 14, you're _hilariously_ out of date and there's no chance of our addons working.  We support Kodi 18 or 19, with 19 being far preferred.

The addon browser is when you open Kodi's settings and select "add-ons"

**Comment by allhailCdosdude** [comment]
> I'm not sure which zip file you're referring to. The only zip file referenced in that document is the addon repository, which absolutely works just fine. However, if what you've reported is correct and you're actually trying to use Kodi 14, you're _hilariously_ out of date and there's no chance of our addons working. We support Kodi 18 or 19, with 19 being far preferred.
> 
> The addon browser is when you open Kodi's settings and select "add-ons"

Thanks a lot. I'm indeed "hilariously out of date." Thank you very much. I could have saved a lot of time, asking here first if Kodi 14 would work. And here we go again, another device for the dustbin!
Cheers.

**Comment by mcarlton00** [comment]
Kodi 14.2 came out in [March of 2015](https://kodi.tv/article/kodi-142-helix-final-translation/).  I'm honestly not even sure how you managed to get it installed.  There are methods to get Kodi 19 onto an AppleTV, but if you don't have an AppleTV 4 it appears you need to jailbreak your device.  https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Apple_TV_4_and_5_(HD_and_4K).  I don't have any experience with that and can't give any guidance.

**Comment by allhailCdosdude** [comment]
> Kodi 14.2 came out in [March of 2015](https://kodi.tv/article/kodi-142-helix-final-translation/). I'm honestly not even sure how you managed to get it installed. There are methods to get Kodi 19 onto an AppleTV, but if you don't have an AppleTV 4 it appears you need to jailbreak your device. https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Apple_TV_4_and_5_(HD_and_4K). I don't have any experience with that and can't give any guidance.

Thanks a lot. I got Kodi 14.2 installed in an ATV2. I don't own an ATV4. We have arrived at the end.
