### ISSUE TITLE
Replacing some media file with a different version of the same content causes some sync issue requiring repair of the library

### ISSUE THREAD

**Issue by singularity098** [jellyfin/jellyfin-kodi#639]
**Describe the bug**
Seems that if I replace some movie or television show media with a different version of the same thing, then Jellyfin for Kodi has trouble updating the library and future syncs are now broken until I repair the library.  The actual server handles this perfectly fine, it just seems that the Kodi add-on gets tripped up.

**To Reproduce**
1. Suppose that I have some random Superhero Movie, and it's a 1080p version which is already synced to Kodi.
2. On Jellyfin server, delete the 1080p version of the movie and replace with 4k version (different filename).
3. Add some other new content to the library as well.
4. Start up Kodi.
5. Newer content is not synced.  Nothing new that is added to this library will be synced now or into the future, until I "repair" the affected library in Jellyfin for Kodi.

**Expected behavior**
All new content should sync, regardless of whether it's brand new content to my server, or a replaced new version of something already existing.

**System (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.4
 - Addon Version: 0.7.7+py3
 - Playback Mode: Add-On

**Comment by mcarlton00** [comment]
Logs will tell us if the server is actually sending us the updated file.  Without that, we have no clue if this is a processing issue on the kodi side or an issue on the server side.

**Comment by oddstr13** [comment]
I would like to note that this is working fine in my setup, and that media file swapping occurs quite often.

If you are still having this problem, please provide logs, and request reopen of this issue.
