### ISSUE TITLE
Help needed to run Library updates remotely.

### ISSUE THREAD

**Issue by bugbounce** [jellyfin/jellyfin-kodi#649]
Hello,
I run a Jellyfin instance for friends and family and manage a few remote Kodi instances(RPi 4, OSMC) which connect to the Jellyfin server via this plugin. There are occasional sync failures and I can usually fix them via a full library repair. However, not all my "clients" are technically adept and require assistance in repairing/updating the library manually. Is there a way I can run the plugin's "Manage Library" functions remotely ? Maybe via the web interface's "API Browser" through JSON/RPC ? (https://kodi.wiki/view/JSON-RPC_API/v12#Addons.ExecuteAddon)

- I have SSH access to all the clients.
- I have web Interface access to all clients.

App versions :
 - Jellyfin Version: 10.7.7
 - Kody Sync Queue Plugin : 6.0.0
 - Kodi Version: 19.3
 - Addon Version: 0.7.9
 - Playback Mode: Add-On

Thanks in advance.

**Comment by mcarlton00** [comment]
I haven't verified this, but presumably you could trigger the same plugin commands that the manage libraries menu calls.

https://github.com/jellyfin/jellyfin-kodi/blob/f1977c01854ccd18a12f0cbc79473ca0c2b12d74/jellyfin_kodi/entrypoint/default.py#L248-L253

It then goes through the `OnNotification` function.  If looks like currently you'll have to find a way to spoof the sender to be the addon so it follows the correct code paths

https://github.com/jellyfin/jellyfin-kodi/blob/f1977c01854ccd18a12f0cbc79473ca0c2b12d74/jellyfin_kodi/entrypoint/service.py#L146-L157

**Comment by bugbounce** [comment]
Thanks for the advice. Could not get the RPC to work. The parameters passed aren't getting parsed properly and the debug logs aren't much help. 

However, I stumbled onto a way to get it done via the Chorus web interface. The following worked for me :

`  http://osmc:osmc@10.168.143.15/#browser/music/plugin%3A%2F%2Fplugin.video.jellyfin%2F%3Fmode=repairlib&id=48fede0f9ee96b1a449b277ee2b920ae,c248dc0bec4b0ce8fb01231d1f12c5c1,49b1d0fe8ffadb66014d075325247cf2,396e77fb30fb44562223be713bd1418c,a656b907eb3a73532e40e44b968d0225
`
I can pass all the library ids separated with commas and it works just fine.

**Comment by maxim-sm** [comment]
Thanks @bugbounce and @mcarlton00 for the useful information. I also needed to trigger a library update remotely, and if someone will find it useful, this is how I did it with curl and jsonrpc:

```
curl -D - --user osmc:osmc -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method": "Files.GetDirectory", "id": "bash-script", "params": {"directory": "plugin://plugin.video
.jellyfin?mode=updatelib&id=f137a2dd21bbc1b99aa5c0f6bf02a805"}}' 192.168.1.6/jsonrpc
```
