### ISSUE TITLE
Every time i startup kodi, a popup "select main server"

### ISSUE THREAD

**Issue by klgd** [jellyfin/jellyfin-kodi#65]
I had manually add server before, when next time i startup kodi, the "select main server" is display
![20190905095108](https://user-images.githubusercontent.com/8554422/64305680-b80d5f80-cfc2-11e9-8419-d10ac0712bb0.jpg)

**Comment by mcarlton00** [comment]
Some extra information will make tracking this down much easier.

* What device is Kodi running on?
* What Kodi version number?
* Is your Jellyfin server on the local network, or remote?

**Comment by klgd** [comment]
> Some extra information will make tracking this down much easier.
> 
> * What device is Kodi running on?
> * What Kodi version number?
> * Is your Jellyfin server on the local network, or remote?

sorry, i forgot to write
kodi v18.4 "Leia" on android(8.1) mobile phone(miui system 10.8.12.20)
jellyfin for kodi v0.2.1
fellyfin server v10.3.7 and server on the local network(192.168.1.166:8096)

**Comment by TrueTechy** [comment]
Have you tried reinstalling the Kodi app, then the jellyfin addon to see if the problem persists? 

If you have and it's still popping up each time could you provide us with the kodi log from your device. Since it's an android I believe the easiest way to get the log is to install the kodi log updater addon from the kodi repository and then you can share that URL with us

**Comment by klgd** [comment]
@TrueTechy 

yes, i had reinstall kodi, the problem persists, please help me, thanks
[kodi.old.log](https://github.com/jellyfin/jellyfin-kodi/files/3593263/kodi.old.log): installed kodi, install jellyfin addon and connect jellyfin server
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/3593265/kodi.log): restart kodi, and reconnect jellyfin server

**Comment by klgd** [comment]
> Looking through the logs it looks like the addon is having issues with saving and retrieving addon settings. I also see that your server name in not in english and in my testing this seems to produce the same issue you're having. Could you change the server name to an english word to test if this stops the popup coming up?

thanks, i will try it  tomorrow, and tell the result

**Comment by klgd** [comment]
@TrueTechy  it's ok, you are right，i changed the server name, the popup not coming up

**Comment by mcarlton00** [comment]
Good catch.  We should fix this in the code, imo.  The server doesn't have any restrictions on what the name can be, so we should support any options as well.  Reopening so we can continue tracking the issue until a fix is implemented.

**Comment by klgd** [comment]
@mcarlton00  ok  thanks
