### ISSUE TITLE
Failed to install add-on form zip file

### ISSUE THREAD

**Issue by AkarinLiu** [jellyfin/jellyfin-kodi#650]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

![image](https://user-images.githubusercontent.com/58081491/167965195-636260cb-dc92-47b9-97e0-5a2b3736ae9e.png)

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]
 - Playback Mode: [e.g. Add-On or Native]

**Additional context**

**Comment by oddstr13** [comment]
https://repo.jellyfin.org/releases/client/kodi/py2/plugin.video.jellyfin/plugin.video.jellyfin-0.7.8%2Bpy2.zip

**Comment by oddstr13** [comment]
0.7.9 was a CI misshap, is identical to 0.7.8, and did not actually get built.
