### ISSUE TITLE
Hide back folder button

### ISSUE THREAD

**Issue by kevoh1516** [jellyfin/jellyfin-kodi#664]
![image](https://user-images.githubusercontent.com/21131329/182035024-1ccedb3a-f8b4-40cb-9b45-0c1dd57362dd.png)

How can I remove the back to folder button in the top left? Currently using kodi for jellyfin plugin + Aeon Nox: Silvo theme.

**Comment by oddstr13** [comment]
This is a Kodi question, and not specific to this addon – the list of movies is rendered by Kodi itself.

**Comment by kevoh1516** [comment]
Hmm, ok will close this then and ask on Kodi.
