### ISSUE TITLE
How to watch Live TV from jellyfin with this addon?

### ISSUE THREAD

**Issue by Ilia1** [jellyfin/jellyfin-kodi#667]
I want see IPTV on kodi. I connect m3u playlist to jellyfin. If jellyfin has url for connect to iptv simple addon, I can do it. If no, I want watch IPTV with this addon.

**Comment by mcarlton00** [comment]
If you have live tv content in your jellyfin server, you'll see it as an option when you open the addon menu
![2022-08-13-200503_1915x1054_scrot](https://user-images.githubusercontent.com/17029228/184517288-ad741756-96ae-4ced-87cf-0aec8fb5e748.png)
.
