### ISSUE TITLE
Is there a Wake-on-Lan solution for jellyfin servers?

### ISSUE THREAD

**Issue by dakotahawkins** [jellyfin/jellyfin-kodi#671]
I found [Remove WOL Code (#140)](https://github.com/jellyfin/jellyfin-kodi/pull/140), so it seems clear that it's never been implemented here, but my question is does it matter? Is Kodi able to take care of this on behalf of jellyfin?

I'm in a situation where I really want this to work, and for the first time ever I've actually managed to get Wake-on-Lan working correctly on my PC (Windows 10, also my jellyfin server).

Any advice or a summary of the current situation would be appreciated, and thank you in advance for your time :)

**System**
 - OS: Android player, Windows 10 server
 - Jellyfin Version: latest stable
 - Kodi Version: latest stable
 - Addon Version: latest stable
 - Playback Mode: Native

**Comment by mcarlton00** [comment]
No, there's no WOL functionality in the JF server.  I'm not sure if there's any alternative method you could use, but there's nothing built in.  Good luck!

**Comment by dakotahawkins** [comment]
Thanks for the quick response, @mcarlton00 :)
