### ISSUE TITLE
version 6 in kodi 17.6 and jellyfin kodi plugin 0.5.8 problem

### ISSUE THREAD

**Issue by xykz** [jellyfin/jellyfin-kodi#673]
my device android version is 6.0, only can use kodi 17.6 and jellyfin kodi plugin 0.5.8

after I upgrade jellyfin to 10.7.2 and installed jellyfin-plugin-kodisyncqueue version 6

the kodi library always can't auto update. but update by manual is work.

kodi 17.6 and jellyfin kodi plugin 0.5.8 still support?

**Comment by mcarlton00** [comment]
Kodi 17 is ancient and no longer supported.  It's unfortunately just too much of a drain on resources to maintain compatibility with versions that old.
