### ISSUE TITLE
No sync in days, how to troubleshoot?

### ISSUE THREAD

**Issue by axelsimon** [jellyfin/jellyfin-kodi#674]
I have Kody Sync Queue 6.0.0.0 on Jellyfin 10.7.7 talking to plugin.video.jellyfin v0.7.7+py3 on Kodi 19.4 (Coreelec).

Or not talking, that's the issue.
I can see in `.kodi/userdata/addon_data/plugin.video.jellyfin/sync.json` that the last sync was on "2022-03-19T11:20:10Z" but it doesn't look like it worked: new items added to Jellyfin on the 6th of March still don't show up in Kodi's library.
Beyond that, trying to manually sync the library does nothing: going into the Jellyfin add-on settings to update the library does nothing at all. No reaction. Same for repairing.

Any clues?

**Comment by mcarlton00** [comment]
Without logs at the time of failed syncs, it's basically impossible to identify what the cause was.  I would guess that it had to do with the websocket connection failing, which should be much more reliable in current releases of the addon.
