### ISSUE TITLE
Release Date in JF does not translate to Premiered Date in Kodi

### ISSUE THREAD

**Issue by LentulisBatiatus** [jellyfin/jellyfin-kodi#680]
Kodi will use the 'Premiered Date' to sort movie titles by date of actual release. JF does scrape this info from metadata scrapers or NFO but the JF-Kodi addon does not bring this info across. This is useful info for certain sorting like collections. For example the Marvel Cinematic Universe order is by film release date. Without the actual day of release you end up with an out of order MCU where Ant-Man comes before Age of Ultron, or Ant-Man 2 comes before Infinity War. Hope this os possible to sort out.

**Comment by LentulisBatiatus** [comment]
Thank you for adding this into JF-Kodi!

**Comment by LentulisBatiatus** [comment]
I tried updating the most recent files from Github into my JF addon but it produced this error from the log. I am unsure what has gone wrong. Apologies if this isn't how one should report this.

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (service.py, line 8)
                                            Traceback (most recent call last):
                                              File "C:\Users\flami\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\service.py", line 10, in <module>
                                                from jellyfin_kodi.entrypoint.service import Service
                                              File "C:\Users\flami\AppData\Roaming\Kodi\addons\plugin.video.jellyfin\jellyfin_kodi\entrypoint\service.py", line 8
                                                <!DOCTYPE html>
                                                ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--

**Comment by oddstr13** [comment]
Likely an issue with how you copied the file over, nothing in the lines up to 8 in that file would give a syntax error

**Comment by LentulisBatiatus** [comment]
I saved the files from github and copied them into the JF-Kodi addon folder then started JF. Is there an update to the addon through the repo or another method I should be using? I feel like a noob.

**Comment by LentulisBatiatus** [comment]
Still unsure how to implement this change into JF-Kodi and have it working correctly. If I just copy the files into the addon folder I end up with an error as noted before and I can't access most of the options from within the addon itself (manage libraries etc.). I've tried updating the addon but that doesn't have the premiered date appearing. I know I'm doing something simple wrong but I just can't figure out what.
