### ISSUE TITLE
No sound with dual audio

### ISSUE THREAD

**Issue by whyiseveryfuckingnameisalreadyused** [jellyfin/jellyfin-kodi#685]
Whenever i play media with dual audio the first video plays fine, but the second video will have no sound at all. Restarting kodi fixes it, but it's needed every time i want to watch more than one video

**To Reproduce**

1. Play video with dual audio
2. Close the video
3. Start an other (or the same) video
4. No sound

**Expected behavior**
Videos should have sound without restarting kodi

**Logs**
https://pastebin.com/nwHr7jsf

**System (please complete the following information):**
 - OS: EndeavourOS
 - Jellyfin Version: 10.8.5
 - Kodi Version: 19.4-5
 - Addon Version: 0.7.8
 - Playback Mode: Add-On

**Additional context**

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
I also tried kodi-git from aur but it has the same problem.

**Comment by mcarlton00** [comment]
I'm not able to replicate this.  Of the dozen tests I've ran across my library, all files have had audio output immediately on starting playback, along with being able to toggle between audio tracks without issue.  And there's nothing in your logs that I can see that's indicating any problem with the addon code.  The only thing in your logs that I can see are the lines following `ActiveAE::InitSink - failed to init`.  This looks like a hardware/device issue of some kind.

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
It was solved by an update (i suspect python)
