### ISSUE TITLE
Kody Sync Queue wakes kodi client htpc when sync request is triggered

### ISSUE THREAD

**Issue by h3llrais3r** [jellyfin/jellyfin-kodi#697]
I have switched from kodi with mysql setup to jellyfin (jellyfin for kodi plugin) and I have enabled the kodi sync queue plugin as adviced.
However, it seems that when my htpc kodi client awakes from sleep when the kodi sync queue is requesting a sync request.
Not sure if this is intended or a bug, or could have it something to do with my setup?
My htpc is triggered via my remote to go in sleep when not used.
Before my switch to jellyfin, the htpc remains in sleep until my trigger it to wake via remote.
Since the migration to jellyfin, it seems to wake my htpc every few minutes automatically.
From the logs on the jellyfin server I see that the kodi sync queue has triggered a sync request at that time.
When I disable kodi sync plugin, the htpc seems to remain in sleep.

If this is intented, what's the side effect of not using the kodi sync queue?
If it's not intended, it would be great if there could we a workaround for this, or even better, if it could be fixed. :)

**Comment by oddstr13** [comment]
I have never seen this happen on my laptop nor gaming rig, more information about your setup, and logs are required.

Only thing I could think of is TCP keepalive of some sort waking the HTPC (for example, wake on LAN, any addressed packet)

**Comment by h3llrais3r** [comment]
I think I made the assumption too early, as I started to notice it around the time I installed the plugin.
But I can already confirm it's not coming from the plugin... it seems that something else from my laptop seems to wake the HTPC, but I can't seem to figure it out. Anyway, I'll close the issue, as it's not related to the plugin
Thanks for support!
