### ISSUE TITLE
Missing Add-on

### ISSUE THREAD

**Issue by Head-Scratcher** [jellyfin/jellyfin-kodi#706]
**Describe the bug**
Add-on does not exist

**To Reproduce**
2. Install JellyCon Add-on
    From within Kodi, navigate to "Add-on Browser"
    Select "Install from Repository"
    Choose "Kodi Jellyfin Add-ons", followed by "Video Add-ons"
    Select the JellyCon add-on and choose install

**Expected behavior**
Expected it to be there as per the instructions. There are no add-ons starting with J or K, even with all hidden and other settings set to show.
There is no Kodi Jellyfin Add-ons under Video Add-ons either, in case the instructions were typed back to front.

**Logs**
No log since there is nothing to install

**System (please complete the following information):**
 - OS: Android
 - Jellyfin Version:
 - Kodi Version: 20.0 Nexus
 - Addon Version:
 - Playback Mode: Add-On

**Additional context**
Tried to download the zip from jellyfin-kodi and install it from the zip file. Brought up an error message about not understanding the structure of the file, or some other similar message.

**Comment by mcarlton00** [comment]
You haven't installed our addon repository.  Our addons can't go in the upstream Kodi repos, so we host our own addon repository for easier updates and distribution: https://jellyfin.org/docs/general/clients/kodi/#install-add-on-repository

**Comment by Head-Scratcher** [comment]
Thanks, that was the repo I was looking for. Some of the issues I was also having was with Kodi 20.0 Nexus, it doesn't show the add source option to allow the repo install unless you turn on a couple of things in the settings. In my previous installations of Jellyfin for Kodi I added the repo and included it in my own Kodi install instructions.
This is my first attempt to install JellyCon because I am having all sorts of compatibility issues trying to sync data between the Kodi database to the Jellyfin one. I must have installed and uninstalled Kodi a dozen times and every time I do an install I get a different result.
So I am attempting to reduce it down to one source of truth and have the Jellyfin database on just my Synology NAS box.



    On Friday, 27 January 2023 at 11:29:30 pm AEST, mcarlton00 ***@***.***> wrote:  
 
 


You haven't installed our addon repository. Our addons can't go in the upstream Kodi repos, so we host our own addon repository for easier updates and distribution: https://jellyfin.org/docs/general/clients/kodi/#install-add-on-repository
