### ISSUE TITLE
Add play on functionality in Kodi 

### ISSUE THREAD

**Issue by gzpr** [jellyfin/jellyfin-kodi#709]
Would it be possible to add the "play on" functionality present in the web client to kodi as well? This would allow Kodi to be used in conjunction with mpv-shim. As of now both jellycon and this add on have issues when mpv is used as an external player as evidenced here #571  , not to mention kodi's support of external players is fairly limited  anyway (no watch progress) .

**Comment by mcarlton00** [comment]
We've had this feature literally since day 1 of the project existing, both in jellyfin for kodi and jellycon., so I'm not really sure what you're asking for.  

![2023-02-19-133024_259x325_scrot](https://user-images.githubusercontent.com/17029228/219967824-3be50041-9f31-439f-bf02-b42661c3ae0e.png)

**Comment by gzpr** [comment]
I know you can cast from jellyfin web/jellyfin media player to kodi. What I'm asking for is being able to do it the other way around i.e. setting the play on device on kodi. So instead of kodi playing  content using its own player, it plays it on another client e.g. mpv-shim.

**Comment by mcarlton00** [comment]
No.  Why?  I see virtually no reason to ever do such a thing.  Kodi's playback system is pretty robust and can play basically anything.  You're just adding links to the chain and improving risks of playback failure.

**Comment by gzpr** [comment]
As I've said, my use case would be using kodi with mpv, which has a much higher extensibility and customizability than kodi's default player. Kodi's native support for external players is limited but somewhat usable,  however with either of the jellyfin add ons using one is extremely annoying and basically unusable what with the issue I mentioned.  I realize it's something that might be relatively niche, but I'm sure I'm not the only one using kodi with mpv, so if it wouldn't require much effort it'd be greatly appreciated if there was some disabled by default option tucked away in the settings that would allow me to cast to mpv-shim.

**Comment by mcarlton00** [comment]
Yeah, so I have no interest in adding/supporting daisy chained clients.  There's so, so many ways that can break and cause ongoing maintenance issues, plus it's just unreasonable.  Kodi is a player, it doesn't make sense to make it remote control _another_ player.

I guess if you were to want to patch it yourself, you're more than welcome to, but I don't think it makes sense to have it in the addon.  This is the nichest of niche things.  Probably far more reasonable to find a way to improve external player support in kodi, if that's even possible.  If you want to maintain your own patch, you'd likely need to replace this function with some api calls to the server: https://github.com/jellyfin/jellyfin-kodi/blob/6040bc99d470350ee0bf30965053eaf71e4c8440/jellyfin_kodi/objects/actions.py#L62-L79
