### ISSUE TITLE
[Bug Report] Up Next + Jellyfin server

### ISSUE THREAD

**Issue by tundrablasen** [jellyfin/jellyfin-kodi#717]
Im using up next in kodi with the official jellyfin kodi addon to populate my media library.
https://github.com/im85288/service.upnext

up next works fine with that setup for the first episode. 
(I play episode 1, and in the end of it up next comes up to ask if I wanna play episode 2.)

but when I continue watch episode 2, in the end of episode 2, no pop up comes, to ask for playing episode 3.

In the settings I have set it up that after 3 episodes it should ask if I’m still watching. 

When I’m manually stopping the playback and start to play again, the cycle starts again.

did anybody notice this behaviour?

**Comment by tundrablasen** [comment]
Update:

another developer seems to have found the bug in the code of Jellyfin for Kodi

see here for more technical details.
https://github.com/im85288/service.upnext/issues/297#issuecomment-1558739027

It would be super good if the maintainer of jellyfin fpr kodi could fix this bug

**Comment by DrDagless** [comment]
I'm having a similar issue, where the first instance of up next works fine. But then after the second episode, it will oddly loop me back to the first episode instead of the third.  Strange stuff, but looks like the problem was identified by the Up Next dev?

Any updates on the issue on this end?

**Comment by tundrablasen** [comment]
I haven’t any update

**Comment by mcarlton00** [comment]
The last update on the linked upnext issue says that it fixed itself by updating Kodi.  I personally haven't seen this happen, but I usually don't watch that many episodes of things at one time.

**Comment by DrDagless** [comment]
I'm on beta 2 of Omega (21) and it's unfortunately not resolved itself. I'd update to beta 3 but I'm pretty sure there are still some database issues going on.

**Comment by CeruleanRed** [comment]
I've recently upgraded to Kodi v21 and this issue still persists, has there been any movement on this lately?

**Comment by damomato** [comment]
> I'm having a similar issue, where the first instance of up next works fine. But then after the second episode, it will oddly loop me back to the first episode instead of the third.  Strange stuff, but looks like the problem was identified by the Up Next dev?
> 
> Any updates on the issue on this end?

I'm having this problem too, has anyone created an Issue for it?

**Comment by Schaka** [comment]
I  came across this issue when trying to identify my issue.
Jellyfin 10.9.9, Jellyfin for Kodi 1.0.4 and Kodi 21.

When using the native Kodi functionality to automatically play the next episode, it never does anything. Using the Up Next plugin, I've not had any issues with it showing the pop up.

However, I've basically never actually gotten it to play the next episode. It shows the preview correctly and once I click on it to play the next episode, I see a pop up in the top right that the playlist item couldn't be found and nothing happens.

Is this related? Has anyone else experienced anything like it?

**Comment by tundrablasen** [comment]
> I came across this issue when trying to identify my issue. Jellyfin 10.9.9, Jellyfin for Kodi 1.0.4 and Kodi 21.
> 
> When using the native Kodi functionality to automatically play the next episode, it never does anything. Using the Up Next plugin, I've not had any issues with it showing the pop up.
> 
> However, I've basically never actually gotten it to play the next episode. It shows the preview correctly and once I click on it to play the next episode, I see a pop up in the top right that the playlist item couldn't be found and nothing happens.
> 
> Is this related? Has anyone else experienced anything like it?

I have a fairly similar setup. I never occurred on this issue again since it was fixed. Playing the next episode is/was rock solid recently. 

I’m using though jellyfin 10.9.8 and haven’t upgraded yet

**Comment by Schaka** [comment]
A clean install on Windows seems to not have any problems either. I'm going to see if I can figure out what setting my be breaking it or if there is anything I can to get it to work. I tried for a few hours on my Ugoos (CoreELEC, Kodi 21) device yesterday with no success, prompting me to ask here. 

Maybe I'll try completely building libraries from scratch.

**Comment by Schaka** [comment]
I was not able to get it to work.
Here's a log file from my Ugoos:
[kodi.log](https://github.com/user-attachments/files/16541832/kodi.log)

And here's one from my Windows machine, where things work
[kodi.old.log](https://github.com/user-attachments/files/16541853/kodi.old.log)

Hopefully any of this is helpful at all. I'll continue trying, but I'm unsure where to even look.

**Comment by Schaka** [comment]
A maintainer of Up Next responded here: https://github.com/im85288/service.upnext/issues/313

I have noticed that using the default skin, I don't seem to be getting that issue. I don't think it should matter. But atm, there's no way I can convince my family to use the default Kodi skin.

**Comment by CeruleanRed** [comment]
There seems to be a fix already committed [here](https://github.com/jellyfin/jellyfin-kodi/pull/899). You could try manually implementing the change via SSH, restarting, and see if that fixes your issue.
