### ISSUE TITLE
Multi-disc albums not shown correctly, include "disc 0" with all disc tracks

### ISSUE THREAD

**Issue by neightwulf** [jellyfin/jellyfin-kodi#732]
**Describe the bug**
Multi-disc albums are not represented correctly in Kodi. Kodi shows a "Disc 0" with all tracks from all discs, and "Disc X" for every disc >1 which does appear correctly, though there is no entry for "Disc 1".

**To Reproduce**
Import any multi-disc album in Kodi using jellyfin-kodi

**Expected behavior**
Each disc (including 1) should be represented separately. Kodi provides an "* All discs" view.

**Logs**
None

**Screenshots**
None

**System (please complete the following information):**
Android (Nvidia Shield), Jellyfin 10.8.10, Kodi 20.1, addon 0.7.10+py3, add-on playback mode

**Additional context**
Apologies, I have some dev experience but am not well-versed enough in Python, Kodi, nor Github to submit a fix myself. However was able to determine the problem and potential fix.

Column song.iTrack in the Music db, Kodi expects this value to be "disknumber *2^16 + tracknumber" (see post 4 from jmarshall, https://forum.kodi.tv/showthread.php?tid=194826).

Reviewing Kodi db populated by jellyfin-kodi suggests the formula above is only followed where discnumber >1. i.e. Disc one has iTrack values 1, 2, 3, etc., disc two has iTrack values 131073, 131074, 131075, etc.

Adding a multi-disc album directly in Kodi without use of jellyfin-kodi and reviewing db shows internally Kodi creates tracks on disc 1 in the manner described above, i.e. Disc one iTrack values are 65537, 65538, 65539, etc.

To test, modified jellyfin_kodi/objects/music.py on my Shield. Commented out line 294 and re-indented line 295:
`#       if obj['Disc'] != 1:`
`        obj['Index'] = obj['Disc'] * 2 ** 16 + obj['Index']`
Then repaired the music library and multi-disc albums now correctly display as disc 1,2,3,etc. with no errant "disc 0." This also did not break single-disc albums as Disc is explicitly set to '1' on line 283 if the field is not populated.

Please sanity-check me here but this appears to have resolved the issue for me.

**Comment by csaavedra** [comment]
I wrote a MR based on your investigation: https://github.com/jellyfin/jellyfin-kodi/pull/761
