### ISSUE TITLE
Jellyfin repo appears empty on Kodi 21 (Omega)

### ISSUE THREAD

**Issue by Moxh3** [jellyfin/jellyfin-kodi#736]
**Describe the bug**
Jellyfin repo appears empty on Kodi 21 (Omega), as such it is not possible to add the Video add-on.

**To Reproduce**
1. Install Jellyfin add-on repository on Kodi (repository.jellyfin.kodi.zip) as per https://jellyfin.org/docs/general/clients/kodi/
2. From within Kodi, navigate to "Add-on Browser"
3. Select "Install from Repository"
4. Choose "Kodi Jellyfin Add-ons"
5. Nothing there

**Expected behavior**
Expected to see the Video Add-ons folder and able to select and install the Jellyfin add-on.

**System (please complete the following information):**
 - OS: Fire TV
 - Jellyfin Version: 10.8.10
 - Kodi Version: 21
 - Addon Version: n/a
 - Playback Mode: Add-on

**Aditional context**
1. Modifying the info, checksum and datadir properties in addon.xml in repository.jellyfin.kodi.zip with the following, is a working workaround for the issue:
`<info compressed="false">https://repo.jellyfin.org/releases/client/kodi/py3/addons.xml</info>
 <checksum>https://repo.jellyfin.org/releases/client/kodi/py3/addons.xml.md5</checksum>
 <datadir zip="true">https://repo.jellyfin.org/releases/client/kodi/py3</datadir>`
2. Uninstall current Jellyfin Add-on repo from Kodi
3. Install the modified zip from step 1

**Comment by Moxh3** [comment]
On the Kodi forums, it is suggested that this issue is caused by the datadir in addon.xml in Jellyfin's repo add-on (repository.jellyfin.kodi.zip) pointing to https://repo.jellyfin.org/releases/client/kodi/* where it should be pointing to https://repo.jellyfin.org/releases/client/kodi/py3/*

**Comment by zaidranger** [comment]
Thanks for the workaroud

**Comment by oddstr13** [comment]
Sounds like the black magic used to sort python2 and python3 clients in the web server is failing for Kodi 21

**Comment by oddstr13** [comment]
It was indeed the black magic failing, @joshuaboniface has fixed it for us, so that it won't be an issue again for quite some time :rocket:

Black magic in question;
```nginx
location ^~ /releases/client/kodi {
    # Kodi 20          
    if ($http_user_agent ~* "(Kodi[A-Za-z]*/20\..*)") { 
        rewrite ^/releases/client/kodi/(.*)$ /releases/client/kodi/py3/$1 last;
    }

    # Kodi 19
    if ($http_user_agent ~* "(Kodi[A-Za-z]*/19\..*)") { 
        rewrite ^/releases/client/kodi/(.*)$ /releases/client/kodi/py3/$1 last;
    }                         
                                                           
    # Kodi 18 and older
    if ($http_user_agent ~* "(Kodi.*)") {
        rewrite ^/releases/client/kodi/(.*)$ /releases/client/kodi/py2/$1 last;
    }

    index index.html index.php;
    autoindex on;
}
```

Updated Kodi 20(+) block;
```nginx
# Kodi 20+                                                                                                                                                                                                                         
if ($http_user_agent ~* "(Kodi[A-Za-z]*/2[0-9]\..*)") {
    rewrite ^/releases/client/kodi/(.*)$ /releases/client/kodi/py3/$1 last;
}
```

The magic has been mentioned in this blog post before; [The Jellyfin CDN: Mirrorbits for the masses](https://jellyfin.org/posts/mirrorbits-cdn)
