### ISSUE TITLE
Steam Deck Kodi crash from game mode.

### ISSUE THREAD

**Issue by ShadwDrgn** [jellyfin/jellyfin-kodi#753]
**Describe the bug**

Kodi crashes shortly after launch (usually during library sync) very frequently on steam deck. Note that reopening Kodi after the crash always seems to result in a successful sync

**To Reproduce**

1. Go to 'Kodi' in game mode
2. Click on 'play'
3. Wait roughly 1 minute or less after kodi launches
4. Crash.

**Expected behavior**

Expect a successful sync and no crashes

**Logs**

Both debug and crashlog here:
https://cloud.1ez.us/index.php/s/wa7qcZapn4x4nBf

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: 10.8.10
 - Kodi Version: 20.2 Nexus (Flatpak) 6/28/23
 - Addon Version: 0.7.10+py3
 - Playback Mode: Addon

**Additional context**

**Comment by oddstr13** [comment]
I'm not seeing anything obviously wrong in the logs from our part, I recommend you get gdb working and submit that information in the upstream issue if it is still affecting you.

**Comment by oddstr13** [comment]
I wish I had a deck and could attempt to reproduce, but it is not for sale in my country unfortunately :crying_cat_face:
