### ISSUE TITLE
Out of memory when adding huge library of TV series to Kodi

### ISSUE THREAD

**Issue by haasviktor** [jellyfin/jellyfin-kodi#772]
**Describe the bug**
I have a huge children TV series library, about 3000+ items.
When I sync it to Kodi, it consumes all of my free memory 600MB and kodi hangs up.

**To Reproduce**
1. Set up a big library of TV series, 2000-3000+ item will be the best
2. Start to sync it
3. Check how it consumes your free memory in Kodi Settings - System info, till Kodi hangs up

**Expected behavior**
Consume way less memory and able to sync big library on low memory device (2GB ram) 

**Logs**
With Kodi info and Jellyfin-kodi debug level
[kodi.zip](https://github.com/jellyfin/jellyfin-kodi/files/12565816/kodi.zip)

**System (please complete the following information):**
 - OS: Android TV 11
 - Jellyfin Version: 10.8.9
 - Kodi Version: 21.0-ALPHA3 (20.90.301) Git:20230908-788e28c450
 - Addon Version: 0.7.11+py3
 - Playback Mode: Add-On

**Comment by haasviktor** [comment]
Hi,

With Kodi 20.2 there is no memory leak.
I don't know it's a kodi issue or the jellyfin addon has issue with the new kodi

**Comment by mcarlton00** [comment]
We support current Kodi and the previous one.  So in this case if there's an issue in Kodi 20 or 19 we can look into it, but with Kodi 21 still being in alpha state there's too many things changing and if we start chasing issues specific to it it's likely to just be wasted effort.  In this case, this sounds specifically like Kodi itself is using more memory in 21, as the addon has pretty heavy throttling already to prevent memory exhaustion (and I can sync thousands of things onto a 1GB raspberry pi 3b with no issues).

**Comment by oddstr13** [comment]
Closing as upstream issue from the context provided here
