### ISSUE TITLE
Mark as watched 2 accounts

### ISSUE THREAD

**Issue by DavidHenryThoreau** [jellyfin/jellyfin-kodi#782]
I'm using latest stable kodi jellyfin addon and latest jellyfin version, I'm watching files from shared library on kodi with as kodi user with restricted access read only.
I've got an admin account on the same groups that kodi user whith shared but the content i'm watching with kodi and admin is not shared (I mean percentage of the played video and mark as watch).

I'd like to use 2 accounts 1 on kodi and 1 to admin and mark as read to each other

**Comment by oddstr13** [comment]
If I am understanding you correctly, you want two separate Jellyfin users to have synchronized watched status?
That is out of scope for this client. Sounds like something best suited for a specialized plugin.
The Trakt plugin *might* help you achieve this behavior, in a very roundabout way, but is not ideal..

**Comment by DavidHenryThoreau** [comment]
> If I am understanding you correctly, you want two separate Jellyfin users to have synchronized watched status?
Yes

**Comment by oddstr13** [comment]
Out of scope for the Kodi addon

**Comment by mcarlton00** [comment]
Pretty sure this already exists actually.  If you open the addon there's an option called "Add user to session"

**Comment by oddstr13** [comment]
Heh, that's what that option is supposed to do?
