### ISSUE TITLE
Can't install repo from zip

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin-kodi#788]
**Describe the bug**
In kodi 20.2 + 21, I'm unable to use the `repository.jellyfin.kodi.zip` for installing the add-on

**To Reproduce**
1. Go to https://jellyfin.org/docs/general/clients/kodi/#install-add-on-repository
2. the zip file never shows up on the (usb)device, so can't install it

**Expected behavior**
The zip file should appears in the file browser

**Logs**
Nope

**Screenshots**
Nope, and not needed

**System (please complete the following information):**
 - OS: Android
 - Jellyfin Version: N/A
 - Kodi Version: 20.2 + 21.daily
 - Addon Version: N/A
 - Playback Mode: N/A

**Additional context**

**Comment by mcarlton00** [comment]
Those reproduction steps are less than helpful. 

Are you manually downloading the file and then can't find it on your device?  Because we really can't help much with this.  We can't tell you how to use a device we've never seen.  Are you trying to download it from the repo directly from within kodi?  This method should be pretty foolproof.

**Comment by oddstr13** [comment]
I can confirm that the reproduction steps are accurate. I visited the linked website, and the zip file did indeed not show up on the USB device – in fact, I'm not sure of where my USB stick even is… been a few months since I saw it last time.

**Comment by spirillen** [comment]
@oddstr13 you are right, all the steps are already written in the linked location. the process fails, when I'm trying to locate the zip on the locally attached usb device in that guide.

**Comment by oddstr13** [comment]
@spirillen You didn't actually provide any workable information in your issue report, I was sarcastically pointing out that simply visiting the website wouldn't make the file magically appear, further underlined by the fact that I didn't even know where my USB stick was at the moment.

There are multiple ways of installing listed on the website you're linking, did you try them all?

I've been told permissions might be an issue, can Kodi see the USB device at all?

**Comment by spirillen** [comment]
> further underlined by the fact that I didn't even know where my USB stick was at the moment

Don't worry I got that part :wink: but that doesn't change the fact you hit the nail whit you comment.

> There are multiple ways of installing listed on the website you're linking, did you try them all?

All of them: yes

> I've been told permissions might be an issue, can Kodi see the USB device at all?

Now it's my turn to be sarcastic... 

>>  the process fails, when I'm trying to locate the zip on the locally attached usb device

Leads me to believe I can access the device, but not see the file :smirk:

**Comment by oddstr13** [comment]
I'm unable to reproduce on my Android 13 phone with Kodi 20.2.0 from the Play store.
I don't have a USB-C stick to test with, but installing downloaded zip from the SD card works.
Installing using the add http folder method also works.

**Comment by spirillen** [comment]
this is not a phone... it is nvidia shield, but i'm guessing you don't care if jellyfin for kodi, actually can run on kodi ...

**Comment by oddstr13** [comment]
Of course I care, it is my main way of consuming video content after all.

You have not provided any information that would be necessary for attempting to reproduce the issue.

Both methods; installing the downloaded zip, and adding the website `https://kodi.jellyfin.org` as a browseable path in Kodi works for me.

The fact that you are using a Nvidia shield is new information, you only specified Android.

It is likely that Kodi does not have the required permissions to read your USB device (On android phone, it asked me for permission to access media files on first launch after install).

In any case, it is not an issue with this addon, but a more generic issue of your Kodi install not being able to see the file – at least with the information you've provided so far.

No code changes can be made in this repository to change this, and I've verified that the repository zip file still works with Kodi v20.

Please try the http method, and report back with Kodi logs and full version and environment info if this does not work for you.

**Comment by spirillen** [comment]
For others who stumble on this issue... here comes a few words of wisdom...

go to `Settings` -> `Apps` -> `Kodi` -> `Permissions` -> `Files and Media` and select `Allow all the time`.

This makes the zip file visible, maybe this should be added to the docs??
