### ISSUE TITLE
Fails to connect to IPv6 addresses directly

### ISSUE THREAD

**Issue by TrueTechy** [jellyfin/jellyfin-kodi#79]
**Describe the bug**
Addon cannot connect to server if given address is an IPv6 address

**To Reproduce**

1. Enter ::1 in host section
2. Click connect

**Expected behavior**
Addon connects to server

**Logs**
`InvalidURL: Failed to parse: http://::1:9898/emby/system/info/public`

**System (please complete the following information):**
 - OS: Ubuntu
 - Jellyfin Version: 10.4
 - Kodi Version: 18.3
 - Addon Version: 0.2.1

**Additional context**
Seem to be due to the request not properly encapsulating the IPv6 address since it has a port on it as well. Should be enclosed by square brackets [https://softwareengineering.stackexchange.com/questions/311413/how-should-we-represent-an-ipv6-address-with-port-number-in-text](https://softwareengineering.stackexchange.com/questions/311413/how-should-we-represent-an-ipv6-address-with-port-number-in-text)

**Comment by oddstr13** [comment]
Please test #103, it should solve this issue
