### ISSUE TITLE
jellyfin-kodi causes crash in Kodi after upgrading to Fedora 39

### ISSUE THREAD

**Issue by singularity098** [jellyfin/jellyfin-kodi#794]
After upgrading my system to Fedora 39, I am getting a crash when loading Kodi.  The logs indicate a problem with the jellyfin plugin... something about a python module six.moves.  The thing is, I've checked up and down that this module is in fact installed, so I don't understand the problem.  

I am using Jellyfin through RPMFusion, not a flatpak or anything.

 - OS: Fedora 39
 - Jellyfin Version: 10.8.13
 - Kodi Version: 20.2 from RPMFusion
 - Addon Version: 0.7.11

Attaching crash log.
[kodi_crashlog-20231202_091240.log](https://github.com/jellyfin/jellyfin-kodi/files/13536509/kodi_crashlog-20231202_091240.log)

**Comment by oddstr13** [comment]
Looks like it's related to https://github.com/dpkp/kafka-python/issues/2401

Possibly also https://github.com/benjaminp/six/issues/376

Looks like you've got six 1.15, while latest release (from 2021) is 1.16 (not yet in Kodi)

---

Upstream issue https://github.com/xbmc/repo-scripts/issues/2546
Upstream pullrequest https://github.com/xbmc/repo-scripts/pull/2547

**Comment by singularity098** [comment]
Thanks for the info!

It is strange, as it lists six 1.15 in the log as you point out, but my system has 1.16 as checked from the command-line.  I don't really get it but I'll just sit around and wait for it to work itself out.

```
~ $ pip3 freeze | grep six
six==1.16.0
```

**Comment by singularity098** [comment]
My issue has apparently been fixed and I'm back up and running.  I notice an updated "Six" in my Kodi plugins, which must be responsible for making it work again.  Thanks!
