### ISSUE TITLE
error <general>: CCurlFile

### ISSUE THREAD

**Issue by J666Z** [jellyfin/jellyfin-kodi#801]
**Describe the bug**
webdav http url synchronize past data and Kodi cannot recognize it

**To Reproduce**

1. Go to 'Media library for console'
2. Click on 'Add shared folder directory'
3. Scroll down to 'Add webdav HTTP address'

**Expected behavior**

**Logs**
error <general>: CCurlFile::Exists<dav://USERNAME:PASSWORD@192.168.x.x: xx/Movies/zh 2012 1080p.mkv> Failed: URIusing bad/illegal format or missing URL(3)

**Screenshots**

**System (please complete the following information):**
 - OS: [Android]
 - Jellyfin Version: [10.8.3]
 - Kodi Version: [21.x]
 - Addon Version: [0.7.9]
 - Playback Mode: [Native]

**Additional context**

**Comment by oddstr13** [comment]
I don't see how this error, or steps to reproduce are relevant for the jf4kodi addon.
