### ISSUE TITLE
Periodically Asked to Re-enter Login Details

### ISSUE THREAD

**Issue by wilsoniain** [jellyfin/jellyfin-kodi#827]
Not sure if this a bug or not. For the last few weeks I am periodically asked to login when loading kodi. Typically around every couple of days or so.

Initially, I thought this coincided with the latest release, but I rolled back and still had the same issue. I did a couple of library clean / refresh around the same time so possibly this may have caused it?

I have this happening on multiple Linux boxes. The behaviour suggests its possibly on the server side as all the boxes require reentering login details at the same time. Additionally, it happens for more than 1 user also.

Just wanted to see if anyone has encountered this before starting to investigate further.

`[2024-02-24 16:39:03.951 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:39:03.951 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:39:03.951 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.                                                                 [2024-02-24 16:42:55.199 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:42:55.199 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:42:55.199 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.                                                                 [2024-02-24 16:43:17.097 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:43:17.097 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:43:17.097 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.                                                                 [2024-02-24 16:47:30.471 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:47:30.471 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:47:30.471 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.                                                                 [2024-02-24 16:51:43.700 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:51:43.700 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:51:43.700 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.                                                                 [2024-02-24 16:55:56.969 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:55:56.969 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 16:55:56.969 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.                                                                 [2024-02-24 17:00:10.202 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 17:00:10.202 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."                                              [2024-02-24 17:00:10.202 +00:00] [INF] AuthenticationScheme: "CustomAuthenticat`

**Comment by wilsoniain** [comment]
Thought the same, need to understand why it doesn't happen to other sessions. Android for instance. Seemed exclusively for kodi.

**Comment by nanhoes** [comment]
having this issue as well

**Comment by oddstr13** [comment]
I have personally never seen this happen.
Is the addon data getting pruned for whatever reason?
That would explain why login would be required again. Does the addon generate new devices in the Jellyfin dashboard when you have to log in again? This would indicate that the addon's config files are getting deleted.

Need more information before I can look into this issue.

**Comment by wilsoniain** [comment]
I think I may have discovered some of the reason. I had jellycon installed but disabled. I uninstalled both kodi jellyfin and jellycon, removed all settings then reinstalled kodi jellyfin and seems to have no issue so far. Closing.
