### ISSUE TITLE
importing kodi playlists into jellyfin

### ISSUE THREAD

**Issue by wbravin** [jellyfin/jellyfin-kodi#828]
**Describe the bug**
<!--Hello all 
not able to import kodi m3u playlists into jellyfin 
**To Reproduce**
<!-- saved all kodi playlists in music dataset in a folder called playlists

jellyfin loads the playlist  folder items- and does display them under music playlist

when i try to play one of those playlists i get an this client is not compatible with the media....>

**Expected behavior**
<since both jellyfin and kodi uses m3u playlists format . i presume that jellyfin should play the playlists from kodi

**System (please complete the following information):**
 - OS:jellyfin installed as jail in truenas poxmox vm
  - Jellyfin Version: Version: 10.8.13
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]
 - Playback Mode: jellifin client native

i have about 163 playlist built in kodi.  built over 6 years. i would hate to have to start over from scratch

thank you

**Comment by oddstr13** [comment]
no actionable info provided
