### ISSUE TITLE
Is quick connect supported ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#838]
Hi,

It's all in the title, I would like to know if Jellyfin Quick Connect is supported with this addon or not. I couldn't find the answer.

This would be essential for my setup because I plan on using Jellyfin SSO for delegating login to Oauth2 from Zitadel, which means Quick Connect would be the only way to connect on Kodi as it can't support SSO.

Thanks in advance for any answer and have a great day

**Comment by mcarlton00** [comment]
You already commented on the original issue.  If it had been implemented already, that issue would have been closed.  Please don't waste our time by opening duplicates.

**Comment by LeVraiRoiDHyrule** [comment]
Hello to you too !

Thanks for the answer, have a pleasant day.
