### ISSUE TITLE
Constently missing TV episodes that are present in Jellyfin; do not show up in kodi with addon

### ISSUE THREAD

**Issue by GerbertBless** [jellyfin/jellyfin-kodi#845]
Been trying to transition to jelly fin for metadata and user management for kodi since its much better at it, but random TV shows seems to always be missing episodes and or entire seasons, despite these episodes appearing in jellyfin web client and showing up just fine when scanned in directly with kodi.

 It is the same shows every time and happens on both windows and Linux clients, even with no other addons installed. It is usually shows with larger episode counts. I have used south park as an example in the video below, but it is not the only one. What is especially odd is these episodes show up in jellycon with no problem. 

https://github.com/jellyfin/jellyfin-kodi/assets/84816266/f187a209-6da4-4e10-9e62-5939ca0fa332)

Some will flatten all the seasons into one and show a small range of episodes, others will maintain season hierarchy but just not show some seasons. I have fiddled around with this on clean installs on multiple devices and can't seem to figure out the problem. No error ever seems to be indicated. As far as I can tell, files are correctly named and organized, but even if that were the problem, it seems odd that a naming scheme accepted by both jellyfin and kodi on their own respectively would not work when  you combine them. 

 - OS: Both Windows and Linux clients
 - Jellyfin Version: 10.8.13 running on Debian
 - Kodi Version: 20.1
 - Addon Version: 0.7.11
 - Playback Mode: Add-On

**Comment by mcarlton00** [comment]
Are you sure you haven't toggled the "Flatten TV Shows" setting in Kodi?  That would cause the seasons behavior you're seeing (jellycon doesn't respect any of those settings, while jellyfin-kodi would).

If files were synced and no longer are, that means that the server has notified us that the item doesn't exist anymore.  We just act on what it tells us.  _Why_ the server would send a notification that a file doesn't exist anymore when it still does is another mystery entirely

**Comment by GerbertBless** [comment]
> Are you sure you haven't toggled the "Flatten TV Shows" setting in Kodi? That would cause the seasons behavior you're seeing (jellycon doesn't respect any of those settings, while jellyfin-kodi would).
> 
> If files were synced and no longer are, that means that the server has notified us that the item doesn't exist anymore. We just act on what it tells us. _Why_ the server would send a notification that a file doesn't exist anymore when it still does is another mystery entirely

As I said in my original post, other shows are fine and the flattening doesn't always occur. Sometimes I have an issue like the first few seasons not even showing up, but all the other seasons are always listed. There also was never a point where the files ever showed up in the kodi library through jellfyin-kodi. Many episodes just never show up, no matter how many times I do a fresh install of both kodi and the add-on.

**Comment by GerbertBless** [comment]
I am not sure what caused this issue, but I know now for sure that it isn't with the addon. I have completely redone the setup for my home servers and am now running jellyfin in an Ubuntu VM instead of Debian bare metal, and now everything shows up seamlessly without any changes to the kodi client other than the location of the jellyfin host. Its very odd to me since the jellyfin configuration, the media files, and how everything shows up in the jellyfin web ui are basically the same, but it is a server side problem. Sorry to waste your time.
