### ISSUE TITLE
Music videos library won't play

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin-kodi#847]
**Describe the bug**
For some reason, on one of my Amazon FireSticks, on both Kodi 19.5 and then now 20.5 (just installed), the music videos library won't play. All other libraries play successfully. However, on another FireStick I have, Kodi 19.4, Addon 1.0.1+py3, music videos play with no problem.

**To Reproduce**
1. Go to music videos library on Jellyfin for Kodi
2. Music videos don't play. It just says "Item failed to play. Check logs." or something similar. 

**Expected behavior**
Music video library should play

**Logs**
Kodi is on an Amazon FireStick, so I don't know how to obtain the logs.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: [Amazon FireStick]
 - Jellyfin Version: [10.8.13]
 - Kodi Version: [20.5]
 - Addon Version: [1.0.1+py3]
 - Playback Mode: [Add-On]

**Comment by mcarlton00** [comment]
You literally ignored the URL in the issue template telling you how to get logs: https://kodi.wiki/view/Log_file/Easy

**Comment by nothing2obvi** [comment]
Actually, I was able to add the `advancedsettings.xml` file using ADB. You dont need component-specific logging, right?

Anyway, I played one TV show just to make sure Jellyfin was working, then I attempted to play 3 music videos.

https://paste.kodi.tv/patolomufe

**Comment by mcarlton00** [comment]
You're not connected to your jellyfin server.  Or rather, your server isn't responding to the client requests.  If you take a scroll through your first log it's pretty clear there's connection issues.

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.94', port=8096): Max retries exceeded with url: /system/info/public (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c645df0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by nothing2obvi** [comment]
@mcarlton00 

But right before that I played an episode of a TV show from Jellyfin. On both logs.

**Comment by nothing2obvi** [comment]
I tried removing the library from Kodi, deleting the library from Jellyfin, adding the library back, and adding the new the library to Kodi, but it still won't play.

And to clarify, I can successfully play a TV show and a movie both before and after attempting to play music videos.

I installed the latest Kodi on another TV, with Jellyfin plugin, and I can play the music videos from that new library just fine. I'm not sure what's going on.

**Comment by oddstr13** [comment]
I am unable to reproduce on my system, Music videos play just fine (Kodi 20.3).
Both synced library, and via the non-synced menu.

Is the Jellyfin server showing anything in the logs when attempting to play back the music video? Is it different from playing other items that are successful?

Are you testing with the same file on all devices?  Library entries that don't exist on disk tend to show a generic error in Kodi (media drive not mounted on the server f.ex.)

**Comment by nothing2obvi** [comment]
So strange. I updated to the latest Kodi and it works now. It hasn't been working for over a year. Thanks to both of you for taking the time.
