### ISSUE TITLE
Issue with new dependencies in 0.3.0

### ISSUE THREAD

**Issue by ddurdle** [jellyfin/jellyfin-kodi#85]
I was using 0.2.1 prior on KODI 18.3. Trying to update to 0.3.0 and there is an unmet upgrade dependency on scripts request. Is this designed now only to work on KODI 18.6?

**Comment by ddurdle** [comment]
![image](https://user-images.githubusercontent.com/851508/65706088-b41bad00-e057-11e9-898b-c769b24e4e09.png)

**Comment by TrueTechy** [comment]
Hi there would you be able to upload your kodi.log for us to look at as it should work? 

Have you tried to reinstall the addon, sometimes it'll say it has this issue but when you install it again it works fine?

**Comment by ddurdle** [comment]
Yes, I had a better look, there are two issues.  script.module.dateutil-2.7.3 is listed as a dependency but this is not a standard-issue KODI file (at least in 18.3 that I'm running).  I resolved this by downloading script.module.dateutil-2.7.3.zip

The first error I got was about requests which is an older version in KODI 18.3.  I got past this by downloading script.module.requests-2.22.0.zip off some other repository.

I tried updating the repository.jellyfin and the depencies are not referenced there.  Normally for depencies not automatically provided by KODI, you'd referenced them in the repository file so that when someone installs the Jellyfin plugin from the repository, it will know how to fulfill the dependencies
.

**Comment by mcarlton00** [comment]
I'm fairly confident it's not an issue with 18.3.  I have three 18.3 boxes on my network right now, but only two of them work at this moment.  Can you either upload your `kodi.log` or look through it for a digest error?  I encountered a kodi bug on one system the other day while testing that i haven't had time to fully look into it yet.

My error looks like `ERROR: CRepository: http://mirrors.kodi.tv/addons/leia/addons.xml.gz index has wrong digest 5bab34754e325f68bb101fd4f670f2df6b752e95f6f3507109e61ac1e72248b8, expected: c28febbab2093983237e5902a873e38ac3301de9e84e70af110174cece6a6417`  Digging through the kodi forums looks like this was an issue in late 2018 with certain curl versions combined with certain 64 bit intel CPU architectures.

A few other answers to the questions from the issue template would be helpful.  What device/OS are you running kodi on?

**Comment by ddurdle** [comment]
Do you have lots of repositories installed?  I only have the emby, jellyfin and ddurdle repositories installed because I use this instance strictly for developing.  Your dependencies might be fulfilled by one of those other repositories.  

Kodi (18.3 Git:20190619-nogitfound). Platform: Linux x86 64-bit
Kodi compiled 2019-06-19 by GCC 8.3.0 for Linux x86 64-bit version 4.19.37 (267045)
 Running on Linux Mint LMDE 9.3, kernel: Linux x86 64-bit version 4.19.0-5-amd6

The log file got reset after I restarted when installing the dependencies from their zip files so the log is lost.  I attached the latest log anyways so you'll have the other info (like what addons were installed by KODI automatically)
[kodi.old.log](https://github.com/jellyfin/jellyfin-kodi/files/3659095/kodi.old.log)

**Comment by mcarlton00** [comment]
No.  I only have the default kodi and the jellyfin repos installed.  3 mirror image boxes, only difference is cpu architecture.  That's why I'm curious if you were seeing the same error.

**Comment by TrueTechy** [comment]
@ddurdle

Both of those libraries are in the standard kodi leia repository at those version as you can see at:


https://mirrors.kodi.tv/addons/leia/script.module.requests/

And

https://mirrors.kodi.tv/addons/leia/script.module.dateutil/


Kodi will automatically pull these in when they're listed as depencies in the addon data file. Plenty of installs of the addon at the latest version have been successful with just the kodi and jellyfin repo installed. Sometimes it fails which seems to be a kodi bug but the addon will normally install fine

However since you got your install sorted there's nothing further to be done here.

**Comment by oddstr13** [comment]
Awesome! I was having this issue when I first attempted the dependency change a couple of months back, in my dev setup (direct git repo). I didn't have time to investigate further back then, and prioritized other issues, but the fact that you are seeing the same problem with a install from the main repos confirms it wasn't just a me-issue.

**Comment by mcarlton00** [comment]
@oddstr13 have you had a chance to test the new release?  I'm curious how widespread it is.  Also, what CPU do you have?

**Comment by oddstr13** [comment]
You're in luck, as I'm going back home for fall break tomorrow. The CPU is a few years old i7 something K, I'll dump cpuinfo when I'm back home.

On September 26, 2019 8:36:37 PM UTC, mcarlton00 <notifications@github.com> wrote:
>@oddstr13 have you had a chance to test the new release?  I'm curious
>how widespread it is.  Also, what CPU do you have?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jellyfin/jellyfin-kodi/issues/85#issuecomment-535676091

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oddstr13** [comment]
I'm not currently seeing this issue on my own system.
Kodi 17.6 on Mint (Ubuntu)
```
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
stepping	: 9
microcode	: 0xb4
cpu MHz		: 4400.030
cache size	: 8192 KB
```

**Comment by TrueTechy** [comment]
So it seems that the scripts.module.request library we get from kodi has an old version of certifi as a requirement for its installation and sometimes kodi doesn't like this and refuses to install thus the dependency error for requests whilst other times it ignores the version string in the addon.xml file and installs the newer version of certifi available from the kodi repo 

```
> 2019-10-02 02:11:38.137 T:140027879225088   ERROR: CCurlFile::Open failed with code 404 for https://mirrors.kodi.tv/addons/leia/script.module.certifi/script.module.certifi-2019.3.9.zip:
> 2019-10-02 02:11:38.137 T:140027879225088   ERROR: Could not fetch addon location and hash from https://mirrors.kodi.tv/addons/leia/script.module.certifi/script.module.certifi-2019.3.9.zip
> 2019-10-02 02:11:38.137 T:140027879225088   ERROR: CAddonInstallJob[script.module.certifi]: failed to resolve addon install source path
> 2019-10-02 02:11:38.138 T:140027879225088   ERROR: CAddonInstallJob[script.module.requests]: failed to install dependency script.module.certifi
> 2019-10-02 02:11:38.139 T:140027879225088   ERROR: CAddonInstallJob[plugin.video.jellyfin]: failed to install dependency script.module.requests
```

**Comment by oddstr13** [comment]
This should probably be reported upstream then

**Comment by TrueTechy** [comment]
> This should probably be reported upstream then

I have done so and made a PR to update it to the latest but so far no response 

https://github.com/Freso/script.module.requests/pull/26

**Comment by TrueTechy** [comment]
Given that this seems to be an issue with how Kodi handles upgrades and not something we can catch in the code for given the research @mcarlton00 done for the latest update with a similar issue, there's nothing really we can do about this except tell the user to restart Kodi
