### ISSUE TITLE
Favourite Movies/Shows/Episodes bug

### ISSUE THREAD

**Issue by ddurdle** [jellyfin/jellyfin-kodi#86]
I favourited (hearted) a few movies, shows and episodes of shows.  They show up in JellyFin via the web app under "favourite movies", "favourite shows", "favourite episodes".  Only favourite episodes via the plugin work.  The other two -- favourite movies and favourite shows -- are blank.

**Comment by mcarlton00** [comment]
I can't seem to replicate this in my normal usage.  I am, however, seeing it when there's an apostrophe in the library name (eg, `ddurdle's shows` or `kid's movies`).  In which case this is likely related to #87 as well.

@ddurdle can you confirm if you have apostrophe's in your library names?

**Comment by mcarlton00** [comment]
I've received multiple reports on reddit of this working as expected, as well as being unable to reliably reproduce a failure on my own systems.  Closing
