### ISSUE TITLE
Verify addon works with apostrophes in library names

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#87]
**Describe the bug**
Mentioned by /u/Quixventure on reddit.

"Also, for library issues, I found that if I had an apostrophe (like "Kid's Movies") in the name of my share in Jellyfin, the Kodi client would sync all the data and it would be accessible, but the virtual source would appear empty. You could see stuff in "movies" but not in the Jellyfin add-on>Kid's Movies"

"It was a while ago, and I just renamed my folders, but it could be an issue causing others to see nothing depending on how they are configured."

**System (please complete the following information):**
 - Jellyfin Version: any?
 - Kodi Version: any?
 - Addon Version: any?

**Comment by TrueTechy** [comment]
Issue confirmed, nothing wrong showing up in the logs even with debug turned on

**Comment by steelhands** [comment]
Hi, I have a similar problem, updating the addon to 0.3.4 has stopped synchronizing the progress of some episodes.  just mark it as seen.


Jellyfin version: 10.4 (docker on coreelec)
Kodi version: 18.4 (Last coreelec)
Addon version: 0.3.4

**Comment by loidy** [comment]
I will try to solve this issue.

**Comment by mcarlton00** [comment]
I think I've tracked this down to the XML file handling for each library.  The files get stored in `$HOME/.kodi/userdata/library/video/` and when looking inside of them the labels don't match.

For example, `mcarlton's shows` gets changed to `mcarlton"s shows` inside the files
