### ISSUE TITLE
Incremental sync doesn't complete

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-kodi#88]
**Describe the bug**
The periodic scans that kodi does (or are triggered by the kodi sync companion plugin) never complete.  The library seems to sync 1 item, and then freezes on the rest.

**To Reproduce**
1. Do initial sync with server
2. Edit metadata on server somehow (new items, changed images, etc)
3. Wait for next sync

**Expected behavior**
Sync works fully

**Logs**
Nothing useful yet, more debugging needed

**System (please complete the following information):**
 - OS: All
 - Jellyfin Version: All
 - Kodi Version: All?
 - Addon Version: 0.3.0

**Comment by stewood** [comment]
I am having the same issue.
