### ISSUE TITLE
Website Documentation Error

### ISSUE THREAD

**Issue by ZaxLofful** [jellyfin/jellyfin-kodi#931]
On the documentation website, there is an error with the installation procedure. I have been trying to get it installed for a while, and it would not proceed.

https://jellyfin.org/docs/general/clients/kodi/

It reads that you need to use this connection string: `https://kodi.jellyfin.org`

When you actually need (note the trailing slash): `https://kodi.jellyfin.org/`

If you don't add the trailing slash, the Kodi interface on the Firestick, doesn't allow you to highlight the "OK" button or proceed.

**Comment by mcarlton00** [comment]
I can't replicate this on any of my machines.  Putting in just the URL without a slash works as intended.  Seems like Kodi must do it automatically if it detects the remote destination is a directory and not a file, as when I go back to edit the source it does have a trailing slash.  Either way, if you feel like it's incorrect and want it changed, docs are open source and available in this repo: https://github.com/jellyfin/jellyfin.org
