### ISSUE TITLE
Wrong song url in "recently added albums"

### ISSUE THREAD

**Issue by jeweet** [jellyfin/jellyfin-kodi#936]
Running the addon in Native mode, the url's of the songs in "recently added albums" are incomplete.

They start with the path, missing the server part. For example /storage/music/album/song.flac instead of nfs://192.168.1.1/storage/music/album/song.flac

I'm running:
LibreELEC 12.0.1
Kodi 21.1
Jellyfin for Kodi 1.0.5+p3

**Comment by mcarlton00** [comment]
Native mode no longer functions starting in version 10.10.0 of the server unless you're running the fork in this PR #926, which restores functionality in a very limited interpretation
