### ISSUE TITLE
[Discussion]

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin-kodi#961]
Sorry I know this is more of a discussion, but what is the proper way to completely uninstall the plugin and remove any media from Kodi? I've performed "Local database reset" but I still have media left over. And if I connect to a new server, it adds that media in addition to the old media, resulting in duplicate media.

I'm just wondering because I had to switch servers and I have four other TV's to do this switching process on. I'd appreciate any advice. Thanks!

**Comment by oddstr13** [comment]
the database reset option *should* be outright deleting the whole database. you could try deleting the kodi app data.

it re-adding the media afterwards shouldn't happen unless you actually add the relevant library again.

**Comment by nothing2obvi** [comment]
Right yeah I'm adding the relevant library again. Okay, I'll try deleting the Kodi app data if the database reset doesn't remove everything. Thanks!
